### PR TITLE
Fix the json parsing error when deploying the template from the portal

### PR DESCRIPTION
**Pull request by Yvand**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Fix the json parsing error when deploying the template from the portal

### CODE REVIEW

**Comment by Yvand** [comment]
@alex-frankel I completely overlooked this json parsing error because I always test deployments using script/command line, sorry for that:
image


IMO it is a bug in the portal's json parser since the validation is successful when using script/command line.

**Comment by alex-frankel** [comment]
To make sure I understand, the issue is the newline characters?

**Comment by Yvand** [comment]
@alex-frankel yes, somehow the parsing fails if the content is split into multiple lines

**Comment by Yvand** [comment]
@alex-frankel the tag `sharepoint` which I added to the README file was again deleted (commit f8ed6543705f3819d3c0f03744ac27dfe540bfc9)
Is it possible to add this tag to this template?

**Pull request merged**
