### PR TITLE
SFI update IP addresses

### PR DESCRIPTION
**Pull request by greg-lindsay**
I am updating the public IP addresses in this template to mock addresses per SFI guidelines.

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@duongau - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by greg-lindsay** [comment]
#sign-off

**Comment by duongau** [comment]
#sign-off

**Comment by azure-quickstarts** [comment]
@duongau - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Pull request merged**
