### PR TITLE
Force new storage account to be lower case

### PR DESCRIPTION
**Pull request by gbowerman**
Avoid the possibility of a broken mixed or upper case storage account
being created by changing user parameter value to lower case.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gbowerman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (guybo). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@gbowerman looks good. While you are working on this can you rename all variables that follow the my<something> convention to minecraft<something>. That way anyone who lists resources in Portal (VNETs) for e.g. doesn't see a bunch of myVNET after deploying many templates from here.

**Comment by gbowerman** [comment]
@singhkay updated variables to "minecraft" convention.

**Comment by singhkay** [comment]
Thanks Guy! merged

**Pull request merged**
