### PR TITLE
IBM Cloud Pak for data 3.0 update 

### PR DESCRIPTION
**Pull request by praveshhibm**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by praveshhibm** [comment]
@bmoore-msft  
Hi Brian,
I'm getting this error:
`Subscription has reached the limit on the number of App Service Domain resources it can create. Please contact support if you want to increase the limit.`

Please let us know if you can increase the limit..

**Comment by bmoore-msft** [comment]
@praveshhibm - not sure what happened with the limit error, but looks like we go past that (now a bug in the template).

**Comment by bmoore-msft** [comment]
@akinfemi @praveshhibm - l ran 2 tests overnight... both failed at the same point in the bastion node extension:

2020-08-13 13:10:07 (140 MB/s) - ‘/home/bmoore/.openshift/openshiftfourx/px-install.yaml’ saved [601/601]

--2020-08-13 13:10:07--  https://stage0cec70902e084498933.blob.core.windows.net/ibm2-stageartifacts/scripts/px-storageclasses.yaml?sv=2019-02-02&sr=c&sig=8CEPYumsl%2BK09TlBx5PN0%2BiCl%2B%2FB3FhIJEXD1AZzJ8k%3D&se=2020-08-13T16%3A28%3A21Z&sp=r
Resolving stage0cec70902e084498933.blob.core.windows.net (stage0cec70902e084498933.blob.core.windows.net)... 13.93.168.80
Connecting to stage0cec70902e084498933.blob.core.windows.net (stage0cec70902e084498933.blob.core.windows.net)|13.93.168.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6069 (5.9K) [application/octet-stream]
Saving to: ‘/home/bmoore/.openshift/openshiftfourx/px-storageclasses.yaml’

     0K .....                                                 100% 1.18G=0s

2020-08-13 13:10:07 (1.18 GB/s) - ‘/home/bmoore/.openshift/openshiftfourx/px-storageclasses.yaml’ saved [6069/6069]

error: must specify one of -f and -k

**Comment by akinfemi** [comment]
@bmoore-msft I added the storageOption override. could you please try again?

**Comment by bmoore-msft** [comment]
Sure, but doesn't that mean the other path will still fail?

**Comment by akinfemi** [comment]
No, because selecting Portworx means the user should also enter the pxSpecUrl variable. The current failure is because that variable wasn't supplied and Portworx was chosen.

**Comment by bmoore-msft** [comment]
ok, we should change the defaultValue then

**Comment by akinfemi** [comment]
@bmoore-msft done

**Comment by bmoore-msft** [comment]
merged

**Pull request merged**
