### PR TITLE
Update mongodb replica set and sharding templates

### PR DESCRIPTION
**Pull request by 251744647**
Fix the zabbixserver value is empty bug, and unify the azure and mooncake templates together. So that one template can work for azure and mooncake both.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@251744647__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by 251744647** [comment]
@singhkay Could you please help to check the PR, thanks! Got below 404 error.

Server Error:{

 "statusCode": 404,

"body": "<!DOCTYPE html>\n<html>\n<head>\n  <style type=\"text/css\">\n  body { text-align:center;font-family:helvetica,arial;font-size:22px;\n    color:#888;margin:20px}\n  #c {margin:0 auto;width:500px;text-align:left}\n  </style>\n</head>\n<body>\n  <h2>Sinatra doesn&rsquo;t know this ditty.</h2>\n  \n  <div id=\"c\">\n    Try this:\n    <pre>post '/validate' do\n  \"Hello World\"\nend\n</pre>\n  </div>\n</body>\n</html>\n",

**Comment by 251744647** [comment]
@singhkay Could you please help to check the PR, thanks! Got 404 error.

**Comment by bingosummer** [comment]
@251744647 
I got an exactly same error. I added a minor change to my codes to trigger a new CI build. Now the CI passes.
https://github.com/Azure/azure-quickstart-templates/pull/2170

You can have a try.

**Comment by 251744647** [comment]
@bingosummer Yes, you are right, CI passed. Thank you!

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
