### PR TITLE
Adding Integration Service Environment template

### PR DESCRIPTION
**Pull request by nzthiago**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

* Created template for Integration Service Environment
* Added GEN-UNIQUE to parameters
*

### CODE REVIEW

**Comment by nzthiago** [comment]
Note for reviewer: Integration Service Environments take normally between 1.5 to 2 hours to deploy, so the automated check failed as it seems to have a 1 hour limit.

**Comment by nzthiago** [comment]
The Integration Service Environment puts a  subnet delegation on the first subnet of the VNET and the resource group fails to be deleted (I ran into this while testing as well). Seems like an ARM bug as it should know to delete the ISE first, then the subnet delegation, then the VNET...

**Comment by bmoore-msft** [comment]
Can you add some instructions to the readme on how to delete the resources/resourceGroup?

**Comment by nzthiago** [comment]
@bmoore-msft great idea, I was thinking about that late last night. Added instructions

**Comment by nzthiago** [comment]
@bmoore-msft as discussed it failed on the cleanup step but I added notes to readme to help mitigate. Let me know if there are any other changes needed, thanks

**Pull request merged**
