### PR TITLE
Added Support for UbuntuServer 16.04.0-LTS and latest docker, docker-machine and docker-compose on all

### PR DESCRIPTION
**Pull request by dwaiba**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
* Added Support for UbuntuServer 16.04.0-LTS besides CentOS 6.5, 7.1, 7.2 and latest docker, docker-machine and docker-compose on all
* Made NFS4 Mount striped disks resilient and available on restart auto mounted.
* General Package install cleanup
* Docker now 1.12-1 with Swarm Mode

### Description of the change
Added Support for UbuntuServer 16.04.0-LTS CentOS 6.5, 7.1, 7.2 and latest docker, docker-machine and docker-compose on all. NFS4 MDADM RAID0 array now resilient and available automounted on reboots with zero Message Loss

### CODE REVIEW

**Comment by dwaiba** [comment]
@singhkays Requesting LGTM as this is multi distro support for RAID0 MDADM Array (striped disks)  and latest docker on all. Thanking You in  advance.

**Comment by dwaiba** [comment]
@ahmetalpbalkan For #2340 Added as part of PR #2439

**Comment by dwaiba** [comment]
Requesting LGTM post check and merge to master @singhkays  @bmoore-msft  @gatneil  @gbowerman  @marcvaneijk  @philon-msft  @simongdavies

**Comment by philon-msft** [comment]
LGTM

**Comment by gatneil** [comment]
Looks good to me as well; merging

**Pull request merged**
