### PR TITLE
Making changes to LoadBalancer and Gateway Server NIC settings to accommodate HA functionality

### PR DESCRIPTION
**Pull request by navesh**
HA functionality is being provided by another template. Some changes are
required in Loadbalancer and GW NIC settings for these three basic
templates to accommodate the HA functionality being provided by the HA
template.
Few changes have been made to LoadBalancer and gateway NIC settings to
accommodate the HA functinality.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@navesh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@navesh__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by singhkay** [comment]
@MahendraAgrawal As the author, can you review this change?

**Comment by singhkay** [comment]
expected templates failing, merged

**Pull request merged**
