### PR TITLE
MOVE: 101-signalr to quickstarts\microsoft.signalrservice

### PR DESCRIPTION
**Pull request by akhilthomas011**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@juniwang - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@mumian - this appears to be a "Move" that will need a manual doc update

**Comment by azure-quickstarts** [comment]
@tfitzmac - this appears to be a "Move" that will need a manual doc update

**Comment by mumian** [comment]
@juniwang, @tfitzmac - I will take this one.

**Comment by mumian** [comment]
I have created a local branch for this called 0511-quickstarts-signalr

**Comment by juniwang** [comment]
Thanks for reaching me. Yes we need to a manual [doc ](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-azure-signalr-service-arm-template?tabs=azure-portal)update. Should we update doc now or after this PR completed?

**Comment by mumian** [comment]
https://github.com/MicrosoftDocs/azure-docs-pr/pull/158325

**Comment by mumian** [comment]
@juniwang - I will take care of this.  A PR has been created.

**Comment by juniwang** [comment]
cool, thanks

**Pull request merged**
