### PR TITLE
Add Elementrem SmartContract on ubuntu vm

### PR DESCRIPTION
**Pull request by elementrem**
### Contributing guide

https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md
### Description of the change
- Provide a `private` and `public` elementrem smartcontract  
- Create unique Private block for users.

`include operation manuals`
- T/RX Element Lab
- Deploying a simple contract Lab
- Elementrem meteor wallet Lab – Step by Step

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@elementrem__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@elementrem__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by elementrem** [comment]
Please give favourable consideration to this PR.
Thanks.

**Comment by elementrem** [comment]
Am I missing something important? I'm still awaiting a response.
Please do not hesitate to contact me if you have any queries, request.
Thanks, @singhkays  @gatneil  @bmoore-msft

**Comment by elementrem** [comment]
Hello, Is anybody here?
I feel like I’m invisible man. Do I have to with the avengers help save the earth?

**Comment by elementrem** [comment]
Can someone remind me what I should do next?

**Comment by gatneil** [comment]
Hello! Thanks for your PR. We'll get to it as soon as we can :)

**Comment by elementrem** [comment]
@gatneil : Thank you for your reply. If you have any instructions, please feel free to contact me at any time.

**Pull request closed without merging**
