### PR TITLE
Update azuredeploy.json

### PR DESCRIPTION
**Pull request by vhorne**
requestRoutingRules priority is required now.

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Review by bmoore-msft — CHANGES_REQUESTED** [review]
This change needs to be made in bicep - azuredeploy.json will be updated automatically.

Also need to update the dateUpdated in metadata.json

**Comment by azure-quickstarts** [comment]
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by vhorne** [comment]
@bmoore-msft 
OK, but the bicep file was previously updated and included this change, yet I still have a busted azuredeply.json file that customers are complaining about. Thus, my attempt to directly fix the azuredeploy.json file./

**Comment by bmoore-msft** [comment]
We recently started generating `azuredeploy.json` during CI, so it's going to get overwritten anyway.  We have been seeing problems with CI not executing, but in those cases another PR to bicep (or any other file in the sample) is the current workaround.

If you just change the json, we have no idea what's going to happen as a result of the PR...

**Comment by vhorne** [comment]
Closing to open another PR in attempt to get an updated auto-generated auzuredeploy.json file

**Pull request closed without merging**
