### PR TITLE
WAF (v2) with APIM internal and SSL certificates

### PR DESCRIPTION
**Pull request by dcuenot**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

* Initial Version
* Deploy an Internal APIM, with WAF v2 and SSL endpoints
* Prerequisites : DNS zone and the associated certificate in a Keyvault
* APIM is bound to a App Insights
* APIM and WAF logs are sent to a Log Analytics
* NSG rules are defined for both subnets

### CODE REVIEW

**Comment by dcuenot** [comment]
Hello,
I'm not sure to understand why pipelines are failing.

Could someone give me some hints to better understand what's happening and how could I fix it?

Thanks in advance
Damien

**Comment by dcuenot** [comment]
For the unit tests, I need to simulate the generation of a Wildcard Certificate, but I don't find a way to do it.

Can I get some help?

thanks

**Comment by bmoore-msft** [comment]
@dcuenot - can you provide instructions on how to create such a cert in the readme?

**Comment by dcuenot** [comment]
> @dcuenot - can you provide instructions on how to create such a cert in the readme?

I added a link to the Azure tutorial to create the wildcard certificate, inside the README.

**Comment by bmoore-msft** [comment]
@dcuenot -  thanks - it looks like we could add the cert creation to the prereq template - can you think of any reason why that wouldn't work (i.e. is there a long delay before the cert is available)?

**Comment by bmoore-msft** [comment]
Closing abandoned request

**Pull request closed without merging**
