### PR TITLE
Updates ARM template files - Data Factory

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template used in ARM template [quickstart](https://docs.microsoft.com/azure/data-factory/quickstart-create-data-factory-resource-manager-template) article.
- Updates `docOwner` in _metadata.json_ with quickstart article's `author`.
- Updates _README.md_ with link to the quickstart article.
- Fixes template property order based on best practices guidance.
- Changes template indentation from tabs to spaces.

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@djpmsft - check this PR for updates that may be needed to documentation that references this sample.

**Comment by djpmsft** [comment]
#sign-off

**Comment by bmoore-msft** [comment]
@djpmsft - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
@djpmsft I removed an existing blank line that was in the template after Line 179.

**Pull request merged**
