### PR TITLE
Truncate netbios name to 15 characters

### PR DESCRIPTION
**Pull request by TheJeremyGray**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

* This uses the DomainNetBIOSName parameter to make sure that the netbios name does not exceed 15 characters.  If this is not provided it defaults to the domain name, if the domain name exceeds 15 characters there will be an error when trying to create the AD forest.  Error message below. 
*
*

"message":  "VM has reported a failure when processing extension 'CreateADForest'. Error message: \"DSC Configuration 'CreateADPDC' completed with error(s). Following are the first few: Verification of prerequisites for Domain Controller promotion failed. The NetBIOS name \"012345678901234567890\" is too long. The maximum length is 15 characters.\r\n The PowerShell DSC resource '[xADDomain]FirstDS' with SourceInfo C:\\Packages\\Plugins\\Microsoft.Powershell.DSC\\2.22.0.0\\DSCWork\\CreateADPDC.0\\CreateADPDC.ps1::81::9::xADDomain' threw one or more 
non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details. The SendConfigurationApply function did not succeed.\".

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TheJeremyGray__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@TheJeremyGray__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by mmarch** [comment]
@TheJeremyGray, @bmoore-msft  Jeremy, what where you thinking when you did this change?  
I urge you to revert it asap because you broke everything.

**Comment by TheJeremyGray** [comment]
https://github.com/Azure/azure-quickstart-templates/pull/3159

https://github.com/Azure/azure-quickstart-templates/issues/3148

**Pull request merged**
