### PR TITLE
Several network fixes

### PR DESCRIPTION
**Pull request by FrankSiegemund**
This pr addresses several issues:
1. references to lb appeared at wrong place
2. addressing issues with dependsOn
3. chose right data type for some fields
4. make network elements according to JSON schema (for example, for naming)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@FrankSiegemund__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (franksie). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
Thanks for fixing @FrankSiegemund! merged

**Comment by FrankSiegemund** [comment]
@DeepakRajendranMsft @ypitsch

**Comment by ypitsch** [comment]
good, thanks!

**Pull request merged**
