### PR TITLE
Update Stratis

### PR DESCRIPTION
**Pull request by sigwo**
### Changelog

* Added Stratis to `commandToExecute`

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sigwo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by sigwo** [comment]
It didn't even add in the change for the check...Will mod something else to kick the process off again....

**Comment by sigwo** [comment]
Travis checks do not take into account the drop down selections, thus my build (Stratis) is failing, but the errors are in the `bigchaindb` build procedure. Please either revert to non-aggregated templates or merge this PR so my community can utilize Stratis Azure BaaS. Thanks!

https://travis-ci.org/Azure/azure-quickstart-templates/builds/177863479
https://travis-ci.org/Azure/azure-quickstart-templates/builds/180079257

**Comment by gatneil** [comment]
looks good to me; merging

**Pull request merged**
