### PR TITLE
Lower default gap between master and worker node ip addresses and new disk mount logic

### PR DESCRIPTION
**Pull request by netwmr01**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
* Lower the default gap to better accommodate small subnet
* New mount logic

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@netwmr01__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by netwmr01** [comment]
@kmouss @singhkay 
I think the CI failed for quota check, can someone rerun the CI test and merge this PR please?

**Comment by gatneil** [comment]
@netwmr01 @kmouss 
The Travis CI is failing with an error about storage accounts; this should probably be fixed before merging, unless this error is expected?

**Comment by netwmr01** [comment]
@gatneil @kmouss 
The actual for this pull is https://travis-ci.org/Azure/azure-quickstart-templates/builds/129995174

also for the storage account, I believe that is Azure platform bug, which should be fixed by Azure
"Deployment provisioning state was not successful\nThe resource operation completed with terminal provisioning state 'Failed'.\nStorage account mdcsimageeastus2762 doesn't belong to subscription f42b4319-067a-4548-a650-33a1553b3a42.\nThe resource operation completed with terminal provisioning state 'Failed'.\nStorage account mdcsimageeastus2762 doesn't belong to subscription f42b4319-067a-4548-a650-33a1553b3a42.\nThe resource operation completed with terminal provisioning state 'Failed'.\nStorage account mdcsimageeastus2762 doesn't belong to subscription f42b4319-067a-4548-a650-33a1553b3a42.\n"


So for now, let's rerun the CI and see.

**Comment by netwmr01** [comment]
@kmouss @gatneil 
other backend errors
Server Error:{
    "error": {
        "code": "ENOTFOUND",
        "errno": "ENOTFOUND",
        "syscall": "getaddrinfo",
        "hostname": "arm-validator.40.118.211.57.xip.io"
    }
}

**Comment by netwmr01** [comment]
@kmouss @gatneil @singhkay can I get a merge on this?

**Comment by singhkay** [comment]
@netwmr01 Thanks for the ping. merged.

**Pull request merged**
