### PR TITLE
Dynamic Web Test Creation

### PR DESCRIPTION
**Pull request by sedouard**
Create any number of App Insights web (ping) tests by specifying a list
of test descriptor objects.

### CODE REVIEW

**Comment by singhkay** [comment]
@template-deploy-bot test this please

**Comment by sedouard** [comment]
repro command? what were the provided parameters?

**Comment by singhkay** [comment]
@sedouard The bot just took in the parameters file in this PR https://github.com/sedouard/azure-quickstart-templates/blob/dyn_web_tests/201-dynamic-web-tests/azuredeploy.parameters.json

**Comment by sedouard** [comment]
Got it. It's a unique parameter issue. Does the `####` logic work here for any field in a complex parameter object? Or does it only work for:

```
"value": "####"
```

**Comment by sedouard** [comment]
@template-deploy-bot test this please

**Comment by singhkay** [comment]
@sedouard should work for any. All it does is a string replace. Also the bot takes in a whitelist of admins for the test command :)

@template-deploy-bot test this please

**Comment by sedouard** [comment]
I thought so but I might as well give a try. No logs, or diagnostics on this thing :-(. I'm only interested in seeing the rendered template parameters.m that it used.

Overall this bot isn't proving to be very contributor-friendly.

Sent from Outlook<http://aka.ms/Ox5hz3>




On Tue, Dec 8, 2015 at 4:19 PM -0800, "Azure Quickstarts Template Deployment Bot" <notifications@github.com<mailto:notifications@github.com>> wrote:


Template deployment ran into an error. Please fix the below reported error and update the current Pull Request.

Failed template: 201-dynamic-web-tests

-

**Comment by singhkay** [comment]
@sedouard Ya this is strange, it's supposed to report back the error it got back from the service. Will need to investigate

**Pull request closed without merging**
