### PR TITLE
order the properties

### PR DESCRIPTION
**Pull request by mumian**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@mumian - any ideas what the error in Fairfax is caused by?

**Comment by mumian** [comment]
@bmoore-msft - The error message is "Update/create is not available for this subscription using the 2020-05-01 API version.".  API 2018-07-01 works fine.

**Comment by bmoore-msft** [comment]
Should probably file a ticket on it...

**Comment by mumian** [comment]
@IngridAtMicrosoft - Hi Ingrid, can you take a look at this issue?

**Comment by IngridAtMicrosoft** [comment]
@mumian I am not sure what is going on with this, but I did talk with Michael before I went on vacation.  I can probably get to it by the end of the week.

**Comment by mumian** [comment]
@bmoore-msft - can you take a look of this PR?  I reran the PR.  The PR has passed the validation process.

**Pull request merged**
