### PR TITLE
201 web app python

### PR DESCRIPTION
**Pull request by DarqueWarrior**
Adding a template that will create an Azure Web App with Python configured.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DarqueWarrior__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@DarqueWarrior Can you sign the CLA?

**Comment by DarqueWarrior** [comment]
Can you please send me the Details again. I searched like crazy for the
email you sent me in the past and could not find them.

Thank you so much for reaching out because I have other templates I would
like to submit but not sure even how to correct why this PR failed.  Is it
because of the CLA?

On Mon, Jun 13, 2016 at 10:43 AM, Kay Singh <notifications@github.com>
wrote:

> @DarqueWarrior <https://github.com/DarqueWarrior> Can you sign the CLA?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Azure/azure-quickstart-templates/pull/2007#issuecomment-225655170>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADrMXYhSO_WOS8mMBlY3qoFKLlrJQKqeks5qLZbcgaJpZM4ImRmw>
> .
>



-- 
Take care,
Donovan L Brown

**Comment by singhkay** [comment]
@DarqueWarrior Sent email again

**Comment by azurecla** [comment]
Hi __@DarqueWarrior__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (dbrown). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
