### PR TITLE
Added note related to depreciate of this template

### PR DESCRIPTION
**Pull request by rbinrais**
### Contributing guide

https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md
### Changelog

*
*
*
*
*

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rbinrais__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (rbinrais). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@rgardler @sauryadas Can you review this? Should we remove the mesos template?

**Comment by gatneil** [comment]
@rgardler @sauryadas Can you review this? Should we remove the mesos template?

**Comment by rgardler** [comment]
This pull request is against a very old version of the original template. Current version is at https://github.com/Azure/azure-quickstart-templates/tree/master/101-acs-mesos

If you view the current version you will see that the depr3ecation notice is  already there.

I'm unsure how long deprecated templates are supposed to stay in the repo, but from my perspective you are free to remove it.

**Comment by gatneil** [comment]
Removed; Closing

**Pull request closed without merging**
