### PR TITLE
Updates ARM template files - NSG flow logs

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template used in ARM template [quickstart](https://docs.microsoft.com/azure/network-watcher/quickstart-configure-network-security-group-flow-logs-from-arm-template) article.
- Adds quickstart article's author to `docOwner` in _metadata.json_.
- Updates _README.md_ with link to the quickstart article, adds **Deploy to Azure Gov** button, copyedits.
- Updates resource `type` to the latest `apiVersion`.
- Fixes order of template's `resources` properties based on best practices guidance.
- To resolve a best practices warning, updates _prereq/azuredeploy.json_ Line 63 and replaces `concat` with `resourceId`.
- Fixes indentation.

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@damendo - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@damendo - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
The build step **What-If (prereqs)** ran for over an hour with no output or errors. The build halted at that step. Close and reopen to reinitialize the build.

**Comment by bmoore-msft** [comment]
@damendo - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
Successful build.

**Pull request merged**
