### PR TITLE
[ADF] Added "\r" to lines 16, 36, and 84 to start a new multi line string.

### PR DESCRIPTION
**Pull request by markingmyname**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@daperlov - check this PR for updates that may be needed to documentation that references this sample.

**Comment by markingmyname** [comment]
#sign-off

**Comment by markingmyname** [comment]
Thanks, Brian.

However, I am trying to make the template fit on the page for this article - https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-resource-manager-template.

As you can see it comes off the page.

I was trying to make the longer expression lines escape to the next line so a user does not have to scroll.

Is there a way you suggest I can make that happen?

Thank you.

-Mark Ghanayem

**Comment by markingmyname** [comment]
i mistook the formatting of the JSON script to represent the visual effects display in the article.

Apologizes.

closing PR.

thank you for reviewing this.

**Pull request closed without merging**
