### PR TITLE
Removed MAA and ASC Endpoint for Linux TLVM

### PR DESCRIPTION
**Pull request by AjKundnani**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Changed default value for MAA & ASC Endpoint to empty string as it is managed by backend service.
* Updated UI Definition to be in sync with TLVM Windows.
* Updated metadata.json

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@cynthn - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@cynthn - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@cynthn - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by AjKundnani** [comment]
@bmoore-msft - The template is aligned to `vm-simple-linux` but still getting flagged for BPA (Password used instead of SSH Public key). Kindly review and modify if needed.

**Pull request merged**
