### PR TITLE
Azure RM template for creating an Azure DevTest Lab with policies.

### PR DESCRIPTION
**Pull request by mithunshanbhag**
Change Description: 

1: This Azure RM template allows the user to create an Azure DevTest Lab with the following policies set on it: 
  - VM sizes allowed in the Lab.
  - Total number of VMs allowed in the Lab.
  - Maximum number of VMs allowed for each user.

2: Updating an existing Azure RM template per changes in DevTest Lab RP. 

3: Minor bug-fixes & updates to the DTL PS cmdlets (wrapper around the DTL quickstart templates).

### CODE REVIEW

**Comment by singhkay** [comment]
@template-deploy-bot test this please

**Comment by mithunshanbhag** [comment]
@singhkay PR is now ready to be merged into master. Please let me know if any additional details/fixes are needed from my end.

**Comment by singhkay** [comment]
@template-deploy-bot test this please

**Comment by mithunshanbhag** [comment]
@singhkay: Just submitted a fix for the recent issue caught by @template-deploy-bot. Can you please take a look? 

Also quick question: Is it possible for PR submitters to request validation by @template-deploy-bot? I noticed that it is not automatically triggered (unlike @acomghbot).

**Comment by singhkay** [comment]
@mithunshanbhag The bot is currently set to only deploy when an admin posts :) Is committer kick off a required scenario for you?

@template-deploy-bot test this please

**Comment by mithunshanbhag** [comment]
@singhkay I see. Not a required thing, but a nice to have :-)

Another question related to the recent failure above.... I generally supply bogus/fake values in the azuredeploy.parameters.json. 

Most of our templates work well with this (e.g. The RM template to create a lab can accept any supplied string as the 'newLabName' parameter).

However some of our templates need name (or IDs) of existing Azure resources (e.g. The RM template to create a lab VM can only accept actual/existing lab names/Ids as input). 

What is the recommendation to work around this issue?

**Comment by singhkay** [comment]
@mithunshanbhag Ya existing is a bit of a pain and not easy to do. Are there any existing values for resources that can work across subscriptions?

**Comment by mithunshanbhag** [comment]
@singhkay Unfortunately no. The resources exposed by our RP (labs, VMs, VM templates etc) are unique to (and tied to) a subscription.

**Comment by singhkay** [comment]
@mithunshanbhag Ah ok, we'll have to figure out that part. I'll merge this assuming you've deployed it to be working.

**Pull request merged**
