### PR TITLE
[resource graph] - add the bicep file

### PR DESCRIPTION
**Pull request by mumian**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@DCtheGeek - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by DCtheGeek** [comment]
@timwarner-msft Can you update these and take ownership?  Thanks!

**Comment by timwarner-msft** [comment]
#reassign:@timwarner-msft

**Review by timwarner-msft — COMMENTED** [review]
@mumian Would you please add my alias (GitHub: timwarner-msft; MS: timwarner) to the *metadata.json* file?

**Comment by azure-quickstarts** [comment]
@timwarner-msft - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by mumian** [comment]
@timwarner-msft - Done.

**Comment by azure-quickstarts** [comment]
@timwarner-msft - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Pull request merged**
