### PR TITLE
Added ssh public key params

### PR DESCRIPTION
**Pull request by dwaiba**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
* Added ssh public key params

### Description of the change
Added ssh public key params

### CODE REVIEW

**Comment by dwaiba** [comment]
@singhkay created pull #1942 for Disk striping template for centos 7.2. This is for using the ssh public key

**Comment by dwaiba** [comment]
@singhkay created pull #1942 for Disk striping template for centos 7.2. This is for using the ssh public key .. Requesting Merge... Passed tests

**Comment by dwaiba** [comment]
@singhkay Requesting merge... All tests pass ... #1942 for commit [a36378f](https://github.com/Azure/azure-quickstart-templates/pull/1942/commits/a36378ff96961431def6ad6355ce57d077f4362e)

**Comment by dwaiba** [comment]
@singhkay @kmouss  Requesting merge... All tests pass ... #1942  for commit [8cf3798](https://github.com/Azure/azure-quickstart-templates/pull/1942/commits/8cf37987383a896a8f176c62b68c9d6075e48c36)

**Comment by dwaiba** [comment]
@singhkay @kmouss Requesting merge... All tests pass ... #1942

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
