### PR TITLE
Event Grid Updated APIs and metadata

### PR DESCRIPTION
**Pull request by JFolberth**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Updated Event Grid APIs
* Updated dateUpdated in metadata

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@JFolberth can you check the deployment failure?

**Comment by JFolberth** [comment]
Not sure how to update this for best practice.  Error is related to the URL not existing.  The URL was the original provided by the author.  Here's the description provided for the parameter:
                "description": "The webhook URL to send the subscription events to. This URL must be valid and must be prepared to accept the Event Grid webhook URL challenge request."

**Comment by bmoore-msft** [comment]
Yeah - I see the pattern in another PR, reached out to @johndowns to see if he can help.

**Comment by bmoore-msft** [comment]
Closing abandoned request

**Pull request closed without merging**
