### PR TITLE
Fix issue #6897

### PR DESCRIPTION
**Pull request by MCKLMT**
Fix issue #6897
- Fix URLs in README.md

### CODE REVIEW

**Comment by MCKLMT** [comment]
@bmoore-msft The deployment fails on US Gov. Can you have a look?

**Comment by MCKLMT** [comment]
@bmoore-msft Can you explain what's your change?

**Comment by bmoore-msft** [comment]
The container in the prereq template wasn't creating the fileshare in USGov - not sure why since it didn't fail and worked in Public...  So I changed the prereq template to use the deploymentScript resource instead of a container, which seems to work as expected.  Also, using ACI for the prereq leaves the resource intact, so the deploymentScript resource is a more appropriate solution.

**Comment by bmoore-msft** [comment]
ok, looks like deployment is working everywhere... @MCKLMT any concerns merging this?

The BP failure is coming from the fact that the apiVersion is not rolled into USGov yet (even though it's 4 months old).

**Comment by MCKLMT** [comment]
OK to be merged.

**Pull request merged**
