### PR TITLE
update pxc install for xtrabackup

### PR DESCRIPTION
**Pull request by liupeirong**

### CODE REVIEW

**Comment by liupeirong** [comment]
I successfully deployed this template with the same parameters that Travis used.  Let me know why Travis still fails.

**Comment by singhkay** [comment]
@liupeirong When I deployed I got the below error. 

```
New-AzureRmResourceGroupDeployment : 2:52:55 PM - Resource Microsoft.Compute/virtualMachines/extensions 'a-pxc/pxc-ext' failed with message 'The resource 
operation completed with terminal provisioning state 'Failed'.'
At C:\RunParam.ps1:6 char:1
+ New-AzureRmResourceGroupDeployment -Name test12 -ResourceGroupName $r ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand
 
New-AzureRmResourceGroupDeployment : 2:52:55 PM - VM has reported a failure when processing extension 'pxc-ext'. Error message: "Script returned an error.
---stdout---
age percona-release.x86_64 0:0.0-1 will be installed
--> Finished Dependency Resolution
Dependencies Resolved
================================================================================
 Package            Arch      Version    Repository                        Size
================================================================================
Installing:
 percona-release    x86_64    0.0-1      /percona-release-0.0-1.x86_64    3.6 k
Transaction Summary
================================================================================
Install       1 Package(s)
Total size: 3.6 k
Installed size: 3.6 k
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : percona-release-0.0-1.x86_64                                 1/1 
  Verifying  : percona-release-0.0-1.x86_64                                 1/1 
Installed:
  percona-release.x86_64 0:0.0-1                                                
Complete!
Preparing...                ##################################################
socat                       ##################################################
Loaded plugins: security
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package Percona-XtraDB-Cluster-56.x86_64 1:5.6.28-25.14.1.el6 will be installed
--> Processing Dependency: Percona-XtraDB-Cluster-server-56 for package: 1:Percona-XtraDB-Cluster-56-5.6.28-25.14.1.el6.x86_64
--> Processing Dependency: Percona-XtraDB-Cluster-galera-3 for package: 1:Percona-XtraDB-Cluster-56-5.6.28-25.14.1.el6.x86_64
--> Processing Dependency: Percona-XtraDB-Cluster-client-56 for package: 1:Percona-XtraDB-Cluster-56-5.6.28-25.14.1.el6.x86_64
--> Running transaction check
---> Package Percona-XtraDB-Cluster-client-56.x86_64 1:5.6.28-25.14.1.el6 will be installed
---> Package Percona-XtraDB-Cluster-galera-3.x86_64 0:3.14-1.rhel6 will be installed
---> Package Percona-XtraDB-Cluster-server-56.x86_64 1:5.6.28-25.14.1.el6 will be installed
--> Processing Dependency: percona-xtrabackup >= 2.2.5 for package: 1:Percona-XtraDB-Cluster-server-56-5.6.28-25.14.1.el6.x86_64
--> Processing Dependency: Percona-XtraDB-Cluster-shared-56 for package: 1:Percona-XtraDB-Cluster-server-56-5.6.28-25.14.1.el6.x86_64
--> Processing Dependency: perl-DBD-MySQL for package: 1:Percona-XtraDB-Cluster-server-56-5.6.28-25.14.1.el6.x86_64
--> Running transaction check
---> Package Percona-XtraDB-Cluster-shared-56.x86_64 1:5.6.28-25.14.1.el6 will be installed
---> Package percona-xtrabackup.x86_64 0:2.3.3-1.el6 will be installed
--> Processing Dependency: libev.so.4()(64bit) for package: percona-xtrabackup-2.3.3-1.el6.x86_64
---> Package perl-DBD-MySQL.x86_64 0:4.013-3.el6 will be installed
--> Finished Dependency Resolution
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Loaded plugins: security
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package xinetd.x86_64 2:2.3.14-39.el6_4 will be installed
--> Finished Dependency Resolution
Dependencies Resolved
================================================================================
 Package         Arch            Version                    Repository     Size
================================================================================
Installing:
 xinetd          x86_64          2:2.3.14-39.el6_4          base          121 k
Transaction Summary
================================================================================
Install       1 Package(s)
Total download size: 121 k
Installed size: 259 k
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : 2:xinetd-2.3.14-39.el6_4.x86_64                              1/1 
  Verifying  : 2:xinetd-2.3.14-39.el6_4.x86_64                              1/1 
Installed:
  xinetd.x86_64 2:2.3.14-39.el6_4                                               
Complete!
Stopping xinetd: [FAILED]
Starting xinetd: [  OK  ]
---errout---
ls: cannot access /datadrive: No such file or directory
mdadm: Defaulting to version 1.2 metadata
mdadm: array /dev/md127 started.
yes: standard output: Broken pipe
yes: write error
Device contains neither a valid DOS partition table, nor Sun, SGI or OSF disklabel
Building a new DOS disklabel with disk identifier 0x1b567793.
Changes will remain in memory only, until you decide to write them.
After that, of course, the previous content won't be recoverable.
Warning: invalid flag 0x0000 of partition table 4 will be corrected by w(rite)
WARNING: DOS-compatible mode is deprecated. It's strongly recommended to
         switch off the mode (command 'c') and change display units to
         sectors (command 'u').
mke2fs 1.41.12 (17-May-2010)
mkfs.ext4: invalid blocks count - /dev/md127p1
mount: can't find /datadrive in /etc/fstab or /etc/mtab
azurepxc.sh: line 242: /etc/init.d/mysql: No such file or directory
--2016-01-31 22:51:19--  https://raw.githubusercontent.com/azure/azure-quickstart-templates/master/mysql-ha-pxc/my.cnf.template
Resolving raw.githubusercontent.com... 23.235.39.133
Connecting to raw.githubusercontent.com|23.235.39.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1478 (1.4K) [text/plain]
Saving to: /etc/my.cnf
     0K .                                                     100%  243M=0s
2016-01-31 22:51:20 (243 MB/s) - /etc/my.cnf saved [1478/1478]
Error: No matching Packages to list
--2016-01-31 22:51:55--  http://apt.sw.be/redhat/el6/en/x86_64/rpmforge/RPMS/socat-1.7.2.4-1.el6.rf.x86_64.rpm
Resolving apt.sw.be... 193.1.193.67
Connecting to apt.sw.be|193.1.193.67|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 348020 (340K) [application/x-redhat-package-manager]
Saving to: socat-1.7.2.4-1.el6.rf.x86_64.rpm
     0K .......... .......... .......... .......... .......... 14%  279K 1s
    50K .......... .......... .......... .......... .......... 29%  554K 1s
   100K .......... .......... .......... .......... .......... 44%  555K 0s
   150K .......... .......... .......... .......... .......... 58%  556K 0s
   200K .......... .......... .......... .......... .......... 73%  558K 0s
   250K .......... .......... .......... .......... .......... 88% 54.7M 0s
   300K .......... .......... .......... .........            100%  442K=0.6s
2016-01-31 22:51:56 (539 KB/s) - socat-1.7.2.4-1.el6.rf.x86_64.rpm saved [348020/348020]
warning: socat-1.7.2.4-1.el6.rf.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID 6b8d79e6: NOKEY
Error: Package: percona-xtrabackup-2.3.3-1.el6.x86_64 (percona)
           Requires: libev.so.4()(64bit)
Warning: RPMDB altered outside of yum.
azurepxc.sh: line 259: /etc/init.d/mysql: No such file or directory
azurepxc.sh: line 283: /etc/init.d/mysql: No such file or directory
azurepxc.sh: line 296: mysql: command not found
".
```

**Comment by liupeirong** [comment]
Kay, did you point the script to my repo when you deploy manually?

**Comment by singhkay** [comment]
@liupeirong The CI should have automatically replaced the links to your fork but in this case it looks like since the Github URLs are case sensitive and the default value of the scripts is `azure` instead of `Azure` the replacement didn't happen at 
https://travis-ci.org/Azure/azure-quickstart-templates/builds/105960086#L513 

This (https://github.com/liupeirong/azure-quickstart-templates/blob/master/mysql-ha-pxc/azuredeploy.json#L211) should become 
`https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/mysql-ha-pxc/my.cnf.template`

**Comment by liupeirong** [comment]
changed from "azure" to "Azure" in the URL.  Looks like the replacement happened, but deployment still fails.  I can deploy it successfully manually.  The "stopping xinet [FAILED]" is not a problem, if the service is not running, it will move on to start it.  Anything else I can check why Travis still fails?

**Comment by singhkay** [comment]
@liupeirong Looks like that was a weird custom script failure. I reran the CI and it passed. The newer version of Azure CLI can't come soon enough :smile: merging

**Pull request merged**
