### PR TITLE
Changing Map Create template for price changes

### PR DESCRIPTION
**Pull request by anastasia-ms**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Updated JSON to reflect new pricing tiers
* Removed "preview" tag

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@philmea - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by philmea** [comment]
approved

**Comment by azure-quickstarts** [comment]
@philmea - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by azure-quickstarts** [comment]
@philmea - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by azure-quickstarts** [comment]
@philmea - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by anastasia-ms** [comment]
#sign-off

**Pull request merged**
