### PR TITLE
Updating policy to seclude emails and having IsSendToAdmins disabled

### PR DESCRIPTION
**Pull request by beng930**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@beng930 - why are we removing the feature instead of making it optional?

**Comment by beng930** [comment]
> @beng930 - why are we removing the feature instead of making it optional?

Hi Brian,
We're migrating our alert email service to ASC, hence we're removing these fields from our policy

**Comment by beng930** [comment]
@bmoore-msft - hey, any ideas why after verification the pipeline for USGov gives an error  'The client does not have authorization to perform action'?

**Comment by bmoore-msft** [comment]
my guess a timing issue with the roleAssignment for CI - I ran another pass and it seems fine now...

**Comment by beng930** [comment]
Awesome! Thank you for your help Brian.

**Pull request merged**
