### PR TITLE
Remove dependency of Resource Group location.

### PR DESCRIPTION
**Pull request by rjfmachado**
Key Vault and parent resource group can have different locations.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rjfmachado__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@rjfmachado__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by singhkay** [comment]
@seanbamsft Can you review this change?

**Comment by singhkay** [comment]
@rjfmachado Thanks for the update! Can you add the description metadata for the location parameter?

**Comment by singhkay** [comment]
looks good, merging

**Pull request merged**
