### PR TITLE
enable standalone marvel cluster

### PR DESCRIPTION
**Pull request by hglkrijger**
- add marvel options for cluster and vm size
- add marvel availability dataset, with dependency
- use marvel node endpoints and cluster name when cluster selected
- add marvel ip prefix to empty resources to ensure consistency
- fix marvel install bug, so marvel is not installed unless selected

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@hglkrijger__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (hkrijger). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@hglkrijger Can you amend the template readme and description will all these new capabilities you are adding as well?

**Comment by hglkrijger** [comment]
@singhkay updated the PR with readme/metadata changes

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
