### PR TITLE
Dynamically determine certificate end date for Windows VM with WinRM demo

### PR DESCRIPTION
**Pull request by xandersherry**
Updated the Create-Certification function to dynamically determine and set the certificate validity end date rather than using a static date string which is currently in the past, so new certificates are already expired.

This PR resolves Issue #12100 

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by xandersherry** [comment]
I'm not sure what I need to do to fix the best practices violation issue.  Any guidance is welcome.

**Comment by tfenster** [comment]
@xandersherry you can find the details here https://dev.azure.com/azurequickstarts/azure-quickstart-templates/_build/results?buildId=91026&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=14b22f05-782e-55fa-3e59-b66c82f514a9&l=125. Basically, the API versions used in azuredeploy.json are too old

**Comment by xandersherry** [comment]
@tfenster Apologies, I should have been more clear.  Specifically, do those updates need to be made as a part of this PR in order for it to be accepted?  

They're unrelated to this very small and highly targeted critical bug fix, and given that they're hygiene issues rather than functional issues, and cleaning them up could actually cause new issues, it seems to me that a separate PR would be more appropriate for them.

**Comment by tfenster** [comment]
@xandersherry I am not directly involved here, just stumbled across your question as I looked at my own PR, but from reading the guidelines, I think fixing the best practice warnings is indeed a requirement

**Comment by xandersherry** [comment]
@tfenster Fair enough, thanks for the thoughts!

**Comment by xandersherry** [comment]
Ok, this PR should be good to go now.

**Comment by xandersherry** [comment]
Hi @AmrutaKawade, I do see the change reflected in the file you've linked.   
image

Perhaps you are (or were) seeing a caching issue, either with GitHub or in ADO?

**Pull request merged**
