### PR TITLE
Add SSH rsa public key parameter for all linux vms, and docker to linux jumpbox

### PR DESCRIPTION
**Pull request by anhowe**
- enable the user to specify an ssh public key through the parameter.  The reason this is done through the script is to provide the user the option, and the normal method highlighted in https://github.com/anhowe/scratch/tree/master/linuxvm does not provide this option.
- add docker to linux jumpbox

@ahmetalpbalkan, @rgardler

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@anhowe__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by ahmetalpbalkan** [comment]
@anhowe I think the way you add the SSH public key to the VM is inconvenient. It will work but it is vague and you have a lot of code around it just to handle/parse/place it. Please check the swarm template about how it is done. Our infrastructure already makes this easy to specify keys in the provisioning configuration.

**Comment by anhowe** [comment]
The swarm template doesn't solve the problem I highlighted in the description to this pull.  How do you solve that problem?

**Comment by ahmetalpbalkan** [comment]
@anhowe I am not sure I understand the problem. Is it because you want to give user an option to choose password or public key?

**Comment by anhowe** [comment]
yes, to provide the user an option to enable ssh access

**Comment by anhowe** [comment]
let's take this discussion offline

**Comment by rgardler** [comment]
Please post a summary of that discussion here. That way this issue becomes a useful piece of documentation for those facing the same issue.

**Comment by ahmetalpbalkan** [comment]
It's not trivial to easily make templates use password for Virtual Machines and at the same time "give an option" to use SSH public keys. Therefore the scripts are there to write the public key contents to `>> $HOME/.ssh/authorized_keys`. The script is trivial, as I also said will probably just work fine. The point I didn't see here initially was not many people just trying to kick the tires will have SSH key pairs, so we still need to have a password option as well.

**Comment by rgardler** [comment]
Yeah, that makes sense. Thanks for following up here.

**Pull request merged**
