### PR TITLE
FIX-BESTPRACTICES: logic-app-create

### PR DESCRIPTION
**Pull request by sameera-spektra**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@ecfan - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by ecfan** [comment]
Hi @sameera-spektra,

Thanks for your suggestion! Can you please provide a comment or reason for your suggested update? Looks like you want to change the following line from:

`"uri": "@parameters('testUri')"`

to:

`"uri": "[parameters('testUri')]"`

@Azure/azure-logicapps-team, can you please check the customer's proposed change to this Logic Apps quickstart template? Their suggestion would change the functionality for the code in question.

**Comment by joechung-msft** [comment]
> @Azure/azure-logicapps-team, can you please check the customer's proposed change to this Logic Apps quickstart template? Their suggestion would change the functionality for the code in question.

The change looks correct. The parameter being referenced is a deployment template parameter, not a Logic Apps parameter.

**Comment by ecfan** [comment]
@joechung-msft: Thanks for confirming! 
@sameera-spektra: Please continue with the process to submit your contribution (change from **Draft** to **Ready for review**), and then I think the team can sign off?

**Comment by sameera-spektra** [comment]
> 
> 
> Hi @sameera-spektra,
> 
> Thanks for your suggestion! Can you please provide a comment or reason for your suggested update? Looks like you want to change the following line from:
> 
> `"uri": "@parameters('testUri')"`
> 
> to:
> 
> `"uri": "[parameters('testUri')]"`
> 
> @Azure/azure-logicapps-team, can you please check the customer's proposed change to this Logic Apps quickstart template? Their suggestion would change the functionality for the code in question.

@ecfan Using @parameters('testUri') violates the best practice checks. We were trying to fix it. I'll mark the PR as ready for review anyways.

**Comment by ecfan** [comment]
@sameera-spektra, thank you for clarifying, I was just curious to better understand. 👍 
#sign-off

**Comment by ecfan** [comment]
@sameera-spektra: Oh, at the top of your PR, please add an entry to the Changelog, and put an `X` in the box next to `Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.`

**Pull request merged**
