### PR TITLE
spelling mistake

### PR DESCRIPTION
**Pull request by cassiopaia**
###  Changelog
- Spelling mistake correction

### Description of the change
[-] BitShare
[+] BitShares

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@cassiopaia__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@ryanRfox Since you're the template author, OK with the merge?

**Comment by ryanRfox** [comment]
Yes, all seems to be proper on the merge. Thanks

On Mar 10, 2016, at 3:45 PM, Kay Singh <notifications@github.com<mailto:notifications@github.com>> wrote:


@ryanRfox<https://github.com/ryanRfox> Since you're the template author, OK with the merge?

-

**Comment by singhkay** [comment]
merged

**Pull request merged**
