### PR TITLE
Remove broken sample

### PR DESCRIPTION
**Pull request by bmoore-msft**
## Changelog

* removing broken sample
*
*

### CODE REVIEW

**Comment by gruve-p** [comment]
Why was this removed @bmoore-msft  ?

**Comment by bmoore-msft** [comment]
We could not get a successful deployment for the sample.

**Comment by gruve-p** [comment]
But groestlcoin was working successfull  van that one be reverted?

**Comment by bmoore-msft** [comment]
If you want submit a PR with a working variation of that (or just that variation) I'm happy to add it back...  We just don't have the bandwidth/expertise to debug all the community workloads.

**Pull request merged**
