### PR TITLE
Fully documenting how to specify ISE connector/connectors when deploying the template

### LINKED ISSUE #6376: Can/How do you deploy multiple connectors to ISE?
[Provision an Integration Service Environment with a VNET, subnets, and managed connectors](https://github.com/Azure/azure-quickstart-templates/tree/master/201-integration-service-environment)

### Issue Details
It's not clear from the readme or the template comments how to deploy multiple connectors to the ISE; do you comma-separate? semicolon separate? Is it not possible? Should provide guidance here.

Additionally if it's not possible, it should be :)

### PR DESCRIPTION
**Pull request by brandonh-msft**
Fixes #6376

### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

* Updated README with example ISE connector parameter values
* Adding example values to template parameter description

### CODE REVIEW

**Comment by nzthiago** [comment]
Hmm, strange that the PR is now failing on the managed APIs, where it didn't in my PR. Maybe something changed with ISE since then?

{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "IntegrationServiceEnvironmentManagedApiProvisioningFailed",
        "message": "The provisioning of managed api 'servicebus' in integration service environment '/subscriptions/0cec7090-2e08-4498-9337-eb96ade50821/resourceGroups/azdo-ea1155c4-956a-4979-8dbc-2a4beaa19b63/providers/Microsoft.Logic/integrationServiceEnvironments/cid537525c45d349aa' failed with error: '{\"message\":\"CreateFailed\",\"code\":\"Failed\"}'."
      }
    ]
  }
}'
7:11:35 PM - The provisioning of managed api 'servicebus' in integration service environment '/subscriptions/0cec7090-2e08-4498-9337-eb96ade50821/resourceGroups/azdo-ea1155c4-956a-4979-8dbc-2a4beaa19b63/providers/Microsoft.Logic/integrationServiceEnvironments/cid537525c45d349aa' failed with error: '{"message":"CreateFailed","code":"Failed"}'.
7:12:42 PM - Resource Microsoft.Logic/integrationServiceEnvironments/ManagedApis 'cid537525c45d349aa/azureblob' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "IntegrationServiceEnvironmentManagedApiProvisioningFailed",
        "message": "The provisioning of managed api 'azureblob' in integration service environment '/subscriptions/0cec7090-2e08-4498-9337-eb96ade50821/resourceGroups/azdo-ea1155c4-956a-4979-8dbc-2a4beaa19b63/providers/Microsoft.Logic/integrationServiceEnvironments/cid537525c45d349aa' failed with error: '{\"message\":\"CreateFailed\",\"code\":\"Failed\"}'."
D:\_work\1\test\Deploy-AzTemplate.ps1 : Deployment failed.

**Comment by brandonh-msft** [comment]
oh no we've been seeing this for the past week - please report on our email thread w/ PG if you just hit this as they told us they fixed it.

**Comment by bmoore-msft** [comment]
@brandonh-msft - can you fix the issues in metadata.json?  see CI results

**Comment by brandonh-msft** [comment]
⏲

**Comment by brandonh-msft** [comment]
@nzthiago trying to get this update in but it looks like the deployment mechanism for managed APIs has changed to require location and that's what's failing the build? Can you help out here (on my fork)? Thanks!

**Comment by nzthiago** [comment]
> @nzthiago trying to get this update in but it looks like the deployment mechanism for managed APIs has changed to require location and that's what's failing the build? Can you help out here (on my fork)? Thanks!

@brandonh-msft I *think* that under name [here](https://github.com/Azure/azure-quickstart-templates/blob/1e1ce3b4f803a281d6fa569389d2bbc57ff5656c/201-integration-service-environment/azuredeploy.json#L230) you need the following as well now (yes, properties is just empty):
``` 
"location": "[parameters('location')]",
       "properties": {
       }
```
If it doesn't you will need to double check with @rarayudu

**Comment by brandonh-msft** [comment]
perfect looks like that got us much further, but ran in to the `Internal Server Error` deployment failure. I've informed PG and will be re-submitting something to this PR to trigger another CI when they've completed their investigation.

**Comment by brandonh-msft** [comment]
@bmoore-msft same issue  as #6378 here w/ RG cleanup in the CI. Can we push this one thru? Thanks!

**Comment by brandonh-msft** [comment]
ping @bmoore-msft et al

**Comment by bmoore-msft** [comment]
@brandonh-msft - last build failed to deploy - see: https://dev.azure.com/azurequickstarts/azure-quickstart-templates/_build/results?buildId=1476

I'm running another one now...

**Comment by brandonh-msft** [comment]
@bmoore-msft what do we make of Public succeeding (just failed on RG cleanup) but Fairfax failing?

**Comment by bmoore-msft** [comment]
Is ISE supported in FF?

**Pull request merged**
