### PR TITLE
Change AKS to default create MSI cluster

### PR DESCRIPTION
**Pull request by norshtein**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Change 101-aks to create MSI cluster by default.

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@mlearned - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
Can you update the date in metadata.json as well?

**Comment by norshtein** [comment]
@bmoore-msft , thanks for reviewing! Updated the date.

**Comment by bmoore-msft** [comment]
@mlearned - check this PR for updates that may be needed to documentation that references this sample.

**Pull request merged**
