### PR TITLE
Disable private link service for NPIP CI &cluster

### PR DESCRIPTION
**Pull request by JudyHuangzhuhuang**
https://msdata.visualstudio.com/Vienna/_workitems/edit/1317117/?workitem=924469

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@Blackmist - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by bmoore-msft** [comment]
@JudyHuangzhuhuang - can you expand on the reason for the change?  I'm not able to discern how the work item and this change are related... 

Also, need to update the date in metadata.json

**Comment by JudyHuangzhuhuang** [comment]
Hi Brian,

Sure. For NoPublicIP clusters and NoPublicIP compute instance used in Private Link Workspace, privateLinkServiceNetworkPolicies needs to be disabled in order to provision them with no public IP.

So the change is to set default value of privateLinkServiceNetworkPolicies to "disabled".

Is "dateUpdated" where I need to update in metadata.json?

**Comment by Blackmist** [comment]
@jhirono for feedback. As far as I am aware, no public IP computes are private (gated) preview capabilities only at this time. So not sure we should be default enabling in a template.

**Comment by bmoore-msft** [comment]
dateUpdated is in metadata.json

**Pull request merged**
