### PR TITLE
CF enable diego by default

### PR DESCRIPTION
**Pull request by gossion**
Azure Cloud Foundry will have Diego enabled by default in its manifests.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gossion__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (guwe). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@bingosummer Can you review ?

**Comment by bingosummer** [comment]
@singhkay 
LGTM

**Comment by bingosummer** [comment]
@singhkays 
LGTM now. Please merge it if you are also OK with the PR. Thanks in advance.

**Comment by singhkays** [comment]
lgtm, merged

**Pull request merged**
