### PR TITLE
New template for Trusted Launch VMSS

### PR DESCRIPTION
**Pull request by AjKundnani**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* New template for Trusted Launch Windows VMSS
*
*

### CODE REVIEW

**Comment by AjKundnani** [comment]
@sirfamelin - Kindly review the template for Trusted Launch VMSS.

**Comment by sirfamelin** [comment]
@AjKundnani LGTM, have you tested the templates?

**Comment by AjKundnani** [comment]
> @AjKundnani LGTM, have you tested the templates?

Thanks @sirfamelin - Yes the template has been successfully validated.

image

**Comment by AjKundnani** [comment]
Bicep warning generated due to missing property. Issue https://github.com/Azure/bicep/issues/9303 raised Bicep team.

**Pull request merged**
