### PR TITLE
MOVE: 201-2-vms-internal-load-balancer to quickstarts\microsoft.compute

### PR DESCRIPTION
**Pull request by akhilthomas011**
…te\2-vms-internal-load-balancer

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@asudbring - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by azure-quickstarts** [comment]
@mumian - this appears to be a "Move" that will need a manual doc update

**Comment by azure-quickstarts** [comment]
@tfitzmac - this appears to be a "Move" that will need a manual doc update

**Comment by tfitzmac** [comment]
@asudbring @mumian - I'll fix this one.

**Comment by tfitzmac** [comment]
https://github.com/MicrosoftDocs/azure-docs-pr/pull/156624

**Comment by azure-quickstarts** [comment]
@asudbring - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by azure-quickstarts** [comment]
@mumian - this appears to be a "Move" that will need a manual doc update

**Comment by azure-quickstarts** [comment]
@tfitzmac - this appears to be a "Move" that will need a manual doc update

**Comment by asudbring** [comment]
@akhilthomas011 - Is there a process for updating the links to these templates in docs.microsoft.com?  We have quickstarts and the main Template Quickstart azure pages reference the path to these templates and they are breaking.

Thanks!

**Comment by mumian** [comment]
@asudbring - Yes.  Tom has created a PR to address these broken links - MicrosoftDocs/azure-docs-pr#156624

**Comment by tfitzmac** [comment]
@asudbring - are you seeing broken links for other templates that have already been moved? It's possible some are slipping through. We are notified of any templates that are marked with a doc owner. We also can see any warnings in the doc build for templates that have a code link. However, it's possible if you have just a link (not an external code reference) and the template is not marked with a code owner that we would not catch it in our process.

**Comment by asudbring** [comment]
@tfitzmac I was trying to merge a PR yesterday and it wouldn't let me because of the broken links.  It could have just been timing and I was trying to do something at the exact time you were.   

Thanks Tom!!!!

**Pull request merged**
