### PR TITLE
Update sample: Front Door (Standard/Premium) with Azure Storage static website

### PR DESCRIPTION
**Pull request by johndowns**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Use `loadTextContent()` to load deployment script.

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by johndowns** [comment]
@bmoore-msft I'm not sure why the Bicep file is transpiling with a different hash and with the `\r\n` line breaks in the PR validation. I'm using Bicep v0.4.451.19169 and I've tried on both macOS and Windows. Any ideas?

**Comment by azure-quickstarts** [comment]
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by StephenWeatherford** [comment]
@johndowns What's the OS of the machine you're running bicep build on?

**Comment by johndowns** [comment]
@StephenWeatherford I've used two machines and have the same output on both:
- Windows 10 (21H1)
- macOS Big Sur (11.4)

**Comment by StephenWeatherford** [comment]
It's probably caused by git encoding with LR or CRLF based on the machine OS.  Can you try adding a .gitattributes file in your scripts folder to force a consistent linefeed?  Here's an example: https://github.com/Azure/bicep/blob/a9c666441c6093d02d709ce75a290be187b182a9/.gitattributes

**Comment by azure-quickstarts** [comment]
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by johndowns** [comment]
@StephenWeatherford Looks like that worked. Do you think we'll need to do this in every similar folder, or would it be better to do this at the root of the repo?

**Comment by StephenWeatherford** [comment]
We can't know for sure what files should be treated this way and what shouldn't, so it's best to keep it under individual samples.

**Pull request merged**
