### PR TITLE
Add template for Power BI Embedded

### PR DESCRIPTION
**Pull request by mgblythe**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by mgblythe** [comment]
@bmoore-msft - can take a look at this b/c Power BI Embedded requires an existing AAD account for the admin parameter and it's failing when I try to pass my account as a test. What's the right approach for this? Thanks!

**Comment by bmoore-msft** [comment]
No idea... it doesn't seem to want a service principal, I tried using my tenant admin account and it fails with either.  I can't find any documentation on it aside from this: https://docs.microsoft.com/en-us/rest/api/power-bi-embedded/capacities/create#dedicatedcapacityadministrators which isn't at all helpful.

So I think we need to understand what the resource is really after...

Also, is your readme description accurate? ie. a portal dashboard?

**Comment by mgblythe** [comment]
Thanks @bmoore-msft - good catch on the copy-paste error from my Azure portal template :-).

Here's some more info from docs: "Power BI capacity administrators can view the capacity in the Power BI admin portal and give assignment permissions to other users. By default, the capacity administrator is your account. The capacity administrator must be within your Power BI tenant." 

If I deploy the template through the portal UI, it defaults to my account and it works, but I can also change it to someone else at microsoft.com, and it still works. I'll reach out to the PBI team and see if they have any ideas, but does it make sense to you that it would work in the portal UI but not in the test harness?

**Comment by bmoore-msft** [comment]
@KesemSharabi - check this PR for updates that may be needed to documentation that references this sample.

**Comment by mgblythe** [comment]
@bmoore-msft - I discussed with the PBI Embedded PM, and we believe the issue is that Power BI is not already provisioned for the onmicrosoft tenant you're using to deploy the quickstarts. Can you sign up for a free Power BI license on your tenant then that should allow AD to do what it needs to do. Let me know if you need more details, thanks!

**Comment by bmoore-msft** [comment]
@mgblythe - Can we add instructions for that to the README?  That way customers that run into the same problem will have a solution handy...

**Comment by mgblythe** [comment]
@bmoore-msft - yes I'll do that. Let me know when you've added it on your side and we can see if we get a successful run, thanks!

**Comment by bmoore-msft** [comment]
@KesemSharabi - check this PR for updates that may be needed to documentation that references this sample.

**Comment by mgblythe** [comment]
@bmoore-msft - can you sign up for Power BI so we can see if that solves this issue?

**Comment by bmoore-msft** [comment]
The template fails to deploy - did we update the readme w/ instructions for a successful deployment?  (I'm not seeing anything)

**Comment by mgblythe** [comment]
@bmoore-msft - I'm waiting on a successful deployment then I'll know what to say :-). To clarify - you now have a PBI license for your tenant but the deployment still fails?

**Comment by bmoore-msft** [comment]
How do I check if I have a PBI license? I don't remember if you gave me instructions offline or I was waiting for the README updates so I can test to see if someone other than the product team can deploy the sample ;)

**Comment by mgblythe** [comment]
@bmoore-msft:

1. Go to https://powerbi.microsoft.com/en-us/get-started/ and select **Try free**. 
2. Enter with bmoore@azurequickstarts.onmicrosoft.com. 

The licensing flow will either tell you that you already have a license or it will walk you through the sign up process.

**Comment by bmoore-msft** [comment]
I'm able to login to the PBI home page with bmoore@azurequickstarts.onmicrosoft.com - so I think we're good there...

**Comment by bmoore-msft** [comment]
@KesemSharabi - check this PR for updates that may be needed to documentation that references this sample.

**Comment by KesemSharabi** [comment]
Hi @bmoore-msft and @mgblythe,

As per my understanding from the [guidance article](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-resource-manager-quickstart?branch=master#second-h2-review-the-template), I need to reference to the ARM template located in https://github.com/Azure/azure-quickstart-templates...

When will this template be available from there?

Thanks,

Kesem

**Comment by bmoore-msft** [comment]
@KesemSharabi - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@KesemSharabi - check this PR for updates that may be needed to documentation that references this sample.

**Comment by mgblythe** [comment]
@bmoore-msft - I added steps to the readme, and it looks like you have the public cloud version working 👍.

**Comment by bmoore-msft** [comment]
@KesemSharabi - check this PR for updates that may be needed to documentation that references this sample.

**Comment by KesemSharabi** [comment]
Hi @bmoore-msft,

When will this template be live? I need to reference to it from my article.

@mgblythe - I noticed that in azuredeploy.parameters.json and azuredeploy.parameters.us.json, the capacity name is 'mblythetestcapacity' - is this something you might want to change?

**Comment by mgblythe** [comment]
Thanks @KesemSharabi - I'll update the name. @bmoore-msft - does your Fairfax user have a Power BI license?

**Comment by mgblythe** [comment]
@bmoore-msft - any update on this? The doc article is ready and waiting on this to be merged. Thanks!

**Comment by mgblythe** [comment]
@tfitzmac - I'm OOF until 7/28, looping you in to see if we can get this one finished. CC: @KesemSharabi

**Comment by bmoore-msft** [comment]
@KesemSharabi - check this PR for updates that may be needed to documentation that references this sample.

**Comment by KesemSharabi** [comment]
Hi @bmoore-msft,

I'm ok with merging this branch. After it's merged I'll reference the files from the doc I'm writing.

Thanks,

Kesem

**Comment by tfitzmac** [comment]
@KesemSharabi - I see an error about the server name "testcapacity". Does the name need to be unique? If so, you'll need to replace testcapacity in your parameter file with GEN-UNIQUE

**Comment by KesemSharabi** [comment]
Hi @bmoore-msft and @tfitzmac,

No idea if this needs to be unique. Can we try tp replace it with something else (testcapacity2) and see if it works?

Thanks,

Kesem

**Comment by bmoore-msft** [comment]
@KesemSharabi - check this PR for updates that may be needed to documentation that references this sample.

**Comment by KesemSharabi** [comment]
Hi @bmoore-msft, looks good to me, please go ahead a publish.

**Comment by bmoore-msft** [comment]
@KesemSharabi - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@KesemSharabi - check this PR for updates that may be needed to documentation that references this sample.

**Comment by mgblythe** [comment]
@bmoore-msft - this should be ready to go now.

**Pull request merged**
