### PR TITLE
Add quickstart: cosmosdb-sql-minimal

### PR DESCRIPTION
**Pull request by seesharprun**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* New quickstart: minimal Cosmos DB SQL API (far less parameters than the fully flesh out templates)

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@seesharprun - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by seesharprun** [comment]
@bmoore-msft I'm both the author of the quickstart and the docs owner. I'm comfortable marking this PR as ready for your review. Thanks!

**Comment by azure-quickstarts** [comment]
@seesharprun - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@seesharprun - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Pull request merged**
