### PR TITLE
Function app with deployment slot

### PR DESCRIPTION
**Pull request by patelchandni**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ YES ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

ARM template and bicep for creating Function App with a Deployment Slot

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@ggailey777 - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@ggailey777 - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by ggailey777** [comment]
@patelchandni from [the README](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md#bicep-support):

> 2. The azuredeploy.json must not be included in the PR as it will be built automatically when the sample is merged.

Seems like the solution there is to remove the azuredeploy.json file and it gets generated automagically from the bicep.

**Comment by azure-quickstarts** [comment]
@ggailey777 - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by patelchandni** [comment]
@ggailey777 I've removed azuredeploy.json so this PR is ready to merge. Thank you.

**Pull request merged**
