### PR TITLE
Issueavailabilityset

### PR DESCRIPTION
**Pull request by honcao**
Put Sql cluster Vms and SQL witness Vm into the same availability set.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@honcao__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@template-deploy-bot test this please

**Comment by singhkay** [comment]
@honcao It looks the deployment failed with the bot. Since we're still testing out the bot, can you check if this deploys successfully on your end?

**Comment by honcao** [comment]
Hi Kay

I had successful deployment.

https://ms.portal.azure.com/#asset/HubsExtension/ResourceGroups/subscriptions/05bae940-af0c-4739-9c08-09bd3a818e36/resourcegroups/11sqlrgz

Thanks
Hongbin

**Comment by singhkay** [comment]
@honcao got it, merging

**Pull request merged**
