### PR TITLE
This template creates a Key Vault along with Secrets

### PR DESCRIPTION
**Pull request by rahulpnath**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
* This template creates a Key Vault along with Secrets

### Description of the change
The template supports a dynamic list of Secrets and Access Policies (to control the AD objects that have access to the Key Vault).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rahulpnath__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@rahulpnath Let's call this 101-key-vault-secret-create

**Comment by rahulpnath** [comment]
@singhkay Done. Renamed

**Comment by singhkay** [comment]
lgtm, merged

**Comment by rahulpnath** [comment]
@singhkay Seeing that all of the key vault templates are not showing up on the template site. Anything that you know of? https://azure.microsoft.com/en-us/documentation/templates/201-key-vault-secret-create/

**Pull request merged**
