### PR TITLE
Dynamic (DYN) integration to uber "blockchain" template

### PR DESCRIPTION
**Pull request by Duality-CDOO**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### CODE REVIEW

**Comment by Duality-CDOO** [comment]
Not sure why this PR is failing tests. I am sure it has nothing to do with the code additions I have made.

**Comment by LordDarkHelmet** [comment]
Looks like the API versions are out of date. For example you are using a 2015 version of Microsoft.Storage/storageAccounts. You should upgrade to the latest version 2019-06-01

**Comment by Duality-CDOO** [comment]
> Looks like the API versions are out of date. For example you are using a 2015 version of Microsoft.Storage/storageAccounts. You should upgrade to the latest version 2019-06-01

That code isn't even in the repo that I have edited.

**Comment by Duality-CDOO** [comment]
I updated the APIs and it still fails.

**Comment by Duality-CDOO** [comment]
@bmoore-msft any ideas?

**Comment by LordDarkHelmet** [comment]
From the [documentation](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md) it looks like it is used to access _artifactsLocation. Looks like you need it for uniform resource identifiers (URI). Not sure if this [link](https://docs.microsoft.com/bs-cyrl-ba/azure/azure-resource-manager/vs-azure-tools-resource-groups-deployment-projects-create-deploy) or this [link](https://docs.microsoft.com/en-us/azure/marketplace/cloud-partner-portal/virtual-machine/cpp-get-sas-uri) helps clarify. 

It shows as an "Unreferenced parameter". Have you tried removing it? (I think you need it in your case, but it is worth a check)

**Comment by Duality-CDOO** [comment]
> From the [documentation](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md) it looks like it is used to access _artifactsLocation. Looks like you need it for uniform resource identifiers (URI). Not sure if this [link](https://docs.microsoft.com/bs-cyrl-ba/azure/azure-resource-manager/vs-azure-tools-resource-groups-deployment-projects-create-deploy) or this [link](https://docs.microsoft.com/en-us/azure/marketplace/cloud-partner-portal/virtual-machine/cpp-get-sas-uri) helps clarify.
> 
> It shows as an "Unreferenced parameter". Have you tried removing it? (I think you need it in your case, but it is worth a check)

https://github.com/Azure/azure-quickstart-templates/pull/6880/commits/e201e61d9fc9ec8804fbf321232204e0bb01e3ae

That commit was me trying exactly what you suggest (one commit previous to the last, where i put it back).

This is what I have in the azuredeploy.json file:
```    "_artifactsLocation": {
      "type": "string",
      "metadata": {
        "description": "The base URI where artifacts required by this template are located. When the template is deployed using the accompanying scripts, a private location in the subscription will be used and this value will be automatically generated."
      },
      "defaultValue": "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/blockchain/"
    },
    "_artifactsLocationSasToken": {
      "type": "securestring",
      "metadata": {
        "description": "The sasToken required to access _artifactsLocation.  When the template is deployed using the accompanying scripts, a sasToken will be automatically generated."
      },
      "defaultValue": ""```

**Comment by LordDarkHelmet** [comment]
It looks like your project uses deployment artifacts.  [This part](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md#deployment-artifacts-nested-templates-scripts) states what to do.

I didn't immediately see where you were you included your URIs but if you look at this [line](https://github.com/Azure/azure-quickstart-templates/blob/61c8a3e7e24588ba8d393e8bc86edd629d939193/blockchain/azuredeploy.json#L256),  you may need to add `parameters('_artifactsLocationSasToken')` to the end. See this [example](https://docs.microsoft.com/bs-cyrl-ba/azure/azure-resource-manager/vs-azure-tools-resource-groups-deployment-projects-create-deploy#deploy-code-with-infrastructure).

**Comment by Duality-CDOO** [comment]
> It looks like your project uses deployment artifacts. [This part](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md#deployment-artifacts-nested-templates-scripts) states what to do.
> 
> I didn't immediately see where you were you included your URIs but if you look at this [line](https://github.com/Azure/azure-quickstart-templates/blob/61c8a3e7e24588ba8d393e8bc86edd629d939193/blockchain/azuredeploy.json#L256), you may need to add `parameters('_artifactsLocationSasToken')` to the end. See this [example](https://docs.microsoft.com/bs-cyrl-ba/azure/azure-resource-manager/vs-azure-tools-resource-groups-deployment-projects-create-deploy#deploy-code-with-infrastructure).

I need someone to fix this issue as I am having no luck.

**Pull request closed without merging**
