### PR TITLE
Add 101-event-grid-servicebus-queue Template

### PR DESCRIPTION
**Pull request by MarkusMeyer13**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Review by bmoore-msft — CHANGES_REQUESTED** [review]
See the pipeline results for changes that need to be made...

**Review by MarkusMeyer13 — COMMENTED** [review]
No more issues

**Comment by bmoore-msft** [comment]
@MarkusMeyer13 - I'm still seeing the same results in the pipeline...

**Comment by MarkusMeyer13** [comment]
@bmoore-msft Pipeline issues are fixed

**Pull request merged**
