### PR TITLE
Update install_manifold.sh

### PR DESCRIPTION
**Pull request by tpinckard**
### Changelog
*

### Description of the change
Add '-noprompt' to keytool command to add manifold cert

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@tpinckard__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tpinckard** [comment]
I also made an update the azuredeploy.json template, is there a way to add that change to this pull request?

**Comment by singhkay** [comment]
@tpinckard If it's in the same branch, do another commit. That will get queued up here

**Comment by tpinckard** [comment]
Wilco @singhkay! Thanks for the help sir! Not sure why the build would fail, there haven't been any sort of material changes to the template at all here...

**Comment by singhkay** [comment]
@tpinckard Looks like the dns resolution problems form xip.io causing server to not be found. I kicked off the build again

**Comment by tpinckard** [comment]
@singhkay Thanks! I'm seeing that the Travis build is still complaining

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
