### PR TITLE
Reordered template parameters

### PR DESCRIPTION
**Pull request by DigitalBanana**
---

### Changelog
*  minecraft-on-ubuntu/azuredeploy.json - reorder params passed to .sh script
*  minecraft-on-ubuntu/install_minecraft.sh - reorder params in script 

### Description of the change

unsupplied option params were causing the script to break - have updated so required params are first. have tested with optionl params supplied as blank string and works. could not recreate

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DigitalBanana__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@DigitalBanana Is it possible to have this template be automatically tested with our CI? See here https://github.com/Azure/azure-quickstart-templates/tree/master/1-CONTRIBUTION-GUIDE#travis-ci

**Comment by DigitalBanana** [comment]
@singhkay Travis ci now passing.....

**Comment by DigitalBanana** [comment]
@singhkay  not sure how to remove labels - is this something i can do?

**Comment by singhkay** [comment]
@DigitalBanana np, I remove those after the merge. Thanks for updating the parameters! merged

**Pull request merged**
