### PR TITLE
Template for ScyllaDB on VMSS

### PR DESCRIPTION
**Pull request by dciborow**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Adding example of using Scylla DB on VMSS

### CODE REVIEW

**Comment by dciborow** [comment]
@bmoore-msft , need this image approved for this quick-start template.
publisher='scylladb1631195365807' offer = 'scylla-enterprise', sku = 'scylla-enterprise-vm'

Is this something you want to consider automating? Perhaps we could add a new field to the metadata for a list of custom images used, which a script can iterate through and approve? 

idk how much time you spend fixing this for me but feels like I ask a lot :-)

**Comment by dciborow** [comment]
(i am working with ScyllaDB to get access to a VM Image which does not have additional billing for testing which is blocking us from using it internally)

**Comment by bmoore-msft** [comment]
@dciborow - is this still needed?

**Comment by bmoore-msft** [comment]
Closing abandoned request - please reopen if you can address the feedback.

**Comment by dciborow** [comment]
@bmoore-msft , sorry stuck waiting for customer to provide a version of the VM Image that we can use in this test harness.

**Comment by bmoore-msft** [comment]
ack just reopen when you're ready

**Pull request closed without merging**
