### PR TITLE
Check API versions

### PR DESCRIPTION
**Pull request by mgblythe**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@mgblythe - can you take a look at the pipeline result and advise on how customers fix that error?

**Comment by mgblythe** [comment]
@bmoore-msft - some parts of gov require an earlier API version. Should we scope to public only then I can explain that you can use an earlier API version for gov?

**Comment by bmoore-msft** [comment]
It's better to have Gov support than not, so if it's possible we should target the sample to support it.  Better to not pass BP checks than not support a cloud.  Also, eventually that should be fixed and then we have to remember to come back and fix these.

**Comment by mgblythe** [comment]
@bmoore-msft - I left the latest API version in and I added a note to the readme that you might require an earlier version for gov.

**Comment by bmoore-msft** [comment]
But that's the opposite of what I was suggesting - does this work in FF with the older API version?

**Comment by mgblythe** [comment]
@bmoore-msft - yeah I see that now that I re-read :laughing: Closing this, will leave as old version for now.

**Pull request closed without merging**
