### PR TITLE
update sharepoint server farm template to follow standard guidelines

### PR DESCRIPTION
**Pull request by arroyc**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
*
*
*
*
*

### Description of the change

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@arroyc__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (arroyc). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by mapucket** [comment]
This broke the AMP SharePoint 2013 template.  The template points to the following path "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/sharepoint-server-farm-ha/dscv2/...".  There is no DSCv2 path.  :-(  Azure deployments are failing because the ps1 files cannot be found.

**Comment by bmoore-msft** [comment]
Nice... thanks for the update.

**Comment by arroyc** [comment]
I found couple of AMP sharepoint templates using DSC and DSCV2 path from this repo .. will send a pull request which fix that ..

**Comment by mapucket-msft** [comment]
Thanks!  My customers will be very happy.  :-)

**Pull request merged**
