### PR TITLE
Update SQL MI template

### PR DESCRIPTION
**Pull request by jftl6y**
# Best Practice Checklist

Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment.
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Update the template for revised management IPs, API versions and updated NSG rules
*
*

### CODE REVIEW

**Comment by jftl6y** [comment]
@bmoore-msft I do not know if this is going to ever pass the check as it is timing out deploying the SQL Managed Instance.

**Comment by bmoore-msft** [comment]
We can do a manual test - how do we know if it completed correctly?  The log shows "Accepted" and "Failed"

**Comment by jftl6y** [comment]
@bmoore-msft I did a test deploy and it was failing because the GEN-PASSWORD token for the administrator password does not meet the password length/complexity requirements.  Generally I omit this parameter for a manual deploy (prompts the user) or pull in from a key vault for an automated deployment.  Thoughts/suggestions?

**Comment by bmoore-msft** [comment]
I don't think that's what caused the CI failure (Accepted and Failed) but aside from that, how do we validate that this works?  We can either automate the test (and fix the password complexity issue (though it seems to work for other SQL workloads so I'm not sure that's related) or perform a manual test... if manual, how to we validate that this succeeds? since even after the timeout, the test deployment did not succeed...

**Comment by jftl6y** [comment]
Close to re-submit.

**Pull request closed without merging**
