### PR TITLE
These new templates enable Capture to ADLS as destination

### PR DESCRIPTION
**Pull request by ShubhaVijayasarathy**
Enabling Event Hubs Capture to ADLS as a new destination

### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

*
*
*

### CODE REVIEW

**Comment by ShubhaVijayasarathy** [comment]
#sign-off

**Comment by gatneil** [comment]
Please merge the formatting changes here: https://github.com/ShubhaVijayasarathy/azure-quickstart-templates/pull/1

**Comment by ShubhaVijayasarathy** [comment]
We have a public preview which requires this template, can we merge this please?

**Comment by gatneil** [comment]
This template is invalid json and is improperly formatted; the link above points to a PR I made into your repo that fixes these; if you merge that, this PR will be updated with the version that I can merge :)

**Comment by gatneil** [comment]
looks good; merging

**Pull request merged**
