### PR TITLE
ARM temp

### PR DESCRIPTION
**Pull request by anvar-ms**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@rahul-gupta - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by bmoore-msft** [comment]
@rahul-gupta - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by bmoore-msft** [comment]
@rahul-gupta - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by rahug1190** [comment]
@bmoore-msft we need help to understand why the build is failing. I have fixed the issues that were showing up earlier but the current error "PowerShell exited with code: 1" is something that I am unable to decode to figure out what the issue is. Could you please advise?

**Comment by bmoore-msft** [comment]
You need to click "view more details on Azure pipelines" and look at the logs.

**Comment by rahug1190** [comment]
@bmoore-msft Thanks for the guidance Brian. I checked the errors and I will still need help resolving them. Below is my understanding and analysis of the errors. 
1. The best practice test is failing due to null values in the ARM template - This is by design and this is how currently our ARM deployments happen behind the scenes when the customer provides the inputs through GUI. So this is an expected input. 
2. Template deployment failing - The template deployment is failing because the automated deployment is picking a region where the service isn't available or is choosing a subscription that does not have access to the service in the region. I am not sure how to resolve this.

Would need help to understand how to move forward on these. Thanks in advance!

**Comment by bmoore-msft** [comment]
re: #1 - not sure I follow but if you're saying that you used code-gen of some sort on the template and that put those properties in the template, then you need to remove them manually.

for #2 - the defaultLocation for the deployments is westus/usgovvirginia - you can override that value in the parameters file for each cloud.  If the service is not global (and will never be global) use allowedValues in the template to restrict the location.

**Comment by bmoore-msft** [comment]
@rahul-gupta - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by bmoore-msft** [comment]
@rahul-gupta - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by bmoore-msft** [comment]
@rahul-gupta - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by bmoore-msft** [comment]
@rahul-gupta - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by anvar-ms** [comment]
#sign-off

**Pull request closed without merging**
