### PR TITLE
Imagebuilder/patch1

### PR DESCRIPTION
**Pull request by mgreenegit**
Fix for broken deployment script

### CODE REVIEW

**Review by bmoore-msft — CHANGES_REQUESTED** [review]
you'll need to update the bicep source and then do ```bicep build``` to generate azuredeploy.json

**Comment by mgreenegit** [comment]
@bmoore-msft I'm confused. I did that before pushing and the files are already in sync. What is the ask to build again? The files won't change, so I would have nothing to push (based on my understanding).

**Comment by bmoore-msft** [comment]
You fixed the bug in azuredeploy.json directly - the fix needs to be done in the "source" which is bicep in this case.  Then build the json file using the ```bicep build``` command.  Right now, the bicep and the json are not the same.

**Comment by mgreenegit** [comment]
What am I missing?

image

**Pull request merged**
