### PR TITLE
Quickstart demonstrating configuration of Azure Functions Premium plan with availability zones support

### PR DESCRIPTION
**Pull request by nzthiago**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by nzthiago** [comment]
@bmoore-msft can you please help me with the following for this PR:
* It was it was just a point in time and it'd eventually show up, but this template still doesn't show up on the quickstarts index page, is there something I missed for it to flow there? https://azure.microsoft.com/en-us/resources/templates/?term=Azure%20Functions%20Premium
* What does the 'remove azuredeploy.json' tag mean?

**Comment by bmoore-msft** [comment]
https://azure.microsoft.com/en-us/resources/templates is being deprecated - the new location is here: https://learn.microsoft.com/en-us/samples/azure/azure-quickstart-templates/function-premium-availability-zone/

the `remove azuredeploy.json` tag means the file should be removed from the PR.  If a sample contains bicep, azuredeploy.json will be generated during CI

**Comment by nzthiago** [comment]
Ah, ok - thank you for clarifying. Given the PR has been merged I'll leave it as is for now, is that ok?
I suspect eventually that deprecated link will redirect to the new one eventually.

**Comment by bmoore-msft** [comment]
redirs will be added for the existing samples, if it was never listed on ACOM the redir will just go to the query page...  It's fine to leave as is...

**Pull request merged**
