### PR TITLE
Updated metadata and Gremlin APIs

### PR DESCRIPTION
**Pull request by JFolberth**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* APIs updated to 2020-06-01-preview
* Updated dateUpdated in metadata

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@JFolberth - something about this change is causing a failure in Fairfax - the test is passing prior to the change (just ran another one).

**Comment by JFolberth** [comment]
Yup, I'm not sure either.  Yesterday I updated the secondary location to Texas in #8609 and it worked.  I will update this one and see how it works.  Thought it was interesting too.

**Comment by bmoore-msft** [comment]
if that does fix it - we should file a ticket to figure out what's going on in usgovvirginia

**Comment by JFolberth** [comment]
@bmoore-msft It's cleaning up the resources but the deployment worked when switching the region.  What path should we take to file a ticket about usgovvirginia?

**Comment by bmoore-msft** [comment]
Grab a correlationId from a failed deployment and open in ICM for the RP...

**Comment by JFolberth** [comment]
Dumb question....what is ICM?  Believe RP is Resource Provider.

**Comment by bmoore-msft** [comment]
ICM = service incident

**Comment by JFolberth** [comment]
Is that just through the portal or is there a specific place for it since it's occurred in a non customer subscription?

**Comment by bmoore-msft** [comment]
Well whatever it was it looks like it's fixed... so I'll leave it at that ;)

**Pull request merged**
