### PR TITLE
Workspace PNA flag update in arm template and bicep

### PR DESCRIPTION
**Pull request by mingweihe**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Updated workspace resource version from 2021-10-01 to 2022-01-01-preview
* Added publicNetworkAccess: 'Disabled'
* Removed allowPublicAccessWhenBehindVnet: false

### CODE REVIEW

**Review by bmoore-msft — CHANGES_REQUESTED** [review]
Can you update the date in metadata.json?

**Comment by mingweihe** [comment]
> Can you update the date in metadata.json?

Updated, thanks for the request.

**Comment by mingweihe** [comment]
> Can you update the date in metadata.json?

Hi @bmoore-msft , I tried, but that also introduced lots of build errors, it requires updating versions for some other resources which I've never used before, can we please skip the metadata update?

**Comment by mingweihe** [comment]
Hi @bmoore-msft , thanks for the request. I've updated metadata.json file.
The deployment in my local box by using the "az deployment" command succeeded,
The AzquickStarts-MAC verification succeeded. I believe the reason AzquickStarts-USGov pipeline failed is because of the region, for example the VM deployment in the template was failed in US west, while it's succeeded in US west2, the USGov is probably similar.
So would you like to approve the PR if everything looks good to you.
If the USGov verification is mandatory, then please kindly let me know the way to fix it, I was not able to fix the issue according to the error log there. Thanks a lot!

**Comment by bmoore-msft** [comment]
We do need to work our what's going on in Fairfax - I don't think it's location since that error message is pretty clear and happens before deployment begins.  This is failing 10 minutes in on the ```machineLearningPrivateEndpoint``` resource.  First step would be to determine if the workload is supported in FF.

Also, the bicep files have some linter warnings, need to get those cleaned up as well.

**Comment by mingweihe** [comment]
> 



> We do need to work our what's going on in Fairfax - I don't think it's location since that error message is pretty clear and happens before deployment begins. This is failing 10 minutes in on the `machineLearningPrivateEndpoint` resource. First step would be to determine if the workload is supported in FF.
> 
> Also, the bicep files have some linter warnings, need to get those cleaned up as well.

**Comment by mingweihe** [comment]
> Can you update the date in metadata.json?

Done the update, please review again, thanks.

**Pull request merged**
