### PR TITLE
Made apiVersion properties a set of variables across a template. #934

### PR DESCRIPTION
**Pull request by boutquin**
Added variables for apiVersion to visual-studio-dev-vm template; successfully deployed in US East2.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@boutquin__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by boutquin** [comment]
Hi @singhkay,

Modestly started to work on your APi version help wanted issue #934. Experienced coder, but new to GitHub & open arc.

Not sure how to make Travis happy --deployed the latest commit to my Azure account.

**Comment by boutquin** [comment]
Open src --not arc. Darn auto-correct. ;)

**Comment by sedouard** [comment]
@boutquin CI templates are deployed to westus so maybe that's causing the invalid value error

**Comment by boutquin** [comment]
Will fix the parameter file; likely the cause of the failed CI Test.

**Pull request closed without merging**
