### PR TITLE
Bank login

### PR DESCRIPTION
**Pull request by tarikbas**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

*
*
*

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@tarikbas - what's the intent of the change here, seems we're downgrading the template?

**Comment by Ashofstone13977** [comment]
I never knew about this site

**Comment by Ashofstone13977** [comment]
Bank login I didn't do sounds wrong

**Comment by Ashofstone13977** [comment]
Asking for password to be changed on site with a bank login I'm not aware of add it up

**Comment by bmoore-msft** [comment]
Not clear on why we're downgrading this sample - please reopen if we can clear up the confusion

**Comment by Ashofstone13977** [comment]
HuhOn Mar 8, 2020 10:34 AM, Brian Moore <notifications@github.com> wrote:Closed #7191.

**Pull request closed without merging**
