### PR TITLE
Added VM template with ESET File Security extension

### PR DESCRIPTION
**Pull request by branislavsimo**
I've created a new VM template example containing the ESET file security extension.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@branislavsimo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@branislavsimo Please add dummy values for your parameters in the parameters file

**Comment by branislavsimo** [comment]
You mean azuredeploy-parameters.json? Or something else?

**Comment by singhkay** [comment]
@branislavsimo yep, the azuredeploy-parameters.json file

**Comment by singhkay** [comment]
@branislavsimo Looks good, please sign the CLA as well before we can merge

**Comment by singhkay** [comment]
Closing due to duplicate PR https://github.com/Azure/azure-quickstart-templates/pull/395

**Pull request closed without merging**
