### PR TITLE
Added the support for multiple XSLT parameters.

### PR DESCRIPTION
**Pull request by jaakhter**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
*
*
*
*
*

### Description of the change
The function ARM template is updated to include the change in one of the script files. The change is to support multiple XSLT parameters while invoking the transform XSLT function.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jaakhter__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jaakhter). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by jaakhter** [comment]
The CI build is expected to fail as the template is dependent on an existing function app which is passed as a parameter. The template deploys an Azure function in that existing function app.

**Comment by jaakhter** [comment]
@bmoore-msft, can you please look into my pull request?

**Comment by jaakhter** [comment]
Hi @bmoore-msft, please look into my request or suggest any other person who can help. The change is required to be published soon as customers are waiting.

Thank you.

**Pull request merged**
