### PR TITLE
Removed function app dependency for GA version

### PR DESCRIPTION
**Pull request by vinaysingh123**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

*
*
*

### CODE REVIEW

**Comment by gatneil** [comment]
Can we fix the merge conflicts?

**Comment by vinaysingh123** [comment]
@gatneil It says: This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests. 

Is there anything I need to do?

**Comment by gatneil** [comment]
merged https://github.com/Azure/azure-quickstart-templates/pull/2914 instead, which does the same thing but without merge conflicts :)

**Comment by gatneil** [comment]
I just noticed this PR also included changes in the 201-logic-app-xslt-with-params folder, but #2914 didn't have these changes; do we need one more PR for these changes?

**Pull request closed without merging**
