### PR TITLE
Added output parameter for Linux hostname

### PR DESCRIPTION
**Pull request by pcgeek86**
### Changelog
* Added output parameter for Linux hostname
* Added sshCommand output parameter

### Description of the change
Added output parameter for Linux hostname
Added sshCommand output parameter

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pcgeek86__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by pcgeek86** [comment]
@singhkay Is that error from acomghbot valid? I'm not seeing an issue.

**Comment by singhkay** [comment]
@pcgeek86 Neat changes! Ignore acomghbot for now. The ARM Validate API started checking for available DNS names and storage account failures early which is why acomghbot is complaining. I have a work item open for the Azure.com team to fix. merged.

**Comment by pcgeek86** [comment]
@singhkay I stole the idea from some other templates I've seen on here. :smile: I think the Azure Container Service (ACS) guys have been doing something like this. @ahmetalpbalkan

**Pull request merged**
