### PR TITLE
Updates ARM template files - Data Share

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template used in ARM template [quickstart](https://docs.microsoft.com/azure/data-share/share-your-data-arm) article.
- Adds quickstart article's author to `docOwner` in _metadata.json_.
- Updates _azuredeploy.json_ to latest schema version 2019-04-01.
- Updates _README.md_ with link to the quickstart article.

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@mumian - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
To fix build errors, reverts the `apiVersion `for Storage resources.

**Comment by bmoore-msft** [comment]
@mumian - check this PR for updates that may be needed to documentation that references this sample.

**Comment by mumian** [comment]
@bmoore-msft - The update looks good.

**Pull request merged**
