### PR TITLE
Kvaes docker rancher

### PR DESCRIPTION
**Pull request by kvaes**
Updated version to be more dynamic after a change in the tags of the rancher project

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kvaes__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@kvaes Can you resolve merge conflict?

**Comment by singhkay** [comment]
@kvaes Something weird is going on with this PR. It's showing a bunch of commits but no files changed 

image

**Comment by kvaes** [comment]
That's due to the fact that I was kinda stupid and doing a rebae instead of a merge...

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
