### PR TITLE
Update template to make all deployment happen in template not in azure CLI

### PR DESCRIPTION
**Pull request by ostclilideng**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

* Not use azure CLI in script
* Deploy backend vms and route table in template
* All deployment time cost 5 mins instead of 30 mins which use previous solution

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ostclilideng__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by ostclilideng** [comment]
@gatneil could you please help review my new changes?

**Comment by KylieLiang** [comment]
@gatneil Could you please help review the changes? It refined the content of readme and also updated the template to shorten the deployment time. Once it is available, we will promote it in upcoming event. Thank you.

**Comment by ostclilideng** [comment]
@gatneil could you please help review my new changes?

**Comment by gatneil** [comment]
Looks good; merging

**Pull request merged**
