### PR TITLE
Add vertcoin to blockchain

### PR DESCRIPTION
**Pull request by vertiond**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Added Vertcoin to Azure quickstart

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@vertiond - I tried a test using the new script for vertcoin and the extension times out...  the *usually* means the script is prompting for something.  Can you have a look?

**Comment by vertiond** [comment]
Ah.  Missed the `$` for an environment variable.

**Comment by bmoore-msft** [comment]
ok, did you push the changes?  I couldn't find a new commit and ran another build - same result...  When you do push, make sure you pull first or update the param file to test the vertcoin option...

**Comment by vertiond** [comment]
I added `software-properties-common` to enable `add-apt-repository` command.

**Comment by vertiond** [comment]
I just tested this on latest Ubuntu Server 18.04.6 and found it to work.

**Review by bmoore-msft — CHANGES_REQUESTED** [review]
We need to change azuredeploy.parameters.json to test vertcoin... I changed it but your force push keeps overwriting it.

**Comment by vertiond** [comment]
I have no idea, sorry.  I don't understand how Groestlcoin works then considering it follows the same template.

**Comment by vertiond** [comment]
Note: I got the same error as https://github.com/Azure/azure-quickstart-templates/issues/12216 when deploying the groestlcoin template using SSH public key as Authentication Type.

```
Error type

Deployment template validation failed: 'The value for the template parameter 'adminPasswordOrKey' at line '65' and column '27' is not provided. Please see https://aka.ms/resource-manager-parameter-files for usage details.'. (Code: InvalidTemplate)
```

**Comment by bmoore-msft** [comment]
> Note: I got the same error as #12216 when deploying the groestlcoin template using SSH public key as Authentication Type.
> 
> ```
> Error type
> 
> Deployment template validation failed: 'The value for the template parameter 'adminPasswordOrKey' at line '65' and column '27' is not provided. Please see https://aka.ms/resource-manager-parameter-files for usage details.'. (Code: InvalidTemplate)
> ```

Via Portal?  You have to use an existing publicKey that you supply - the other options are broken in portal

**Pull request closed without merging**
