### PR TITLE
Initial commit of Solace community edition of VMR

### PR DESCRIPTION
**Pull request by KenBarr**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

*
*
*

### CODE REVIEW

**Comment by azurecla** [comment]
__@KenBarr__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by KenBarr** [comment]
Struggling a bit with how travis validated CustomScript fileUris.
It seemed to be failing on a parameter in the fileUris.   Now it seems to be simply timing out.

Any guidance or assistance would be greatly appreciated.

**Comment by KenBarr** [comment]
Finally had time to troubleshoot this and get it running.  Would like to know next steps.

**Comment by KenBarr** [comment]
Time is marching forward.  Have moved from simple single instance to ability to do singleton, or ha cluster.  Interested in moving forward and get this pull request committed.

**Pull request merged**
