### PR TITLE
Removed autoUpdateClient flag used for Chef Extension

### PR DESCRIPTION
**Pull request by dheerajd-msys**
Removed autoUpdateClient flag used for Chef Extension from chef-json-parameters-linux-vm and multi-vm-chef-template-ubuntu-vm templates

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dheerajd-msys__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by dheerajd-msys** [comment]
@singhkay 
As we don't provide actual chef server details, so the travis fails for the templates.
Can you please merge the PR

**Comment by NimishaS** [comment]
@singhkay , please review this PR

**Comment by NimishaS** [comment]
@singhkay , we are tracking this task in our internal process and waiting for this to be merged. Please update here if you have any review comments. We'll make the necessary changes.

**Comment by btm** [comment]
@NimishaS have you looked at the travis failure?

**Comment by dheerajd-msys** [comment]
@btm,

Yes i had looked into the travis failure. 
First travis failure is same as travis failure in https://github.com/Azure/azure-quickstart-templates/pull/1385. 
@singhkay  comment on the same :- https://github.com/Azure/azure-quickstart-templates/pull/1385#issuecomment-197171444
Second failure is due to when the `multi-vm-chef-template-ubuntu-vm` template was added, the  `numberOfInstances` value was set as `number of VMs to create` instead of a particular number, so that it is easy for user to understand, hence the failure.  [code here](https://github.com/Azure/azure-quickstart-templates/blob/master/multi-vm-chef-template-ubuntu-vm/azuredeploy.parameters.json#L17)
No changes from our side are required, from our end, this can be merged directly.

**Comment by singhkays** [comment]
@btm The failure is expected since our CI doesn't have a Chef server to point to. Sorry for the delay in reviewing, been busy with other stuff. In the future you can ping a couple of other folks on cc below. Merging this one. 

cc: @bmoore-msft @gatneil

**Pull request merged**
