### PR TITLE
updated versions

### PR DESCRIPTION
**Pull request by trentmswanson**
updated es versions allowed
updated kibana script install version

### CODE REVIEW

**Comment by trentmswanson** [comment]
This deploys just fine for me and CI does not seem to provide any useful information as to why it failed the checks.

**Comment by sedouard** [comment]
hey @trentmswanson as the [CI guidance](https://github.com/Azure/azure-quickstart-templates#parameters-file-placeholders) suggests can you try `GEN-PASSWORD` instead?

**Comment by trentmswanson** [comment]
Cool!  Thanks @sedouard.

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
