### PR TITLE
Add Stratis

### PR DESCRIPTION
**Pull request by sigwo**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
* Added Stratis details and build options

### Description of the change
Created template for Stratis to deploy on Azure.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sigwo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by bmoore-msft** [comment]
Is there any reason we can combine this sample with the blockchain sample?

**Comment by sigwo** [comment]
No, there is no reason to not combine. I am glad to see the PR was merged. Can you merge this PR and I'll submit a new PR with Stratis in the combined blockchain sample?

**Comment by bmoore-msft** [comment]
Ok, cool - but we don't want to merge this because we'd just have to do another PR to remove it...  We can just close it and fold your changes into the blockchain sample...

**Comment by sigwo** [comment]
No prob. I'll do it up tonight and submit.

**Comment by bmoore-msft** [comment]
Sounds good - @ me so I see it, should be simple to review.

**Pull request closed without merging**
