### PR TITLE
Supporting an optional switch parameter "ShowProperties" for DTL cmdlets. 

### PR DESCRIPTION
**Pull request by mithunshanbhag**
This switch parameter will fetch the extended information (properties) of DTL resources like labs, VMs and VM templates.

Note: This change has no impact on the Azure RM Templates.

### CODE REVIEW

**Comment by singhkay** [comment]
@mithunshanbhag What is the use case for this powershell script for template deployment users?

**Comment by mithunshanbhag** [comment]
The powershell script provides many quick-and-dirty wrapper cmdlets over the Azure RM template deployments (to create of various DevTestLab RP entities  like labs, VMs, VM templates etc).

**Comment by singhkay** [comment]
@mithunshanbhag Is the PS script using the templates in this repo?

**Comment by mithunshanbhag** [comment]
@singhkay Yes. It uses all five of our team's Azure RM Template. 
- 101-dtl-create-lab
- 101-dtl-create-vm-builtin-user
- 101-dtl-create-vm-username-pwd
- 101-dtl-create-vm-username-ssh
- 201-dtl-create-vmtemplate

**Pull request merged**
