### PR TITLE
Add Standard A Series VMs

### PR DESCRIPTION
**Pull request by furqansoftech**
Add Standard A Series VMs in AD and SQL Witness VM allowed values.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@furqansoftech__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by furqansoftech** [comment]
I am trying to add A Series VMs in AD and SQL witness Allowed Values. Someone please help me

**Comment by singhkay** [comment]
@furqansoftech Change looks good but looks like the metadata file has a problem from the Travis CI log. Can you check?

AssertionError: sql-server-2014-alwayson-dsc/metadata.json is not valid JSON. Copy and paste the contents to https://jsonformatter.curiousconcept.com/ and correct the syntax errors. Error: SyntaxError: Unexpected token

**Comment by furqansoftech** [comment]
metadata files looks okay for me. but I can see ADVmTemplate.json and SqlWitnessVmTemplate.json	both files do not have A series VMs in allowed list. Do I need to update these files as well?
Thanks

**Comment by singhkay** [comment]
@furqansoftech Looks like the metadata.json file is not valid JSON and has an unallowed newline. Try checking with jsonlint.com. Sure, you can add the sizes to those files as well.

**Comment by singhkay** [comment]
@furqansoftech Any update on this?

**Comment by singhkay** [comment]
@furqansoftech Any update on this?

**Comment by singhkay** [comment]
@furqansoftech Closing due to lack of activity. Feel free to reopen with an update.

**Pull request closed without merging**
