### PR TITLE
Azure Databricks Custom VNet Updates

### PR DESCRIPTION
**Pull request by tw3lveparsecs**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

* Added parameters vnetName and vnetResourceGroup
* Updated template to generate VNet ID based off vnetName and vnetResourceGroup parameters instead of having it as a string value that the user needs to retrieve.
* Removed customVirtualNetworkID parameter as no longer required.
* Added parameter managedResourceGroupName to allow users to control the name of the additional resource group that gets created.

### CODE REVIEW

**Comment by botang-databricks** [comment]
For the `managedResourceGroupName` change, we prefer changing it back to the auto-generated one. It would be confusing for customer to ask them specify a managed resource group. We also required the managed resource group cannot be any existing resource group.

**Comment by tw3lveparsecs** [comment]
@botang-databricks  just some feedback to consider as i have deployed this for two established customers now and is the reason i submitted this change.

- Each customer already had a VNet deployed and do not use the prereqs templates, therefore having the customer input the resource id for the VNet as a parameter is unacceptable in my opinion and leads to confusion.

- Each customer has naming standards they need to follow and would like flexibility to names things as they wish, hence the change for `managedResourceGroupName `

- Agreed the managed resource group cannot be any existing resource group, which is why the description states it will create a new resource group.

Perhaps you may want to consider using this template as another version of Databricks, perhaps a 102 version to cater for existing VNets and customer naming standards?

**Comment by bmoore-msft** [comment]
There was a breaking change in a new version of node/npm - update your .travis.yml file to pick up that change or open a new PR after pulling from master.

**Comment by bmoore-msft** [comment]
Closing abandoned request - please reopen if you can address the feedback.

**Pull request closed without merging**
