### PR TITLE
FIX-TEMPLATE: 101-backup-create-storage-account-enable-protection

### PR DESCRIPTION
**Pull request by olga-spektra**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by olga-spektra** [comment]
@bmoore-msft There was nothing to fix, but Azure public test status is 'failed' in master branch. Creating PR to overwrite it.

**Comment by bmoore-msft** [comment]
@olga-spektra - ok I see (I already merged the other one) - but in order for the badges to update there need to be a change... otherwise the pipeline is not executed.

**Comment by olga-spektra** [comment]
i noticed that the deployment failed when adding the change to trigger the pipelines - roleAssignments seems to be having a problem with the timing when assigning the role to the resource that has systemAssigned identity, it kept throwing the 'service principal not found in the directory" error. adding "principalType": "ServicePrincipal" seems to have resolved this.

**Comment by bmoore-msft** [comment]
that was the correct fix...

**Pull request merged**
