### PR TITLE
init gamecredits azure blockchain template

### PR DESCRIPTION
**Pull request by gamers-coin**
### Contributing guide

https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md
### Changelog
- init gamecredits azure blockchain template 25/10/2016
  *
  *
  *
  *
### Description of the change

init gamecredits azure blockchain template

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gamers-coin__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@gamers-coin__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by gatneil** [comment]
Looks like there are merge conflicts; can these be fixed?

**Comment by gatneil** [comment]
No activity; closing

**Pull request closed without merging**
