### PR TITLE
update cmdlets, add enabledForTemplateDeployment

### PR DESCRIPTION
**Pull request by bvirkler**
Updated the cmdlet names to new ARM Powershell 1.0 names.
Added enabledForTemplateDeployment as documented [here](https://msdn.microsoft.com/en-us/library/azure/mt620025.aspx).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bvirkler__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@bvirkler Thanks for fixing! Will wait for you to sign the CLA before merging.

**Comment by bvirkler** [comment]
Just realized my company would have to sign the CLA which probably won't happen. :disappointed: You may as well decline/delete the PR.

**Comment by singhkay** [comment]
@bvirkler That's a shame. Any reasons why you company wouldn't sign the CLA?

**Comment by bvirkler** [comment]
It's a very large company with a very conservative legal department.  I could probably get it done, but not before my changes were obsolete. :)

**Comment by singhkay** [comment]
@bvirkler No worries, I created #1358 based on this

**Pull request closed without merging**
