### PR TITLE
Added enableNoPublicIp Property to deploy Databricks workspace with secure cluster connectivity (SCC)- Update NON VNET Databricks 101 template

### PR DESCRIPTION
**Pull request by msaranga**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Added new property "enableNoPublicIp" with default value FALSE

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@mamccrea - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by mamccrea** [comment]
FYI @JasonWHowell

**Comment by JasonWHowell** [comment]
Related https://docs.microsoft.com/azure/databricks/scenarios/quickstart-create-databricks-workspace-resource-manager-template

**Comment by bmoore-msft** [comment]
@mamccrea - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by JasonWHowell** [comment]
@bmoore-msft Is there a way to update the automation? Mary is not on this project anymore.

**Comment by bmoore-msft** [comment]
@JasonWHowell - just update the docOwner in the metadata.json file...

**Comment by mamccrea** [comment]
@bmoore-msft @JasonWHowell I don't see docOwner in the metadata.json file currently.

**Comment by bmoore-msft** [comment]
I think that's because this PR contains changes from 2 samples (which is why the pipeline is failing).  @msaranga will have to fix that first...

**Comment by bmoore-msft** [comment]
@mamccrea - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by msaranga** [comment]
@bmoore-msft @mamccrea @JasonWHowell : Can any one approve this PR

**Review by Bellybutn278 — COMMENTED** [review]
Merge only with approval

**Comment by Bellybutn278** [comment]
> @JasonWHowell - just update the docOwner in the metadata.json file...

Yes vellybutn278 :)

**Comment by msaranga** [comment]
> Merge only with approval

thanks. will wait for approval

**Pull request merged**
