### PR TITLE
Added new ARM template to deploy S2S VPN using BGP

### PR DESCRIPTION
**Pull request by bhummerstone**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
*
*
*
*
*

### Description of the change

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bhummerstone__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@bhummerstone Can you sign the CLA?

**Comment by bhummerstone** [comment]
@singhkay Do I still need to sign the CLA?

**Comment by singhkay** [comment]
@bhummerstone Yes, once you do, the bot should remove the tag "cla-required"

**Pull request closed without merging**
