### PR TITLE
Migrate bicep example: 101/logic-app-create

### PR DESCRIPTION
**Pull request by StephenWeatherford**
Added bicep support to this sample by integrating bicep.main from the example in https://github.com/Azure/bicep/tree/main/docs/examples/101/logic-app-create

The corresponding PR for the modified bicep example is here: https://github.com/Azure/bicep/pull/3177

### CODE REVIEW

**Comment by StephenWeatherford** [comment]
NOTE: I'm expecting a warning from the bicep linter that we'll need to ignore due to the following bug: https://github.com/Azure/bicep/issues/3176

**Comment by azure-quickstarts** [comment]
@ecfan - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by ecfan** [comment]
@Azure/azure-logicapps-team: Could you please review and identify what changes, if any, are necessary in the main docs for Azure Logic Apps? Thanks!

**Comment by StephenWeatherford** [comment]
FYI @jeffhollan. You're welcome to review if you'd like.

**Pull request merged**
