### PR TITLE
Upgrade to HA Proxy 1.6

### PR DESCRIPTION
**Pull request by stevenlivz**
### Description of the change
Upgrade to use HA Proxy 1.6. This allows us to use tcp-check, ssl and other newer features of HA Proxy. Note you need to use "bind" now.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@stevenlivz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@stevenlivz the CI failed with error https://travis-ci.org/Azure/azure-quickstart-templates/builds/130229020#L224. Can you check?

**Comment by stevenlivz** [comment]
It's probably because it adds a new PPA ... is this restricted in this build? 

"Cannot add PPA: 'ppa:vbernat/haproxy-1.6'.\nPlease check that the PPA name or format is correct."

Works fine on the 5 VMs and multiple deployments i've made with it.

**Comment by singhkay** [comment]
@stevenlivz Shouldn't be. Let me try and spin up a VM and try running the script interactively to see if I can find any more errors.

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
