### PR TITLE
Updates ARM template files - AKS

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template used in ARM template [quickstart](https://docs.microsoft.com/azure/aks/kubernetes-walkthrough-rm-template) article.
- Adds quickstart article's author to `docOwner` in _metadata.json_.
- Updates _README.md_ with link to the quickstart article and copyedits.
- Fixes order of template's `parameters` and `resources` properties based on best practices guidance.
- Fixes indentation.

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@mlearned - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
@bmoore-msft The **Deploy mainTemplate** step has run **Checking the deployment status** for 60+ minutes. Can you terminate the build?

**Comment by davidsmatlak** [comment]
The build failed with the error: **Must define at least one system pool.** The template's `Microsoft.ContainerService/managedClusters` API version was updated to 2020-03-01 in May 2020 and that build was successful so I'll revert the API version.

Found some additional about `mode` in the template's `agentPoolProfiles`:

- Issue Azure/AKS#1568 that since `Microsoft.ContainerService/managedClusters` API 2020-03-01 the `agentPoolProfiles` must define `mode` as `System` or `User`.
- [AKS release notes 2020-04-13](https://github.com/Azure/AKS/releases/tag/2020-04-13)
- [Limitataions](https://docs.microsoft.com/en-us/azure/aks/use-system-pools#limitations)
- [Microsoft.ContainerService managedClusters template reference](https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/2020-03-01/managedclusters)

**Comment by bmoore-msft** [comment]
@mlearned - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
@mlearned If the latest `apiVersion` and `mode` are needed, please update the template. For more information, see my previous [comment](https://github.com/Azure/azure-quickstart-templates/pull/8256#issuecomment-696810386).

**Comment by davidsmatlak** [comment]
@mlearned If the latest `apiVersion` and `mode` are needed, please update the template and [quickstart](https://docs.microsoft.com/azure/aks/kubernetes-walkthrough-rm-template) article. For more information, see my previous [comment](https://github.com/Azure/azure-quickstart-templates/pull/8256#issuecomment-696810386).

**Pull request merged**
