### PR TITLE
Master

### PR DESCRIPTION
**Pull request by anhowe**
README additions and point to correct script share

- template descriptions from @clca
- fix docker command specified in workload
- fix the main script link

@ahmetalpbalkan

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@anhowe__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by anhowe** [comment]
I did fill out the CLA form, but it still nags.

**Comment by anhowe** [comment]
@ahmetalpbalkan  - Thanks, I'll do that in pull requests from now on.

**Comment by ahmetalpbalkan** [comment]
@anhowe AFAIK we don't list parameters in the README anymore. @singhkay can give more context..

Also for those stuff please use single-backtick to escape keywords like `this` to make them look good in Markdown. https://guides.github.com/features/mastering-markdown/

**Comment by ahmetalpbalkan** [comment]
looks like it's merged now, please consider removing parameters in another PR.

**Comment by rgardler** [comment]
Not sure what the policy is but having documentation in the readme is a good thing. This is documentation, not a list of parameters. In my opinion it should stay.

Backticks are good, but I don't think it's sensible to block improved documentation on a presentation issue. One step at a time.

**Comment by rgardler** [comment]
@ahmetalpbalkan Sorry that sounds ungrateful when I read it back. Of course your points are valid and appreciated. Backticks will be added :-)

**Comment by ahmetalpbalkan** [comment]
@rgardler I believe the readmes will be rendered in the Azure.com website as well and that system knows how to infer parameters from the template JSON. That's why I was forced to remove my precious parameters from my templates as well. :)

**Comment by rgardler** [comment]
@ahmetalpbalkan Thanks for the heads up. @singhkay thoughts?

**Comment by singhkay** [comment]
@rgardler Yep, the readme's were supposed to have been rendered by now but I hear Guy's team ran into some roadblocks

**Comment by anhowe** [comment]
I'll add these with back ticks.  It was a customer who submitted a pull request to me and that's why I took them, because he felt they were missing.  Then when the other team is unblocked, I'll remove again.

**Comment by ahmetalpbalkan** [comment]
Also keep in mind Markdown supports table syntax, many template directories were using that, maybe there are still some out there. It's a nice format to present parameters. 



— Ahmet Alp Balkan http://alp.im

**Pull request merged**
