### PR TITLE
[function app dedicated github deploy] - update API versions and add …

### PR DESCRIPTION
**Pull request by mumian**
…Bicep

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by mumian** [comment]
@seesharprun - did you create this template?  https://github.com/AzureBytes/functionshttpecho.git is not a public repo.

**Comment by seesharprun** [comment]
I worked on this template years ago back when that repository existed. It no longer exists.

For this template, you can change RepoURL to be a parameter without a default value. Here's an example: https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.web/function-app-dedicated-github-deploy/azuredeploy.json#L44-L50

**Comment by mumian** [comment]
@seesharprun - without the default value, I will need to specify a value in the parameters file - https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.web/function-app-dedicated-github-deploy/azuredeploy.parameters.json.  The template pipeline needs a value to test the deployment before the PR can be merged.

**Comment by mumian** [comment]
New PR - https://github.com/Azure/azure-quickstart-templates/pull/13971

**Pull request closed without merging**
