### PR TITLE
removing invalid property

### PR DESCRIPTION
**Pull request by tfitzmac**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@tfitzmac__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (tomfitz). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@tfitzmac Looking at this template in detail it seems the diagnosticsStorageAccount needs to be setup before executing this template. Is that correct? If so can you rename the parameter "diagnosticsStorageAccountName" to "existingDiagnosticsStorageAccountName" to make it clear to the user when entering values in the UI

**Comment by tfitzmac** [comment]
@singhkay updated the parameter name

**Comment by singhkay** [comment]
Thanks @tfitzmac! merged

**Pull request merged**
