### PR TITLE
Updates ARM template files - Linux VM

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template used in ARM template [quickstart](https://docs.microsoft.com/azure/virtual-machines/linux/quick-create-template) article.
- Adds quickstart article's author to `docOwner` in _metadata.json_.
- Updates _README.md_ with link to the quickstart article.
- Updates resource `type` to the latest `apiVersion`.
- Fixes order of template's `resources` properties based on best practices guidance.
- Fixes indentation.

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@cynthn - check this PR for updates that may be needed to documentation that references this sample.

**Comment by cynthn** [comment]
@davidsmatlak and @bmoore-msft - cool! Looks like this adds back support of SSH keys? I can't update the topic in azure-docs-pr until we get past the Ignite lockdown, but I'll create a work item to pull over the new .json ASAP.

**Comment by cynthn** [comment]
FYI - work item for doc fix: https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1669561

**Comment by davidsmatlak** [comment]
@cynthn This PR didn't make any changes for SSH support. When this PR is merged, the quickstart article should show the updated JSON template.

**Pull request merged**
