### PR TITLE
Initial commit of cloudera_on_centos template

### PR DESCRIPTION
**Pull request by predeekc**
This is the initial push of the Cloudera template

### CODE REVIEW

**Comment by predeekc** [comment]
When you say title in metadata.json, I assume you are referring to itemDisplayName?

**Comment by singhkay** [comment]
@predeekc Yep. It'll look better on the Azure.com index columns
image 2

**Comment by predeekc** [comment]
Those changes are updated and pushed.  Let me know if there are any other issues

**Comment by singhkay** [comment]
merged, thanks!

**Comment by predeekc** [comment]
Hold on, missed updating the url

**Comment by predeekc** [comment]
Oh well, I'll submit another shortly :)

**Pull request merged**
