### PR TITLE
Adding hdinsight-linux deployment template.

### PR DESCRIPTION
**Pull request by matt1883**
Adding hdinsight-linux deployment template. (windows version coming
soon!)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@matt1883__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@matt1883 Looks good. Before I merge, can you rename the folders to  hdinsight-linux-ssh-password and  hdinsight-linux-ssh-publickey for clearer reading. Thx!

**Comment by musazaidi** [comment]
Question I have for you is if we can add the metastore connection information for hive and oozie.

**Comment by singhkay** [comment]
Adding @matt1883 to take a look at this question

**Pull request merged**
