### PR TITLE
Added instruction in README to create mysql backup from slave and transfer backup file to azure blog storage

### PR DESCRIPTION
**Pull request by maniSbindra**
### Changelog
* Modified README file. Added instructions to create mysql backup from slave and transfer backup file to azure blog storage

### Description of the change
* Modified README file. Added instructions to create mysql backup from slave and transfer backup file to azure blog storage

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@maniSbindra__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by maniSbindra** [comment]
Will submit pull  request through org profile so that I do not need to sign cia

**Comment by maniSbindra** [comment]
resubmitting after changing primary email id

**Comment by azurecla** [comment]
Hi __@maniSbindra__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@maniSbindra__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
