### PR TITLE
Updates ARM template files - Firewall IP Groups

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template used in ARM template [quickstart](https://docs.microsoft.com/azure/firewall/quick-create-ipgroup-template) article.
- Adds quickstart article's author to `docOwner` in _metadata.json_.
- Updates _README.md_ with link to the quickstart article.
- Updates resource `type` to the latest `apiVersion`.
- Fixes order of template's `resources` properties based on best practices guidance.

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by davidsmatlak** [comment]
Build failed in the step to Connect to Azure to create RG.

**Comment by davidsmatlak** [comment]
@bmoore-msft I noticed that the build failed in the step to **Connect to Azure to create RG**. I'll close and reopen the PR to reinitiate the build process.

**Comment by bmoore-msft** [comment]
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by davidsmatlak** [comment]
@bmoore-msft The build ran but **Deploy mainTemplate** failed because there's an extra period in the FQDN on Line 463. I'll pull the change into my local branch and push an update. Thanks.

**Comment by bmoore-msft** [comment]
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by davidsmatlak** [comment]
`targetFqdns` Line 463 changes `'sql1.'` to `'sql1'`

**Pull request merged**
