### PR TITLE
Updates ARM template files - Batch

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template used in ARM template [quickstart](https://docs.microsoft.com/azure/batch/quick-create-template) article.
- Adds quickstart article's author to `docOwner` in _metadata.json_.
- Updates _README.md_ 
  - Link to the quickstart article. 
  - **Deploy to Azure Gov** button because _metadata.json_ doesn't specify environments.
- Updates resource `type` to the latest `apiVersion`.
- Fixes indentation.

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@JnHs - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@JnHs - check this PR for updates that may be needed to documentation that references this sample.

**Review by JnHs — APPROVED** [review]
Thanks! No doc updates appear to be needed.

**Comment by bmoore-msft** [comment]
@JnHs - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
Closing this pull request as **do not merge** because the build validation isn't running when changes are submitted. I'll submit a new pull request.

**Pull request closed without merging**
