### PR TITLE
Added new quickstart template and prereqs for geo redis with vnet

### PR DESCRIPTION
**Pull request by asasine**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog
* Added new quickstart for deploying two virtual network caches and enabling geo-replication
* Added prereq for quickstart to deploy two virtual networks and connecting them with a VPN gateway

### CODE REVIEW

**Comment by asasine** [comment]
This is a recreation of another PR #5462

**Comment by asasine** [comment]
@bmoore-msft the CI build is failing with the same error as before:

>Deployment template validation failed: 'The template resource 'Microsoft.Cache/Redis/ci2d26f962e5f8ddc6/linkedServers/ci28cf8cfbaa82ae29' cannot reference itself

I believe this is because the resource `Microsoft.Cache/Redis/ci2d26f962e5f8ddc6` is also listed in the template and the resource `Microsoft.Cache/Redis/ci2d26f962e5f8ddc6/linkedServers/ci28cf8cfbaa82ae29` depends on `Microsoft.Cache/Redis/ci2d26f962e5f8ddc6`

**Comment by bmoore-msft** [comment]
I'm not familiar with redis, but the resource definition does look odd... can't find any docs on redis either.

**Comment by asasine** [comment]
The schema for child resources is defined [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-templates-resources#child-resources). `linkedServers` is a type of child resource for `Microsoft.Cache/Redis` resources.

**Comment by asasine** [comment]
Hi @bmoore-msft, any update on this?

**Pull request merged**
