### PR TITLE
Change wmfVersion to 5.0

### PR DESCRIPTION
**Pull request by IanMoroney**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
* Changed wmfVersion to 5.0
*
*
*
*

### Description of the change
Fixes [#2008](https://github.com/Azure/azure-quickstart-templates/issues/2008)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@IanMoroney__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by IanMoroney** [comment]
@gbowerman is it possible for you to run the CI build again?
The validation failed to download a file for some reason. I've checked it and the file does exist so re-running the check should solve the issue

**Comment by azurecla** [comment]
Hi __@IanMoroney__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by IanMoroney** [comment]
Closing and re-opening the PR causes the CI to trigger so don't worry.

**Comment by azurecla** [comment]
Hi __@IanMoroney__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Pull request merged**
