### PR TITLE
FIX-BESTPRACTICES: sqlvm-alwayson-cluster-01

### PR DESCRIPTION
**Pull request by badri-spektra**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by badri-spektra** [comment]
##[error]        Property: "sqlLBBEID" must use one of the following expressions for an resourceId property:
##[error]        Property: "sqllbFEConfigID" must use one of the following expressions for an resourceId property:
##[error]        Property: "sqllbProbeID" must use one of the following expressions for an resourceId property:

##[error]        Unreferenced variable: SQL2016-WS2012R2
##[error]        Unreferenced variable: Sunday


Multiple IDs are defined with complex method, each one linked with other

Unreferenced variable can't be removed

**Comment by bmoore-msft** [comment]
@badri-spektra - look at how the Ids are constructed in the variables once resolved - they are using the concat() function and not the resourceId function - those are the changes needed.

**Comment by badri-spektra** [comment]
> @badri-spektra - look at how the Ids are constructed in the variables once resolved - they are using the concat() function and not the resourceId function - those are the changes needed.

@bmoore-msft removed concat in IDs

**Comment by bmoore-msft** [comment]
@badri-spektra - id changes look good... there are still a number of files that need apiVersion updates - those need to be fixed.

We can leave the "unreferenced param/var" violations for now since that will require more of a refactor.

**Comment by badri-spektra** [comment]
> @badri-spektra - id changes look good... there are still a number of files that need apiVersion updates - those need to be fixed.
> 
> We can leave the "unreferenced param/var" violations for now since that will require more of a refactor.

@bmoore-msft updated all api versions

**Pull request merged**
