### PR TITLE
Update azuredeploy.json

### PR DESCRIPTION
**Pull request by maertendMSFT**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by maertendMSFT** [comment]
@bmoore-msft, any ideas why this is failing?

**Comment by jbpaux** [comment]
@maertendMSFT  You need to update the date in metadata.json file

**Comment by bmoore-msft** [comment]
@maertendMSFT - since this sample contains bicep, you need to make the changes to the bicep file, and then submit both bicep and the compiled json to the PR.

**Comment by bmoore-msft** [comment]
Closing abandoned request - please reopen if you can address the feedback.

**Pull request closed without merging**
