### PR TITLE
Fix azure resourceLocations allowedValues validator list

### PR DESCRIPTION
**Pull request by kazumihirose**
Fix azure resourceLocations allowedValues validator list update.
Locations list see below.
"East Asia",
"Southeast Asia",
"Central US",
"East US",
"East US 2",
"West US",
"North Central US",
"South Central US",
"North Europe",
"West Europe",
"Japan West",
"Japan East",
"Brazil South",
"Australia East",
"Australia Southeast",
"Central India",
"West India",
"South India"

Could you marge your repos?
Regards.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kazumihirose__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@kazumihirose__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by singhkay** [comment]
@kazumihirose This PR is too big. GitHub says it can't show the diff because it is so big. Please break it down into smaller chunks and also make sure the resources are available in regions you are adding to allowed values. You can check this using the Get-AzureRmLocation cmdlet.

**Comment by kazumihirose** [comment]
Thank you , I 'll give you commit granularity.

**Pull request closed without merging**
