### PR TITLE
Allow to select 0 data disks dynamically

### PR DESCRIPTION
**Pull request by ashikv**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
* added possibility to select 0 data disks dynamically

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ashikv__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@ashikv Can you sign the CLA?

**Comment by azurecla** [comment]
__@ashikv__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by bmoore-msft** [comment]
Can we update the artifactsLocation to follow BP here: 

https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md#samples-that-contain-extra-artifacts-custom-scripts-nested-templates-etc

**Comment by gatneil** [comment]
We can do the artifactsLocation change in a separate PR; merging

**Pull request merged**
