### PR TITLE
new multi-vm splunk template

### PR DESCRIPTION
**Pull request by liupeirong**

### CODE REVIEW

**Comment by singhkay** [comment]
@rarsan Checked with LCA on our side. They recommend you sign our CLA to allow us to merge this PR? Thanks!

**Comment by sedouard** [comment]
Hey @rarsan thanks for changing your tempalte to follow the CI guidelines. One thing I see that could be causing issues is the `templateLocation` variable. Since it is being defined in `azuredeploy.parameters.json` we can't relink it to your fork since we only relink `raw.githubusercontent.com` links within `azuredeploy.json` itself. That is something we should probably put in the doc.

I see this variable has a default value in the template. Is there any way you can exclude this variable from `azuredeploy.paramters.json`?

**Comment by sedouard** [comment]
+1

**Comment by rarsan** [comment]
Awesome, @sedouard! :tropical_drink:
Special thanks to @liupeirong !

**Pull request closed without merging**
