### PR TITLE
Adding new templates for Budget creation

### PR DESCRIPTION
**Pull request by theelderwand**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@bandersmsft - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Review by mveraluna — APPROVED** [review]

**Review by mveraluna — APPROVED** [review]

**Comment by azure-quickstarts** [comment]
@bandersmsft - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Review by nitinarora-ms — APPROVED** [review]

**Comment by bandersmsft** [comment]
#sign-off

**Comment by azure-quickstarts** [comment]
@bandersmsft - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@bandersmsft - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@bandersmsft - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by bandersmsft** [comment]
@bmoore-msft Please review and merge. ty.

**Review by alex-frankel — APPROVED** [review]
While Brian is OOF, we are going to approve and merge any PRs without his review as long as the CI tests are passing. It is possible he may follow up and request changes once he is back.

**Pull request merged**
