### PR TITLE
Location fix

### PR DESCRIPTION
**Pull request by marcvaneijk**
Changed resource location from parameter to resourceGroup().location.
Deleted location parameter from deployment template and parameter file.

### CODE REVIEW

**Comment by singhkay** [comment]
@marcvaneijk Can you check the error? 

` AssertionError: python-proxy-on-ubuntu/metadata.json - #/itemDisplayName:Failed "maxLength" criteria`

**Comment by marcvaneijk** [comment]
@singhkay fix maxLength < 60 chars

**Comment by singhkay** [comment]
@marcvaneijk Looks like more errors `AssertionError: python-proxy-on-ubuntu/azuredeploy.parameters.json -  Parameter "adminUsername" is missing its value field`

**Comment by marcvaneijk** [comment]
@singhkay replaced empty and static values with placeholders

**Comment by singhkay** [comment]
@marcvaneijk lgtm, merged

**Pull request merged**
