### PR TITLE
Updated labels and ARM deployment template

### PR DESCRIPTION
**Pull request by mikaelweave**
# PR Checklist

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

This is on top of [existing PR here](https://github.com/Azure/azure-quickstart-templates/pull/13597). Main issue is the bicep template was not built into to ARM template.

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@expekesheth - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by mikaelweave** [comment]
@alex-frankel - you approved the [last PR here](https://github.com/Azure/azure-quickstart-templates/pull/13597), could you approve again when you have a chance? I just forgot to run `az bicep build` boooooo.

Thanks so much. @EXPEkesheth FYI.

**Comment by alex-frankel** [comment]
We cannot merge the PR until the CI tests are passing. The deployment of the template is currently failing.

**Comment by mikaelweave** [comment]
Of course @alex-frankel. Thanks so much for getting this on your radar. 😄

**Comment by azure-quickstarts** [comment]
@expekesheth - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by mikaelweave** [comment]
Thank you @alex-frankel for the quick response to fix a problem I created. Appreciate it greatly. 😄

**Pull request merged**
