### PR TITLE
Apim appgw keyvault

### PR DESCRIPTION
**Pull request by chrismason**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [x ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

* Example template connecting API Management and Application Gateway both with Key Vault integration

### CODE REVIEW

**Comment by masonch** [comment]
@bmoore-msft I am trying to get this PR into the quickstarts and it has a dependency on a key vault being deployed with a certificate loaded into it. I am not sure there is a good way to do this via the prereqs templates. Can this be merged without passing that check?

**Comment by bmoore-msft** [comment]
@masonch - check the CI failure, it looks like the problem might be that the:

"apiManagementGatewayCustomDomain"
and
"apiManagementPortalCustomDomain"

Are using the same parameter value - are those mean to be distinct?

**Comment by masonch** [comment]
@bmoore-msft they are distinct URLs however I am using GEN-CUSTOM-FQDN-NAME for the CI process which is producing the same URL for both. Is there a different value I can use to inject unique parameters?

**Comment by bmoore-msft** [comment]
So you need two different certs?

**Comment by bmoore-msft** [comment]
@masonch - ping on that last question...

**Comment by masonch** [comment]
It depends on what certs a customer has when they deploy. If they have a wildcard cert, then a single cert would work for both endpoints, if they want to be specific, they would need 1 cert for each url. I guess the question remains though is is there another way to generate unique names for each of these endpoints since GEN-CUSTOM-FQDN-NAME always seems to generate the same value?

**Comment by bmoore-msft** [comment]
so with how this sample is authored, what are the requirements for certs and/or FQDNs?  The GEN values for cert/fqdn will provide the right parameter values for 1 cert and matching FQDN for that cert.  If we need 2 certs, we can set that up in CI.  If we just need a different FQDN (and cert doesn't matter), just hardcode something in the param file (e.g. contoso.com)

**Comment by bmoore-msft** [comment]
Closing abandoned request - please reopen if you can address the feedback.

**Pull request closed without merging**
