### PR TITLE
Fix allowed Visual Studio versions

### PR DESCRIPTION
**Pull request by MCKLMT**
### Changelog

* Fix allowed Visual Studio versions (Fix issue #2266)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MCKLMT__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mimott). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by MCKLMT** [comment]
@bmoore-msft Could you check this PR please?

**Comment by gatneil** [comment]
is there a particular reason you want bmoore to look at it? The change looks good to me, so if you want I can merge it in :)

**Comment by MCKLMT** [comment]
Thanks @gatneil, please merge it! :)

**Pull request merged**
