### PR TITLE
Minecraft on ubuntu

### PR DESCRIPTION
**Pull request by crpietschmann**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changeling
* Added "virtualMachineSize" parameter
* Added option for Minecraft Server version 1.9.4

### Description of the change
Added a parameter (“virtualMachineSize”) that adds options to pick the
Virtual Machine Size to create in Azure. Also, added an option to the
“minecraftServerVersion” parameter for the latest 1.9.4 Minecraft server version

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@crpietschmann__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by gbowerman** [comment]
Hi Chris, I merged the other PR as it had 1.9.4 as the default value. However the change you made to add machine size in this PR is very useful. Any chance you could update this PR to only add the machine size parameter?

**Comment by gbowerman** [comment]
@crpietschmann I went ahead and merged and will do a test deployment. It occurred to me it should merge correctly with mine, but if not, I'll fix it :-)

**Comment by gbowerman** [comment]
Confirmed successfully created a standard_a2 Minecraft server. 
Next update we should probably delete the a0 size though - I think that will lag.

**Comment by crpietschmann** [comment]
That's why I left the default to A1, but wanted to give some options without requiring to modify the template json.

**Pull request merged**
