### PR TITLE
MOVE: 101-azure-api-for-fhir to quickstarts\microsoft.healthcareapis

### PR DESCRIPTION
**Pull request by akhilthomas011**
…101-azure-api-for-fhir

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@tfitzmac - this appears to be a "Move" that will need a manual doc update

**Comment by azure-quickstarts** [comment]
@StephenWeatherford: IGNORE THIS COMMENT (this is a test): mumian - this appears to be a "Move" that will need a manual doc update

**Comment by azure-quickstarts** [comment]
@StephenWeatherford: IGNORE THIS COMMENT (this is a test): tfitzmac - this appears to be a "Move" that will need a manual doc update

**Comment by mumian** [comment]
https://github.com/MicrosoftDocs/azure-docs-pr/pull/157881

**Pull request closed without merging**
