### PR TITLE
Viya Quickstart for Azure

### PR DESCRIPTION
**Pull request by sasgwb**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

1. Update the Ansible version used by this Quickstart from 2.7.2 to 2.9.14.

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@sasgwb can you check the CI results for some changes that need to be made?

**Comment by sasgwb** [comment]
@bmoore-msft I've fixed the links in the buttons. Now it is flagging an occurrence of "core.windows.net" in the description of _artifactsLocation . Is that a legitimate concern?

**Comment by bmoore-msft** [comment]
Yes, for that you should use

```environment().suffixes.storage```

**Comment by sasgwb** [comment]
@bmoore-msft The builds are all clean now.

**Pull request merged**
