### PR TITLE
v1.1.4: Upgrade Azure CPI version to v8.

### PR DESCRIPTION
**Pull request by AbelHu**
### Changelog

# v1.2.0 (2016-03-28)
- Add a subnet for Diego
- Create network security groups for all subnets
- Upgrade versions
  - Upgrade Azure CPI version to v8. Please see new features in https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AbelHu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (abelch). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@AbelHu Running this manually I'm seeing this error. Can you take a look?

```
error:   Deployment provisioning state was not successful
error:   The resource operation completed with terminal provisioning state 'Failed'.
error:   VM has reported a failure when processing extension 'initdevbox'. Error message: "Script returned an error.
---stdout---
Generating public/private rsa key pair.
Your identification has been saved in bosh.
Your public key has been saved in bosh.pub.
The key fingerprint is:<removed>
The key's randomart image is:
<removed>

---errout---
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "setup_env.py", line 190, in <module>
    main()
  File "setup_env.py", line 184, in main
    bosh_director_ip = render_bosh_manifest(settings)
  File "setup_env.py", line 109, in render_bosh_manifest
    prepare_network_security_group_for_bosh(settings, bosh_director_ip)
  File "setup_env.py", line 72, in prepare_network_security_group_for_bosh
    prepare_network_security_group(settings, static_ip, settings["NSG_NAME_FOR_BOSH"], rules)
  File "setup_env.py", line 35, in prepare_network_security_group
    tenant = settings["TENANT_ID"]
  File "/usr/local/lib/python2.7/dist-packages/msrestazure/azure_active_directory.py", line 328, in __init__
    self.set_token()
  File "/usr/local/lib/python2.7/dist-packages/msrestazure/azure_active_directory.py", line 359, in set_token
    raise_with_traceback(AuthenticationError, "", err)
  File "/usr/local/lib/python2.7/dist-packages/msrest/exceptions.py", line 50, in raise_with_traceback
    raise error
msrest.exceptions.AuthenticationError: , InvalidClientIdError: (invalid_request) AADSTS90002: No service namespace named 'cidf661104a52e9272ci094d3d5c8817d4c3' was found in the data store.

```

**Comment by AbelHu** [comment]
@singhkay It seems like that you do not provide a valid service principal. 
I cannot find any useful information for the CI failure. I have tested this PR successfully in my branch [test](https://github.com/AbelHu/azure-quickstart-templates/tree/test/bosh-setup) with changing the link address.

**Comment by singhkay** [comment]
@AbelHu  Ah yes! I missed the AD properties that are needed. In that case will merge without CI

**Pull request merged**
