### PR TITLE
Adding batch account with keyvault pfx password

### PR DESCRIPTION
**Pull request by manishshar**
**Adding new arm template which helps user to add certificates from keyvault in azure batch account pools.**

### CODE REVIEW

**Comment by manishshar** [comment]
closing pull request

**Comment by bmoore-msft** [comment]
@manishshar - check the CI failure, you'll need to use GEN parameter values to pull the cert from the CI vault (more in the contribution guide)

**Comment by manishshar** [comment]
@bmoore-msft : Thanks for GEN Suggestion. It worked. but I'm not very sure that how it can be use with  existing keyvault secret for content type**application/x-pkcs12 of pfx**, **Password** and **Thumbprint**

**Comment by manishshar** [comment]
@bmoore-msft : from contribution guide, I'm able to find **GEN-KEYVAULT-SSL-SECRET-NAME** but I dont see **application/x-pkcs12** of pfx (base64string) and password for the same. I tried to create keyvault but I'm **not able to create secret** in keyvault. I suppose some permission issue. Any workaround for this scenario?

**Comment by manishshar** [comment]
Thanks @bmoore-msft. It worked.

**Pull request closed without merging**
