### PR TITLE
Updated azure-chef-extension's version

### PR DESCRIPTION
**Pull request by NimishaS**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@NimishaS__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by NimishaS** [comment]
This should wait for merge till the extension 1210.12 is not stable.

**Comment by singhkay** [comment]
@NimishaS Any ETAs for that?

**Comment by NimishaS** [comment]
@singhkay , this can be merged now.

**Comment by singhkay** [comment]
@NimishaS merged, thanks!

**Pull request merged**
