### PR TITLE
fix import command

### PR DESCRIPTION
**Pull request by mgreenegit**
I copied it to a new line but left it on the old line

### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

*
*
*

### CODE REVIEW

**Comment by mgreenegit** [comment]
@marcvaneijk @bmoore-msft any idea why this build is hitting a download error?

**Comment by bmoore-msft** [comment]
This needs to be a secureString parameter type:

https://github.com/Azure/azure-quickstart-templates/blob/398a14b6c4d92a04f670984e0070e4dbc675484c/101-automation-configuration/azuredeploy.json#L73

**Comment by mgreenegit** [comment]
@bmoore-msft thanks.  This is closer but it looks like one of the properties is not getting passed to the deployment script.  Anything clear to you?

**Comment by bmoore-msft** [comment]
@mgreenegit - update metadata.json in your branch, that's a new test that's failing, then I can take a look.

**Comment by mgreenegit** [comment]
@bmoore-msft I am stuck.  I can't repro this locally.

**Comment by bmoore-msft** [comment]
Use the script in the root of the repo (that's what CI uses) - I can repro:

.\Deploy-AzTemplate.ps1 -ArtifactStagingDirectory .\101-automation-configuration\ -Location eastus

Be sure to use a valid set of parameters - also might be helpful to try a green/new subscription.

It appears to be something in the DSC config, but I can't figure out what it's complaining about - whether it's an arg on the resource (in the template) or something missing from the script.

**Comment by mgreenegit** [comment]
@bmoore-msft Confirmed from my workstation that the build script is not producing a username/password from parameter strings "GEN-UNIQUE" and "GEN-PASSWORD".  Did the expected string values change?  cc @bobbytreed since he is working on an update to this template.
image

**Comment by bmoore-msft** [comment]
remember you need to supply a valid set of params - the GEN* values only work in the CI/CD pipeline.  If you look at the logs, you can see in the step prior to deployment which parameters where generated (there is a username, 2 passwords and location). I can reproduce the failure with the same or other parameters.

Also, I have a failed deployment in my sub if you want to have a look: https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/ceaedbb7-b827-4195-b55f-de9b6732010b/resourceGroups/101-automation-configuration/overview

**Comment by mgreenegit** [comment]
@bmoore-msft how are you passing secure strings?  That’s the only difference I can see between this script and directly using the Az deploy cmdlets.

**Comment by bmoore-msft** [comment]
The only secureString passed in is the sasToken, that's working fine at least part of the way because the nested template secured by it is invoked.  You can see how that's done in the PS1.

The passwords are pulled from the file.

**Comment by bmoore-msft** [comment]
Closing abandoned request - please reopen if you can address the feedback.

**Pull request closed without merging**
