### PR TITLE
Added CI to few more DSC using templates

### PR DESCRIPTION
**Pull request by singhkay**

### CODE REVIEW

**Comment by singhkay** [comment]
@sedouard Might need to go over 120 minutes. 

Tested the third template works locally. merging

**Comment by sedouard** [comment]
Not really possible to extended besides [begging the folks at Travis](https://github.com/travis-ci/travis-ci/issues/5346)

**Comment by sedouard** [comment]
In the meantime it may make sense to just put a `.ci_skip` file in that Sharepoint template as the other two templates took about 25 minutes to deploy compared to **over 2 hours** for sharepoint (geez that is, so, so long)

**Comment by singhkay** [comment]
@sedouard Ya that one is reaaaallly long! Let's see if we continue to see more templates like this

**Pull request merged**
