### PR TITLE
fix password reference in outputs, portainer version bump

### PR DESCRIPTION
**Pull request by tfenster**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Fixed the password reference in the outputs because `[steps('vmParameters').adminPassword]` returns an object while I need only the password, which is returned by `[steps('vmParameters').adminPassword.password]`
* Bump portainer version from 2.0.0 to 2.1.1

### CODE REVIEW

**Comment by tfenster** [comment]
@bmoore-msft This fails in a weird place for the public cloud? Is this a fluke or an actual problem, and can I do anything about it?

**Comment by bmoore-msft** [comment]
We'll see - I ran a new build...

**Comment by tfenster** [comment]
@bmoore-msft Looks better :)

**Comment by bmoore-msft** [comment]
Indeed it does...

**Pull request merged**
