### PR TITLE
MOVE: 101-sig-create to quickstarts\microsoft.compute

### PR DESCRIPTION
**Pull request by akhilthomas011**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by olayemio** [comment]
I'm the manager for the Shared Image Gallery service. Can I understand why the 101-sig-create scenario was moved? It's causing customer issues since they cannot find the templates.

**Comment by bmoore-msft** [comment]
@olayemio - check the readme in the root of the repo, the TLDR is we hit an api limit in github and can't use a flat structure anymore.  If you have doc link @tfitzmac may be able to help you with that...

**Comment by olayemio** [comment]
@tfitzmac I would like to get your help in updating the TemplateUri in the following links:
- https://azure.microsoft.com/en-us/resources/templates/101-sig-create/
- https://azure.microsoft.com/en-us/resources/templates/101-sig-image-definition-create/

**Comment by tfitzmac** [comment]
@olayemio - those links are handled by the azure.com team. I am not familiar with how they are updating those pages. If there are links within docs.microsoft.com, I can help with fixing those.

**Comment by bmoore-msft** [comment]
@olayemio - you need to reach out to ACOM for those links

**Comment by olayemio** [comment]
@bmoore-msft do you know which specific ACOM team. Also, for completeness, can we move `101-sig-image-version-create` to the same subfolders as the other two scenarios

**Comment by bmoore-msft** [comment]
shoot me an email - all the samples will move eventually, but yes all the sig samples will be in the same spot.

**Pull request merged**
