### PR TITLE
Update VMs to Mariner OS to avoid security vulnerabilities (9)

### PR DESCRIPTION
**Pull request by BhumikaMatharu**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Updating the VMs from Ubuntu OS to Mariner OS
* Added VM auto-patching and AzSecPack auto-configuration properties on VMs

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Review by alex-frankel — CHANGES_REQUESTED** [review]
The bicep file is the source of truth for this quickstart, so please update the bicep file only. The ARM Template will be regenerated by our CI on your behalf.

**Comment by azure-quickstarts** [comment]
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Pull request merged**
