### PR TITLE
update api-version, add bicep support

### PR DESCRIPTION
**Pull request by markjbrown**
## Changelog

* update api-version
* add bicep support

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@markjbrown - for the bicep samples, we need to update azuredeploy.json to be the one generated by bicep - IOW replace the old json with the bicep json.  That way we know the samples are the same.  We're going to automate that check once @StephenWeatherford gets back from vacation ;)

**Comment by markjbrown** [comment]
@bmoore-msft So do you need me to do build the azuredeploy.json for each of these PR's or is this being built in your test scripts?

**Comment by StephenWeatherford** [comment]
@markjbrown Yes please if you can.  I just restarted the validation against the new bicep pipeline (it should have been running before but wasn't), it should show the error now and what needs to be done.  Let us know if you run into problems or have questions, thanks!

**Comment by markjbrown** [comment]
@StephenWeatherford @bmoore-msft 

Ack. Will run build on update all the arm templates and commit into all the PR's.

Thanks.

**Pull request closed without merging**
