### PR TITLE
Make SP 3 VM template more robust and faster

### PR DESCRIPTION
**Pull request by simongdavies**
This PR contains a set of changes that improve the reliability of the SP 3 VM template and also reduce the amount of time taken to deploy the solution

### CODE REVIEW

**Comment by simongdavies** [comment]
@singhkay do you know why the test deploy failed? I couldn't figure it out.

**Comment by singhkay** [comment]
@simongdavies Not sure, it didn't time out this time. Can you take the rendered templates and parameters and try to deploy locally?

**Comment by sedouard** [comment]
(since this pr was opened before the formatting fix, it won't get the pretty log output. I suppose until the PR is reopened)

**Comment by simongdavies** [comment]
@sedouard @singhkay  the formatted print output is much better !! It still didn't tell me why it had failed though, turns out that there is a parameter missing. This parameter is the baseURL for all the artefacts for this template, it defaults to the master branch of the repo, however this PR makes some changes to those artefacts so when the template runs it picks up the current version not the new version.

One solution would be to point at my fork in the parameters file and then once the change has been merged I will remove the parameter and do another PR?

**Comment by sedouard** [comment]
see https://github.com/Azure/azure-quickstart-templates#relinking

**Comment by singhkay** [comment]
job exceeded Travis timeout. Deployed manually, merging.

**Pull request merged**
