### PR TITLE
Hdi spark linux template update

### PR DESCRIPTION
**Pull request by guyhay**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Review by guyhay — COMMENTED** [review]
file included in error.  Removing

**Comment by bmoore-msft** [comment]
@hrasheed-msft - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by bmoore-msft** [comment]
@hrasheed-msft - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by hrasheed-msft** [comment]
> @hrasheed-msft Hassan Rasheed FTE - check this PR for updates that may be needed to documentation that references this sample. [this is an automated message]

@bmoore-msft I have transitioned to a different team. I think @JasonWHowell would be better to provide approval for this. I have submitted a few PRs to update the docOwner for these templates.

**Comment by guyhay** [comment]
reverting because of multiple files from different templates

**Pull request closed without merging**
