### PR TITLE
change the title to lower case and add some feature

### PR DESCRIPTION
**Pull request by xiaoyingLJ**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

*
*
*

### CODE REVIEW

**Comment by xiaoyingLJ** [comment]
@bmoore-msft 
hi, Brian could you help take a look at this PR?

**Comment by bmoore-msft** [comment]
Can you check the merge conflicts?

**Comment by xiaoyingLJ** [comment]
Resolved.

Thanks
Xiaoying

**Comment by xiaoyingLJ** [comment]
@bmoore-msft ，I have resolved the conflicts, could you help merge the PR?

**Comment by bmoore-msft** [comment]
the file rename causes the files needed for deployment not to be found - we need to get this updated to get a passing CI

**Comment by xiaoyingLJ** [comment]
Hi, Brian

Sorry for that I am not quite clear about below mail, do you mean I need to get a passing CI? But my template depends on some existing resources, and when I try to use prereqs, it always throw an exception “Resource group 'GET-PREREQ-resourceGroupName' could not be found.” I cannot get a passing CI.

Thanks
XIAOYING

**Pull request closed without merging**
