### PR TITLE
Initial commit of Shadow Node @ Azure

### PR DESCRIPTION
**Pull request by dasource**
Add Shadow Blockchain to Azure .. Thanks

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dasource__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@dasource__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by dasource** [comment]
Not sure why adding a description caused the checks to fail? Thanks

**Comment by singhkay** [comment]
@dasource Looks like a transient error with the DNS of the server, I've kicked off deployment again

**Comment by dasource** [comment]
Thanks :) and keep up the great work your doing here.

**Comment by singhkay** [comment]
@dasource Thanks :) lgtm, merged

**Comment by HyperSpaceChain** [comment]
for more information, https://shadowproject.io/

**Comment by HyperSpaceChain** [comment]
https://shadowproject.io/

**Comment by HyperSpaceChain** [comment]
Shadow [BitcoinTalk thread](https://bitcointalk.org/index.php?topic=745352)

**Pull request merged**
