### PR TITLE
Changed default values to match new diagrams and removed public IP address from virtual machine and simplified nat gateway setup

### PR DESCRIPTION
**Pull request by asudbring**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@asudbring - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by alex-frankel** [comment]
Oh, that is because you only edited the JSON file when there is a bicep file available. You need to make your changes to the bicep file and we will autogenerate the JSON file ourselves.

**Comment by alex-frankel** [comment]
The contribution guide covers this:
https://github.com/Azure/azure-quickstart-templates/tree/master/1-CONTRIBUTION-GUIDE

But yes, your understanding is correct.

**Comment by asudbring** [comment]
@alex-frankel 
Awesome!  Thank you for your help with this.  I will filter this down to my team.
Thanks again!
allen

**Pull request merged**
