### PR TITLE
FIX-FAILED-BESTPRACTICES: hdinsight-linux-ssh-publickey-metastore-vnet

### PR DESCRIPTION
**Pull request by badri-spektra**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by badri-spektra** [comment]
Azure error
##[error]        Output name suggests secret: existingHiveMetastorePassword
##[error]        Output contains securestring parameter: existingHiveMetastorePassword

SQL server password in output is removed and added pre-known password from tests param, AZUREAD-AKS-APPID-SECRET. but now the template is failing with with invalid password message "Status Message: DeploymentDocument 'HiveConfigurationValidator' failed the validation. Error: 'Invalid password specified for Hive Sql azure server. Password cannot have any of the following characters -{}'[]"\\' (Code:BadRequest)"

**Comment by bmoore-msft** [comment]
you can use the password stored in keyvault: https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.datafactory/data-factory-v2-blob-to-mysql-copy/azuredeploy.parameters.json#L27

**Comment by badri-spektra** [comment]
@bmoore-msft after updating the password to "GEN-KEYVAULT-PASSWORD-REFERENCE" main template is getting failed with below error

The password must be at least 8 characters in length and must contain at least one digit, one non-alphanumeric character, one upper case letter and one lower case letter. Also, the password should not contain 3 consecutive letters from the username (Code:BadRequest)

Error link
https://dev.azure.com/azurequickstarts/b191bd7a-37bb-47b0-870c-3f1270a79b3d/_apis/build/builds/77338/logs/36

**Comment by badri-spektra** [comment]
> you can use the password stored in keyvault: https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.datafactory/data-factory-v2-blob-to-mysql-copy/azuredeploy.parameters.json#L27

@bmoore-msft: updated with keyvault password, now all Best practice issues cleared

**Pull request merged**
