### PR TITLE
Added visualize button to datastax-enterprise

### PR DESCRIPTION
**Pull request by ytechie**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ytechie__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jayoung). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@ytechie The visualization just shows deployments linking to each other. Is that the intended addition?

**Comment by ytechie** [comment]
Yes, that's about all that can be visualized in that template for now. I was using this as an example to show someone. I'm trying to find someone to go through and test/add buttons for all of them.

**Comment by singhkay** [comment]
@ytechie One thing that would be really cool despite the visualization displaying all deployments if you could read the name from the template and name these deployment icons so it's clear what's kicking off what.

**Comment by ytechie** [comment]
I'll take a look at that.

**Comment by ytechie** [comment]
Done! I also updated the icons. The text overflows a bit in one of them, but doesn't look terrible.

**Comment by singhkay** [comment]
@ytechie Looks good! Merged 

Another request unrelated to this is can you show VNETs and Subnets as rectangles that contain other resources such as NICs, VMs ?

**Pull request merged**
