### PR TITLE
BlackCoin [BLK] Template

### PR DESCRIPTION
**Pull request by tomcio2001**
### Changelog
*Added BlackCoin Template for Ubuntu

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@tomcio2001__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by rahulchand** [comment]
user is rpc/1234 

can you change them to parameters as radium has done it?
https://github.com/Azure/azure-quickstart-templates/tree/master/radium-blockchain-ubuntu#template-parameters

https://github.com/Azure/azure-quickstart-templates/blob/master/radium-blockchain-ubuntu/build_radium.sh#L26

**Comment by tomcio2001** [comment]
Ok, I will change them and remove the remains from INFX template.

**Comment by blood2** [comment]
why running the daemon as user root ?
i see this problem in Radium's template as well.
i would run it as a different user... maybe in a chrooted environment

**Comment by tomcio2001** [comment]
Ok, I changed all rpc config to parameters.

**Comment by allwaytogo** [comment]
Will this task continue?

**Comment by sidhujag** [comment]
your welcome

**Comment by tomcio2001** [comment]
Thank you man.

**Comment by sidhujag** [comment]
@tomcio2001 have you contacted Mr. Gray and finished off the application to get BLK into azure?

**Comment by tomcio2001** [comment]
Very sorry for late reply. Where Can I contact him?

**Comment by sidhujag** [comment]
marleyg@microsoft.com

**Comment by gatneil** [comment]
Sorry for the late reply; is this something we still want to merge in?

**Comment by sidhujag** [comment]
You can im not available to work on it

**Comment by gatneil** [comment]
Thanks!

**Comment by gatneil** [comment]
Merge no longer desired; closing

**Pull request closed without merging**
