### PR TITLE
Chefautomatep2platest

### PR DESCRIPTION
**Pull request by pradeepts**
updated the chef-automate p2p with the following changes:
updated chefserver.sh file

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pradeepts__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by gatneil** [comment]
Looks like there are merge conflicts; can these be addressed?

**Comment by gatneil** [comment]
(also, please sign the CLA; otherwise I can't merge the PR :))

**Comment by pradeepts** [comment]
synced fork with upstream

**Pull request closed without merging**
