### PR TITLE
Update Zookeeper Template to 3.4.8 - fix broken template

### PR DESCRIPTION
**Pull request by ggalow**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
* Update Zookeeper binaries from 3.4.6 to 3.4.8
* Fix broken Zookeeper binary path

### Description of the change
Latest Stable Zookeeper is 3.4.8. 3.4.6 was no longer in the path meaning the template would always fail.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ggalow__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
lgtm, merged

**Comment by ggalow** [comment]
Is parameters.json supposed to contain default values? For this template seems like most of them are in the azuredeploy.json? My guess is the standards have been updated since this has been.

**Comment by singhkay** [comment]
@ggalow yeah, this was one of the first templates I did :) Look at how to use placeholder parameters for passing the CI https://github.com/Azure/azure-quickstart-templates/tree/master/1-CONTRIBUTION-GUIDE#travis-ci

**Pull request merged**
