### PR TITLE
extended zones arm template

### PR DESCRIPTION
**Pull request by halkazwini**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by jasonurban1** [comment]
I do not seem to have permission to approve as a reviewer.  There is a pipeline build failure above.  If you fix that you can add me as a reviewer and I will approve.

**Comment by halkazwini** [comment]
> I do not seem to have permission to approve as a reviewer. There is a pipeline build failure above. If you fix that you can add me as a reviewer and I will approve.

@jasonurban1 my main issue is fixing the build failure.

**Comment by jasonurban1** [comment]
@alex-frankel  would you be able to merge this PR?

**Comment by halkazwini** [comment]
#sign-off

**Pull request merged**
