### PR TITLE
Service fabric template updates

### PR DESCRIPTION
**Pull request by peterpogorski**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog
Updated the Service Fabric templates to use the latest API version for all of the resources.
*
*
*

### CODE REVIEW

**Comment by peterpogorski** [comment]
@bmoore-msft What changes would I need to make to the Parameter values in order to get the tests to pass?

**Comment by bmoore-msft** [comment]
Try: https://github.com/Azure/azure-quickstart-templates/blob/master/5-VM-Ubuntu-1-NodeTypes-Secure/azuredeploy.parameters.json

**Comment by peterpogorski** [comment]
@bmoore-msft I tried updating with the new GEN values and I am still unable to make the tests pass. What other changes would you recommend?

**Comment by bmoore-msft** [comment]
I tihnk we need to break this into 2 PRs one for each sample - I'm not seeing where a deployment is even being attempted for the second sample.

**Pull request closed without merging**
