### PR TITLE
Add v1LegacyMode to e2e secure pl workspace for  sdkv1

### PR DESCRIPTION
**Pull request by mingweihe**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Add v1LegacyMode to e2e secure pl workspace for  sdkv1

### CODE REVIEW

**Comment by mingweihe** [comment]
Hi @bmoore-msft , would you like to review this PR and the other one, https://github.com/Azure/azure-quickstart-templates/pull/12502
Both of them have passed all the checks.

**Comment by mingweihe** [comment]
Hi @bmoore-msft , would you like to review this PR and the other one, https://github.com/Azure/azure-quickstart-templates/pull/12502
Both of them have passed all the checks.

**Comment by bmoore-msft** [comment]
Can you check the pipeline results for the BP violations?

**Comment by mingweihe** [comment]
> Can you check the pipeline results for the BP violations?

learned, fixed, thanks.

**Comment by alex-frankel** [comment]
Merging since all tests are passing, but @bmoore-msft is OOF. He may take another look at this and request changes.

**Pull request merged**
