### PR TITLE
Updated install script to set the owner of the webapps folder to the admin user.

### PR DESCRIPTION
**Pull request by alvadb**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alvadb__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@alvadb To allow us to review and merge, can you sign the CLA? Also please add metadata and description properties to the parameters. Thanks!

**Comment by azurecla** [comment]
__@alvadb__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by singhkay** [comment]
@alvadb Any update on this?

**Comment by singhkay** [comment]
@alvadb As the above error indicates, you need to add a metadata object and description property to the template

**Comment by marleyg** [comment]
Hey, can you send me details about Expanse so I can include it in the next BaaS update?

**Comment by singhkay** [comment]
@alvadb Closing as we haven't seen an update on this for a while

**Pull request closed without merging**
