### PR TITLE
Basic RHEL template

### PR DESCRIPTION
**Pull request by BorisB2015**
Add RHEL template

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@BorisB2015__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (borisb). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by BorisB2015** [comment]
@OakerMin : good catch on 6.7 version! Thanks!

**Comment by BorisB2015** [comment]
Travis CI - flaky? I cannot report the error and log is useless

**Comment by singhkay** [comment]
lgtm ,merged

**Pull request merged**
