### PR TITLE
Update mobilenetwork-create-new-site with new ASE install procedure for AKS-HCI only

### PR DESCRIPTION
**Pull request by o-wb**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by o-wb** [comment]
@bmoore-msft These merge conflicts have now been resolved.

**Comment by bmoore-msft** [comment]
@andrew-lee-metaswitch - have your comments been addressed?

**Comment by andrew-lee-metaswitch** [comment]
> @andrew-lee-metaswitch - have your comments been addressed?

No - this is still a WIP.

**Comment by andrew-lee-metaswitch** [comment]
@o-wb -  can you please close this MR? I've raised https://github.com/Azure/azure-quickstart-templates/pull/12910 instead.

**Pull request closed without merging**
