### PR TITLE
Adding Bicep template for App Configuration Store with Feature Flag

### PR DESCRIPTION
**Pull request by willvelida**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@ZhijunZhao - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@ZhijunZhao - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by willvelida** [comment]
Hey @bmoore-msft, I've check the build logs and the best practices label is being applied even though in my ARM template, I'm using a location parameter that has a default value of ```resourceGroup.location()```. Should the label be applied in this case, or do I need to remove the default value for the best practices label to be removed? 

This is the case with other pull requests that I've raised, so I'm wondering if I have missed something on my side so I can make the changes in those PRs as well :)

**Comment by willvelida** [comment]
#pr-ready

**Comment by azure-quickstarts** [comment]
@ZhijunZhao - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Pull request closed without merging**
