### PR TITLE
Updated to use Managed disks

### PR DESCRIPTION
**Pull request by varunbeesu**
Removed vhd uri to use Managed Disks
updated apivesrion for VM
updated parameter values

### CODE REVIEW

**Comment by bmoore-msft** [comment]
Also, can you go through the other open PRs and check for the unused storageAccounts (I won't comment on each one)

**Comment by varunbeesu** [comment]
Thanks Brian, I will update it accordingly.

**Comment by varunbeesu** [comment]
Updated

**Comment by varunbeesu** [comment]
Removed unused storage

**Pull request merged**
