### PR TITLE
Adding template for deploying TFS against an existing SQL instance

### PR DESCRIPTION
**Pull request by chrisamert**
Creates a new TFS Deployment in an existing domain, configured against an existing SQL instance

### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### CODE REVIEW

**Comment by chrisamert** [comment]
Looks like raw.githubusercontent.com links in prereq.azuredeploy.json files aren't being rewritten to reference the fork.  Is that expected?  If so, is there another way to enable the prereq template to reference nested templates?

**Comment by bmoore-msft** [comment]
go ahead and point to your fork for the initial commit

**Comment by bmoore-msft** [comment]
can you point the links back to Azure/master now?

**Comment by chrisamert** [comment]
Yup, PR for that here: https://github.com/Azure/azure-quickstart-templates/pull/4203

**Pull request merged**
