### PR TITLE
Initial commit for AFS based clusters

### PR DESCRIPTION
**Pull request by hglkrijger**
- initial commit for afs-utils script, for creating and mounting shares
- fix es/marvel/kibana version issues by passing parameters to the kibana install script
- add in AFS options to template and pipe through switches to scripts
- update resources to pass storage account key to install script

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@hglkrijger__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (hkrijger). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@hglkrijger__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (hkrijger). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@hglkrijger Looks at that passing green! 
@trentmswanson Can you review the changes?

**Comment by trentmswanson** [comment]
Thanks @singhkay the changes look good.

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
