### PR TITLE
MOVE: 101-managed-mariadb-with-vnet to quickstarts\microsoft.dbformariadb

### PR DESCRIPTION
**Pull request by akhilthomas011**
…iadb\managed-mariadb-with-vnet

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@ajlam - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by azure-quickstarts** [comment]
@tfitzmac / @mumian- this appears to be a "Move" that will need a manual doc update

**Comment by tfitzmac** [comment]
@mumian - are you getting notified for these changes? It looks like there is an extra dash in the message that might be causing a problem.

**Comment by tfitzmac** [comment]
@mumian - I'll take this one.

**Comment by mumian** [comment]
@tfitzmac - I didn't get this one.
@bmoore-msft - can you fix it?

**Comment by bmoore-msft** [comment]
@mumian - not 100% certain why it wasn't working, but I made a  change

@tfitzmac - please watch the next one to see if the new @ is working...  (there should be 2 distinct comments now)

**Comment by bmoore-msft** [comment]
@mumian & @tfitzmac 

Actually - I'll just re-run this build and we can see...

**Comment by mumian** [comment]
@bmoore-msft - I have received the notification.  Thanks.

**Comment by bmoore-msft** [comment]
The automated one hasn't printed yet - give it 5 mins or so, you should see one that looks exactly like Tom's

**Comment by azure-quickstarts** [comment]
@ajlam - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by azure-quickstarts** [comment]
@mumian - this appears to be a "Move" that will need a manual doc update

**Comment by azure-quickstarts** [comment]
@tfitzmac - this appears to be a "Move" that will need a manual doc update

**Comment by bmoore-msft** [comment]
@mumian - looks like you should have gotten this one... (above)

**Comment by tfitzmac** [comment]
https://github.com/MicrosoftDocs/azure-docs-pr/pull/156151

**Pull request merged**
