### PR TITLE
Updates ARM template files - Event Grid

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template used in ARM template [quickstart](https://docs.microsoft.com/azure/event-grid/blob-event-quickstart-template) article.
- Adds quickstart article's author to `docOwner` in _metadata.json_.
- Updates _README.md_ with link to the quickstart article and fixes broken links for **Deploy to Azure** and **Visualize** buttons.
- Updates resource `type` to the latest `apiVersion`.
- Fixes order of template's `resources` properties based on best practices guidance.
- Fixes indentation.
- To fix a build error, removes empty tag from `azuredeploy.json` template: `"tags": {},`

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@spelluru - check this PR for updates that may be needed to documentation that references this sample.

**Review by spelluru — COMMENTED** [review]
Thanks, Brian. I don't think I will need to update the quickstart, but I will check as soon as your PR is merged and the updated template goes live.

**Comment by bmoore-msft** [comment]
@spelluru - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@spelluru - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@spelluru - check this PR for updates that may be needed to documentation that references this sample.

**Pull request merged**
