### PR TITLE
MOVE: 101-dtl-create-lab-windows-vm to quickstarts\microsoft.devtestlab

### PR DESCRIPTION
**Pull request by akhilthomas011**
…ab\dtl-create-lab-windows-vm

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@Juliako - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by azure-quickstarts** [comment]
@tfitzmac - this appears to be a "Move" that will need a manual doc update

**Comment by azure-quickstarts** [comment]
@Juliako - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by azure-quickstarts** [comment]
@tfitzmac / @mumian- this appears to be a "Move" that will need a manual doc update

**Comment by tfitzmac** [comment]
@mumian @juliako - this one is already submitted. https://github.com/MicrosoftDocs/azure-docs-pr/pull/155971

**Pull request merged**
