### PR TITLE
Azure Backup for SQL Server in Azure Virtual Machines

### PR DESCRIPTION
**Pull request by nilaydshah**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

* Azure Backup for SQL Server in Azure Virtual Machines

### CODE REVIEW

**Comment by nilaydshah** [comment]
@bmoore-msft  Can you please review this PR?

**Comment by nilaydshah** [comment]
@bmoore-msft CI for the main new template passed already, I did some minor fixes in readme in few other recovery services templates which caused their CI build failure. Can we ignore them and merge this PR (if all looks fine)?

**Comment by nilaydshah** [comment]
Skipped CI for one of the existing template which relies on existing resources. Latest CI build is green now.

**Comment by bmoore-msft** [comment]
Please separate these into 1 PR per sample.  Also, if you have existing resource requirements, see the contribution guidelines for how to handle prereqs.

**Pull request closed without merging**
