### PR TITLE
Update the elasticsearch template to support Centos

### PR DESCRIPTION
**Pull request by lizzha**
Update the elasticsearch template to support Centos

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lizzha__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (lizzha). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by lizzha** [comment]
Leave a comment

**Comment by azurecla** [comment]
Hi __@lizzha__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (lizzha). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by lizzha** [comment]
@singhkay, I cannot figure out why the travis CI build failed, could you please shed some lights?

**Comment by singhkay** [comment]
@lizzha CI server was having some troubles. lgtm, merged

**Pull request merged**
