### PR TITLE
update content version and fix deployment link

### PR DESCRIPTION
**Pull request by netwmr01**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@netwmr01__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@netwmr01 Look at that! CI deployed succesfully this time :+1:  Can you also take a look at this issue? #1152 ?

**Comment by netwmr01** [comment]
correct, this version is going to address #1152

**Comment by netwmr01** [comment]
@singhkay Can I get a merge for this one, thanks?

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
