### PR TITLE
Updates ARM template files - Firewall Manager

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template used in ARM template [quickstart](https://docs.microsoft.com/en-us/azure/firewall-manager/quick-secure-virtual-hub) article.
- Adds quickstart article's author to `docOwner` in _metadata.json_.
- Updates _README.md_ with link to the quickstart article.
- Updates `azuredeploy.parameters.json` with latest schema version: **2019-04-01**.
- Updates resource `type` to the latest `apiVersion`.
- Fixes indentation.

### CODE REVIEW

**Comment by davidsmatlak** [comment]
Build failed in the step to Connect to Azure to create RG.

**Comment by bmoore-msft** [comment]
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by bmoore-msft** [comment]
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by davidsmatlak** [comment]
Build failed during **Deploy mainTemplate** because of several authorization errors `(Code:AuthorizationFailed)`.

**Comment by bmoore-msft** [comment]
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by bmoore-msft** [comment]
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by bmoore-msft** [comment]
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by davidsmatlak** [comment]
**Deploy mainTemplate** was successful. To fix build failures, reverted the `apiVersion`:
- `Microsoft.Network/virtualWans` to original `2019-08-01`
  - Build error: AllowVnetToVnetTraffic flag in VirtualWan is not supported
- `Microsoft.Network/virtualHubs` to original `2020-04-01`
  - Build error: Cannot specify VirtualNetworkConnections while creating/updating VirtualHub in API version 2020-05-01 and beyond
- `Microsoft.Network/virtualHubs/routeTables` changed to `2020-04-01` rather than latest version for consistency with `virtualHubs`.

**Pull request merged**
