### PR TITLE
Updates ARM template files - HDInsight Interactive Query

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template used in ARM template [quickstart](https://docs.microsoft.com/azure/hdinsight/interactive-query/quickstart-resource-manager-template) article.
- Adds quickstart article's author to `docOwner` in _metadata.json_.
- Updates _README.md_ with link to the quickstart article.
- Fixes link's title and redirected link in _README.md_.
- Updates resource `type` to the latest `apiVersion`.
- Fixes template's `resources` property order based on best practices guidance.
- Fixes indentation.

### CODE REVIEW

**Comment by davidsmatlak** [comment]
@hrasheed-msft - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
@bmoore-msft Why didn't the automated validation checks run on this pull request?

**Comment by bmoore-msft** [comment]
@hrasheed-msft - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
@bmoore-msft the validation **succeeded with issues**. I'll review the logs tomorrow and update the pull request.

**Pull request merged**
