### PR TITLE
Updatedsharepointserverfarm

### PR DESCRIPTION
**Pull request by arroyc**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
brought back dsc and dscv2 folders 
### Description of the change
as amp sharepoint templates refer the /dsc and dscv path. Till amp guys fix their templates we can't really change it here. fix for SharePoint HA farm - deployment template parse failed.  #2326 too

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@arroyc__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (arroyc). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by bmoore-msft** [comment]
Arjun - don't revert all the changes (or rather any of them) in the templates - leave the templates as you had them (working :)).  Just put a copy of DSCv2 back (it's cases sensitive so make sure I got it right) so that the AMP deployments pass.  Leave the sample so it can still be deployed via script from the root of the repo.

**Comment by arroyc** [comment]
@bmoore-msft  .. this issue is little confusing ... some of the sharepoint template in amp use dsc folder and someof them use dscv2 folder from the repo. interestingly in the repo  we only use dscv2. and we can not move contents of dscv2 to dsc because there are differences. original amp template refer to dscv2 (small letters)

**Comment by bmoore-msft** [comment]
Ok, can you put a note in the readme.md for this sample to include the cmdline needed to deploy it via the scripts in the root of the repo?

**Pull request merged**
