### PR TITLE
Updates ARM template files - HDInsight ML Services

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template used in ARM template [quickstart](https://docs.microsoft.com/en-us/azure/hdinsight/r-server/quickstart-resource-manager-template) article.
- Adds quickstart article's author to `docOwner` in _metadata.json_.
- Adds the `environments` tag to _metadata.json_. 
- Updates _README.md_ 
  - link to the quickstart article
  - removes duplicate HTML link for the Visualize button.
- Updates resource `type` to the latest `apiVersion`.
- Fixes order of template's `resources` properties based on best practices guidance.
- Fixes indentation.

### CODE REVIEW

**Comment by davidsmatlak** [comment]
@bmoore-msft Why didn't the automated validation checks run on this pull request?

**Comment by davidsmatlak** [comment]
@hrasheed-msft - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@davidsmatlak - the triggering isn't as robust as it should be, sometimes it doesn't work.  When it doesn't you can usually just add a commit to trigger it - sometimes that doesn't work and you have to open a new PR.

I added a commit and it triggered this time...

**Comment by bmoore-msft** [comment]
@hrasheed-msft - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
@bmoore-msft Thanks for the update. I have PR 8112 with the same issue, so I'll add a commit to trigger a build.

**Comment by davidsmatlak** [comment]
@bmoore-msft one validation **succeeded with issues** the other failed. I'll review the logs tomorrow and update the pull request.

**Comment by bmoore-msft** [comment]
@hrasheed-msft - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@hrasheed-msft - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@hrasheed-msft - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@hrasheed-msft - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@hrasheed-msft - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
@hrasheed-msft @bmoore-msft Please review this pull request and provide guidance on how to resolve the validation errors. Thanks.

- Best practices validation shows errors for existing template code that wasn't changed by this pull request with the exception of `apiVersion`.
- Gov validation fails with message that `rserver` isn't supported on `HDInsight` version 3.6. 
- Reverting template's `resources` to prior `apiVersion` didn't resolve the errors, so the latest `apiVersion` is used.
- Added Deploy to Azure Gov button to fix a build warning. If that's not correct please let me know.

**Comment by bmoore-msft** [comment]
@hrasheed-msft - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
@hrasheed-msft 

- To resolve the Gov build validation that `rserver` isn't supported on `HDInsight` version 3.6, I added the `environments` tag to _metadata.json_. 
- I removed the **Deploy to Azure Gov** button _README.md_ that I added to troubleshoot build errors. 
- The warnings in the best practices validation are for existing template code that wasn't changed by this pull request.

**Comment by bmoore-msft** [comment]
@hrasheed-msft - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@hrasheed-msft - check this PR for updates that may be needed to documentation that references this sample.

**Pull request merged**
