### PR TITLE
[New]Added create IoT Hub with C2D and D2C configurations and consume…

### PR DESCRIPTION
**Pull request by moonytheloony**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
*
*
*
*
*

### Description of the change
…r group

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@moonytheloony__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@moonytheloony__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by singhkay** [comment]
@moonytheloony This is pretty unique contribution! Thank you! merged

**Comment by moonytheloony** [comment]
Thank you @singhkay. Happy to contribute.

**Pull request merged**
