### PR TITLE
Updates per closed PR# 12694

### PR DESCRIPTION
**Pull request by ecfan**
Replicating updates from the closed PR: https://github.com/Azure/azure-quickstart-templates/pull/12694/files

CC: @vinnieangel 

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Replicate updates from closed PR https://github.com/Azure/azure-quickstart-templates/pull/12694/files
*
*

### CODE REVIEW

**Comment by ecfan** [comment]
#assign:@vinneangel
#assign:@bmoore-msft

**Comment by ecfan** [comment]
#assign:@bmoore-msft

**Comment by azure-quickstarts** [comment]
@ecfan - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by ecfan** [comment]
#assign @ecfan

**Pull request merged**
