### PR TITLE
Update sample create-role-def

### PR DESCRIPTION
**Pull request by johndowns**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Add Bicep file
* Update to most recent API version
* Remove old note from metadata

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@rolyon - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@rolyon - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by johndowns** [comment]
@bmoore-msft Please let me know if you think we should do anything with the BPA/TTK results. The latest API version known to Bicep is 2018-01-01-preview, which is what we use. If we use a more recent version, Bicep will throw a warning.

**Review by bmoore-msft — CHANGES_REQUESTED** [review]
Fix the BPA error so the badge is clean - can also make sure bicep is aware of the missing type

**Comment by azure-quickstarts** [comment]
@rolyon - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by johndowns** [comment]
@bmoore-msft Updated as requested, and I've [reported this issue on the Bicep issues list](https://github.com/Azure/bicep/issues/784#issuecomment-967570020).

**Pull request merged**
