### PR TITLE
add a template for vms with selfhost IR installed

### PR DESCRIPTION
**Pull request by xiaoyingLJ**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

*
*
*

### CODE REVIEW

**Comment by bmoore-msft** [comment]
why are we skipping CI?

**Comment by xiaoyingLJ** [comment]
since we depends on existing resources such as data factory and vnet.

**Comment by bmoore-msft** [comment]
For the existing resources, you need to supply the prereq templates to deploy those...  See: https://github.com/Azure/azure-quickstart-templates#template-pre-requisites

**Comment by xiaoyingLJ** [comment]
Hi, Brian

In my case, the existing resources and the new resources created in my template could be in different resource groups, so I need to fill in the “ResourceGroupName” of existing resources as parameters. But when I try to get the resource group name of the “prereqs.azuredeploy.json”, I don’t find a way to achieve this. Do you know how to achieve this?

Thanks
Xiaoying

**Comment by xiaoyingLJ** [comment]
Hi, Brian

Thanks. I have already find a way to get the resource group name. But the prereqs doesn’t work as expected. The error message: Resource group 'GET-PREREQ-resourceGroupName' could not be found.

Thanks
Xiaoying

From: Xiaoying Zhang
Sent: Monday, October 30, 2017 12:07 PM
To: 'Azure/azure-quickstart-templates' <reply@reply.github.com>; Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [Azure/azure-quickstart-templates] add a template for vms with selfhost IR installed (#3997)

Hi, Brian

In my case, the existing resources and the new resources created in my template could be in different resource groups, so I need to fill in the “ResourceGroupName” of existing resources as parameters. But when I try to get the resource group name of the “prereqs.azuredeploy.json”, I don’t find a way to achieve this. Do you know how to achieve this?

Thanks
Xiaoying

**Pull request merged**
