### PR TITLE
Template to create an Azure Machine Learning dashboard using existing Log Analytics diagnostics data

### PR DESCRIPTION
**Pull request by eldarku**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*sample view:
Azure_Dashboard

### CODE REVIEW

**Comment by eldarku** [comment]
About this check:
image
- it's a false positive, as in the last API version - 2020-09-01-preview Log Analytics (Microsoft_OperationsManagementSuite_Workspace) visuals not supported:
https://docs.microsoft.com/en-us/azure/templates/microsoft.portal/2020-09-01-preview/dashboards?tabs=bicep
- most probably because it's in preview. 

Exporting dashboard from the portal or using Az CLI, this:
image
- generates even older API version json,   "apiVersion": "2015-08-01-preview".

**Comment by Blackmist** [comment]
@bmoore-msft Can you help on this one? It looks like the checks are not accepting the API version. The one we're trying should be within the 2 year limit.

**Comment by eldarku** [comment]
> @bmoore-msft Can you help on this one? It looks like the checks are not accepting the API version. The one we're trying should be within the 2 year limit.
Thank you Larry!

Just to clarify, I am using "2019-01-01-preview" Dashboard API version, which is indeed more than 2-years old.
The BPA analyzer suggests to use the "2020-09-01-preview" API version instead, but the problem with it is it doesn't support Log Analytics visuals "Microsoft_OperationsManagementSuite_Workspace" yet, as documented [here](https://docs.microsoft.com/en-us/azure/templates/microsoft.portal/2020-09-01-preview/dashboards?tabs=bicep) 
I tried all types of supported visuals - they didn't work with LA and Cost visuals. I think this is the reason why older APIs version used when existing dashboard exported form the portal.

**Comment by alex-frankel** [comment]
A couple of questions:

1. For the newer API version, is there not equivalent functionality that you can use in the newer API version? I am not seeing what you are referencing in the doc you linked to that clarifies that certain functionality was removed.
2. I see another BPA error for another check. Do you know why that might be happening?

Specifically:
```
##[error]Analyze-Template : TemplateAnalyzer failed trying to analyze: C:\a\1\s\quickstarts\microsoft.machinelearningservices\machine-learning-workspace-monitoring-dashboard\azuredeploy.json C:\a\1\s\quickstarts\microsoft.machinelearningservices\machine-learning-workspace-monitoring-dashboard\gen.azuredeploy.parameters.json
```

Here is the full error response:

```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           12/3/2021 12:27 AM                templateAnalyzer
##[error]Invoke-WebRequest : Not Found
At C:\a\1\test\ci-scripts\Run-TemplateAnalyzer.ps1:22 char:1
+ Invoke-WebRequest -OutFile "$templateAnalyzerFolderPath\TemplateAnaly …
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Reques…ontent-Length: 0
}:HttpRequestMessage) [Invoke-WebRequest], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
Expand-Archive : The path 'C:\a\1\test\templateAnalyzer\TemplateAnalyzer.zip' either does not exist or is not a valid file system path.
At C:\a\1\test\ci-scripts\Run-TemplateAnalyzer.ps1:23 char:1
+ Expand-Archive -LiteralPath "$templateAnalyzerFolderPath\TemplateAnal …
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (C:\a\1\test\templat…emplateAnalyzer.zip:String) [Expand-Archive], InvalidOperationException
+ FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive
& : The term 'C:\a\1\test\templateAnalyzer\TemplateAnalyzer.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\a\1\test\ci-scripts\Run-TemplateAnalyzer.ps1:44 char:25
+         $testOutput = & $templateAnalyzer analyze-template $templateF …
+                         ~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\a\1\test\templat…emplateAnalyzer.exe:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

##[error]Analyze-Template : TemplateAnalyzer failed trying to analyze: C:\a\1\s\quickstarts\microsoft.machinelearningservices\machine-learning-workspace-monitoring-dashboard\azuredeploy.json C:\a\1\s\quickstarts\microsoft.machinelearningservices\machine-learning-workspace-monitoring-dashboard\gen.azuredeploy.parameters.json
At C:\a\1\test\ci-scripts\Run-TemplateAnalyzer.ps1:78 char:34
+             $newAnalysisPassed = Analyze-Template @params
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Analyze-Template

##[error]PowerShell exited with code '1'.
```

**Comment by eldarku** [comment]
Thanks for reviewing @alex-frankel!
1. _For the newer API version, is there not equivalent functionality that you can use in the newer API version?._
This template contains visualization of Log Analytics Kusto queries. These visuals have type 
"type": "Extension/Microsoft_OperationsManagementSuite_Workspace/PartType/LogsDashboardPart","
it works with all API versions except the latest one, 2020-09-01-preview.
If you create a dashboard in the portal, add any Log Analytics query on it,  and download it's definition (using export->download), exactly this will be used.
Now, in the latest API 2020-09-01-preview, the only one type of this visual is allowed - "Extension/HubsExtension/PartType/MarkdownPart":
image
I actually tried to use both options in the template (along a few other undocumented options), got empty visuals like this:
image
It's worth noting that when I export this blank erroneous dashboard, just deployed with "API 2020-09-01-preview", I got a definition with  "apiVersion": "2015-08-01-preview" again. 
I suppose this suggests that these newer API  versions of the are still somehow incomplete.

_2. I see another BPA error for another check. Do you know why that might be happening?_
No, I don't know why it could happen.  Can it be related with this recently merged PR? 
https://github.com/Azure/azure-quickstart-templates/pull/12060

**Comment by eldarku** [comment]
@alex-frankel - thanks to your help, I fixed this API issues.
Can you please review when you have time.

**Comment by alex-frankel** [comment]
Looks good! While Brian is OOF, we are going to approve and merge any PRs without his review as long as the CI tests are passing. It is possible he may follow up and request changes once he is back.

**Pull request merged**
