### PR TITLE
Add --sha1 for bosh upload command (stemcell && CF release); Refine l…

### PR DESCRIPTION
**Pull request by zhongyi-zhang**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
- Add --sha1 for bosh upload command (stemcell && CF release)
- Switch to mirror.azure.cn to download releases and stemcells in AzureChinaCloud
- Write more logs to install.log in dev-box

### Description of the change
With the changes, 
- BOSH checks SHA1 while uploading stemcell and CF release.
- Releases and stemcells in AzureChinaCloud are downloaded from mirror.azure.cn.
- More logs.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@zhongyi-zhang__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by bingosummer** [comment]
LGTM

**Comment by bmoore-msft** [comment]
We need to update the filesToDownload sections with the best practices here: 
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md#samples-that-contain-extra-artifacts-custom-scripts-nested-templates-etc

And then ensure that you can use the script in the root of the repo to deploy the template.

**Comment by bingosummer** [comment]
@bmoore-msft 
Thanks for your suggestion.

In our scenario, we don't want users to input the script URLs. The scripts are provided by us, not users. For Global Azure, the scripts are downloaded directly from Github. For Azure China Cloud, the scripts are downloaded from a storage account we host. Why we use Azure Storage to store scripts in `AzureChinaCloud` is that the network is not stable in China. Storing them in Azure Storage can provide a better experience. And the permission of the storage blob is `public`, so that they can be downloaded if the template is deployed in `AzureChinaCloud`.

So, based on our scenario, I think, `_artifactsLocation` is not necessary. Do you think it makes sense?

**Comment by bingosummer** [comment]
@singhkay 
Could you please have a review?

**Comment by gatneil** [comment]
LGTM; merging

**Pull request merged**
