### PR TITLE
Created template to deploy Application Gateway

### PR DESCRIPTION
**Pull request by rajinders**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rajinders__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by rajinders** [comment]
renamed azuredeploy.parameters.json file to azuredepoy-parameters.json

**Comment by azurecla** [comment]
Hi __@rajinders__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by rajinders** [comment]
reopened the pull request to make any needed changes.

**Comment by singhkay** [comment]
@rajinders Thanks for the contribution! merged

**Pull request merged**
