### PR TITLE
[Do Not Merge] Add new features and refine the template

### PR DESCRIPTION
**Pull request by bingosummer**
- New features
      - Support Azure DNS
      - Support creating additional storage accounts
      - Support deploying Bosh automatically
    - Update to the official BOSH release, Azure CPI release and Azure stemcell
    - Parameters and Variables
      - Remove the parameter "newStorageAccountName" and generate it by uniqueString()
      - Create the dev-box with SSH Keys
      - Make service principal parameters required and fixed-length
      - Move the parameter "vmSize" into a variable
      - Move the parameters about vnet & subnet to variables
      - Change the CIDR of the subnet for Cloud Foundry to /20
    - Render the manifest of Bosh
      - Autofill the service principal
    - Render the manifest of Cloud Foundry
      - Autofill the virtual network name, the subnet name and so on.
    - Upgrade versions
      - Upgrade bosh_cli and bosh-init
      - Upgrade API version to the latest 2015-06-15
      - Upgrade to Ubuntu Server 14.04.3 LTS
      - Upgrade the default "storageAccountType" into Standard_RAGRS
      - Upgrade the version of CustomScript Extension to 1.4
        - Download the scripts and manifests via fileUris
        - Put commandToExecute into protectedSettings to protect users' credentials

Please have a review. Thanks.
Will remove [Do Not Merge] in the title when we are ready.

### CODE REVIEW

**Comment by bingosummer** [comment]
@singhkay 
1. Should I ignore the error @acomghbot reports?
2. I'm not clear about the error which CI reports? Could you explain it a little more? Thanks
```
Variable length unique params must specify a length between 3 and 32
```

**Comment by AbelHu** [comment]
@bingosummer I guess that the CI will use all default values to run the template in bosh-setup/azuredeploy.parameters.json. You should use valid values in bosh-setup/azuredeploy.parameters.json.

**Comment by sedouard** [comment]
hey guys, unfortunately the [ci validation server](https://github.com/sedouard/azure-arm-validator) doesn't know how to deal with generating AAD credentials for your template. That's out of its ability today.

To get the green checkmark, you'll need to add a file called `.ci_skip` in the template's root. This will skip CI so you should be extra super duper sure your template works (including gotcha's like links to `raw.githubusercontent.com`)

**Comment by bingosummer** [comment]
@sedouard 
In this template, we just need to generate a 36-length string to replace the tenant id and client id. They can be fake. 
I provide a fake service principal in "Provide default values for AAD credentials" and the CI should pass. But it still give an error.

**Comment by bingosummer** [comment]
@sedouard 
Another question:
Why can `[N]` only be any number from 3 to 32 in `GEN-UNIQUE-[N]`?

**Comment by sedouard** [comment]
Unfortunately we've [been waiting](https://github.com/Azure/azure-xplat-cli/issues/1831) on the CLI team to give us the fix that would print out resource deployment errors like you see in the powershell cli. 

Anyways, the CI logs on travis will always show you the rendered parameters and rendered template. Unfortunately not in the best formatting but I think I can fix that for future runs. If you run your template with these parameters, you'll be able to reproduce the error:

```
{"$schema":"http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#","contentVersion":"1.0.0.0","parameters":{"vmName":{"value":"ci56efd7eb20e4b55f"},"adminUsername":{"value":"azureuser"},"sshKeyData":{"value":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJigGXhSKgue3RiGnFLWM4m+jT1QA9lvLewPNZ95duZ/ZN0CLf/u+RnLKH/sR2FS2lDXkuVGVr2nMlJv1MmWxulkzgCqQIrw4EGcw5zFk1jYpJri93YzUkG9KFDfUHoh0oLzATeCedsVsHEf2Wp6zxWzNU3LyxyUKqRESzg/vA0ZkzTsEhr8a3XZ8VQCIsWdDc3Zdxsrq3qCxp11VG6e4MZ/8+3nP1osEOGw5cmLpxyw6ab3/7dWo1jyZgbE6k39nJsgV0IXX0HHAXD8fGbE6kd+RCOyH3Jx0h3WCLcbzogVW/tLEzqETvZGLqHC4neDvJn1I77ORxjOwbW4ZtYEPL sedouard@Stevens-MBP"},"tenantID":{"value":"12345678-1234-1234-1234-123456789abc"},"clientID":{"value":"12345678-1234-1234-1234-123456789abc"},"clientSecret":{"value":"ciP$ss5a54ea28a6090e49"},"additionalStorageAccounts":{"value":"enabled"},"additionalStorageAccountsNumber":{"value":3},"azureDNS":{"value":"enabled"},"systemDomainName":{"value":"example.com"}}}
```

**Comment by sedouard** [comment]
Also if you want a longer random string just put two GEN_UNIQUE's together. For example `GEN_UNIQUE[N]GEN_UNIQUE[N]` We just do a string replacement so this should get you the correct number of characters you want.

**Comment by singhkay** [comment]
@bingosummer Template looks good. Let's get the CI to pass with @sedouard's suggestions

**Comment by singhkay** [comment]
@bingosummer Any update on this?

**Comment by bingosummer** [comment]
@singhkay 
Yes. Please do not merge this PR.
Will update it after Chinese New Year.

**Comment by bingosummer** [comment]
Thanks @sedouard and @singhkay for your comments.
Will create a new PR later.

**Pull request closed without merging**
