### PR TITLE
Missing subscriptionId param in 101-rbac-builtinrole-virtualmachine

### PR DESCRIPTION
**Pull request by lorenpaulsen**
I was not able to use this ARM template as-is because of the reference to undefined parameter `subscriptionId`. Other similar samples infer the subscription ID through `subscription().subscriptionId` so I have made the same substitution here.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lorenpaulsen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@lorenpaulsen Thanks for fixing! Could you also update the metadata file according to convention? https://github.com/Azure/azure-quickstart-templates/tree/master/1-CONTRIBUTION-GUIDE#metadatajson. That is what is currently causing the failure.

**Comment by lorenpaulsen** [comment]
@singhkay How do I fix this CI error? This template was originally intended to run against an existing VM, so I'm not sure what VM name to use here.

**Comment by singhkay** [comment]
@lorenpaulsen Ah got it. In that case changing the metadata file will do. Thanks!

**Pull request merged**
