### PR TITLE
MOVE: 101-event-grid-subscription-and-storage to quickstarts\microsoft.eventgrid

### PR DESCRIPTION
**Pull request by akhilthomas011**
…t.eventgrid\event-grid-subscription-and-storage

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@spelluru - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by azure-quickstarts** [comment]
@tfitzmac - this appears to be a "Move" that will need a manual doc update

**Comment by spelluru** [comment]
@akhilthomas011 - Thank you! I have three articles with links to this sample and I will update them as soon as this PR is merged.

**Comment by azure-quickstarts** [comment]
@spelluru - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by azure-quickstarts** [comment]
@tfitzmac / @mumian- this appears to be a "Move" that will need a manual doc update

**Comment by amalik99** [comment]
@spelluru  - PR is merged.

**Comment by spelluru** [comment]
Thanks @amalik99. I will update the referencing links from my articles.

**Pull request merged**
