### PR TITLE
Updated cloud storage template

### PR DESCRIPTION
**Pull request by adityabalaji-msft**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

*
*
*

### CODE REVIEW

**Comment by adityabalaji-msft** [comment]
Hi @bmoore-msft - Made an update to one of the nested templates. Build fails with ResourceNotFound error. I guess it is because the pipeline places the prereqs and the templates in different resource group, which is not allowed for this particular solution (as discussed in one of my earlier PRs [here](https://github.com/Azure/azure-quickstart-templates/pull/6341)).

I have deployed the template locally and it works.

If there are no other changes to be made from my end, please merge these commits. Thanks!

**Comment by adityabalaji-msft** [comment]
Hi @bmoore-msft / @krnese - This template update was made in order to mitigate an ICM, so would be extremely grateful if you could take a look at the same at the earliest, so that I can inform CSS. Thanks!

**Comment by adityabalaji-msft** [comment]
Any update?

**Comment by adityabalaji-msft** [comment]
Hi @bmoore-msft  - The errors which show up in the pipeline results are of the following categories:

1)	**Validate metadata.json (Display name of the template is too large)** – I have now shortened the display name.
2)	**Run Best practices test (Property: Dashboard must use resourceId() instead of a static id – shows up for all the nested templates)** – ‘Dashboard’ is not really an ARM Resource. The resources being deployed are of type Microsoft.OperationalInsights/workspaces/views, of which ‘Dashboard’ is one of the properties ([doc link](https://docs.microsoft.com/en-us/azure/azure-monitor/insights/solutions-resources-views)). The static id which is populated for the dashboard in the json file comes from the LA View Designer tool, when we export the views as json. Hence there is no ‘Resource Type’ as such we can use to create an ARM id for the Dashboard property. This appears to be more like a warning and not a blocking issue.
3)	**Deploy Main Template (Resource X under Resource Group Y not found)** – As discussed in one of my earlier PRs [here](https://github.com/Azure/azure-quickstart-templates/pull/6341), I believe this error is appearing because the pipeline places the prereqs and nested templates in different resource groups. However, in the case of this template, the prereq (LA Workspace) and the nested templates (views) need to be part of the same resource group.

I have deployed the template locally and it works.

Please let me know if anything else is needed from my end.

PS – After adding the change to the display name, I now see that there is an error in the step ‘Write Test Results to readme.md’: “You cannot call a method on a null-valued expression”. Could you help me understand this error?

Would be grateful if you could provide guidance on getting this merged.

**Comment by adityabalaji-msft** [comment]
@bmoore-msft Any update on this?

**Comment by bmoore-msft** [comment]
It looks like there are still a few problems with CI and prereqs - the prereqs should be deployed into the same group now, but are missing parameters... let's focus on getting a successful deployment, we can look at the BP tests separately once deployment succeeds.

**Comment by bmoore-msft** [comment]
Closing abandoned request - please reopen if you can address the feedback.

**Pull request closed without merging**
