### PR TITLE
Streamline

### PR DESCRIPTION
**Pull request by squillace**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
* added default values for all values except the SSH public key string
* added automatic uniquestring values for DNS subdomains
*
*
*

### Description of the change
I've streamlined the template to request ONLY an SSH key and a resource group name and location. Smoothest experience launch in the portal so far.

### CODE REVIEW

**Comment by squillace** [comment]
@rjmax @singhkay please vet; I'm updating the template to require only three items:

1. the resource group name you want to create
2. the ssh key you want to use
3. the location you want for your group and deployment

The goal here is one of the cleanest direct portal-launches and cli launches that you can have.

to test: `azure group create -n <groupname> -l <location> --template-uri <raw uri>`

creates super fast in westus this way....

**Comment by singhkay** [comment]
@squillace Looks good since you're generating the unique DNS. I'd add the username and dns and ssh connection to outputs section like here https://github.com/Azure/azure-quickstart-templates/blob/master/101-vm-simple-linux/azuredeploy.json#L187

**Comment by squillace** [comment]
OK, hold off for another bug: turns out uniquestring for dns name can generate strings that start with numbers, which dns regex disallows. So I have to also prepend an 'a' to the uniquestring.

I'll make the other fixes as well. thanks!

**Comment by squillace** [comment]
@singhkay OK, reverse the dns name and the uniquestring to handle the bug, and I've add the ssh output link. We don't need the username, because that's in the ssh output; as is the domain name. Bag on the IP.

**Comment by squillace** [comment]
#sign-off. @singhkay ???

**Comment by squillace** [comment]
Uh, @singhkay, your CI is a bit flaky. It signaled a failed check, told me to validate the template, and:

azure group template validate --resource-group sshtemplatetest4 --template-uri https://raw.githubusercontent.com/squillace/azure-quickstart-templates/streamline/101-vm-sshkey/azuredeploy.json                                           azure-quickstart-templates
info:    Executing command group template validate
info:    Supply values for the following parameters
sshKeyData: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDRZ/XB8p8uXMqgI8EoN3dWQwVMHbzTPlZk5l/euYJVPXBYaHvdrPZ76auwNBZ5EtSUZlg602n5PJzSkWh3Dztz8/nKTLow63DE+48bj3PoUiCZD3g8AbXp37Zpv9Wj1ZymZQzX9OYxekmFtk47RrT+THJgMrhATtss1EFTIR39r5VzBH/rNAX+Ou7n97V/AHPQf9fyoUu4oVg5g40ylzDXueT1Q+n67Z6r3OSNXaiu7V1hJmUsyMzY3uxmbbOmkPRJLAGIfERk/O5saqi9wspYphqnfhbnO0Fhg0aYec1BqhAakkAkf7ix+Skdw06VQmr6t2MrUH9totinVqJYybf ralph@squillace.com
+ Initializing template configurations and parameters
+ Validating the template
info:    group template validate command OK

it all works fine. now it's trying again?

**Comment by singhkay** [comment]
@squillace Yeah the "free" dns service can be flaky :) kicked off the build again

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
