### PR TITLE
Changed PowerShell DSC extension versions from 1.0-2.3 to v2.8 

### PR DESCRIPTION
**Pull request by slapointe**
This is to prevent templates deployment failure because these versions have been removed 3 days ago.

http://blogs.msdn.com/b/powershell/archive/2015/10/26/azure-dsc-extension-versions-1-0-2-3-no-longer-available.aspx

This pull request also contain fixes for parameters file that were visibly not validated before.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@slapointe__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by slapointe** [comment]
Depending on the state of the pull request #739, this may seem as a duplicate. In this PR I only update the versions to v2.8 for templates referencing DSC prior to v2.4, leaving the others untouched.

**Comment by singhkay** [comment]
@slapointe I'd like to run these through the automated bot testing. Can you include 5 #'s i.e. "#####" as values for things such as storage accounts and dns names in the parameter files? The automated bot will replace this with auto-gen'd strings.

**Comment by slapointe** [comment]
You want me to append the #'s or replace the values with 5 #'s, just want to be sure...

**Comment by singhkay** [comment]
@slapointe replace :)

**Comment by slapointe** [comment]
I modified both parameter files that I originally touched (one was excluded at first, it caused the double commit, sorry for that)

Let me know if there's anything else

**Comment by singhkay** [comment]
@slapointe The bot is going to go through all the templates in this PR and start testing them one by one. Can you make the same changes in all these tempaltes' parameter files? Also, make sure to replace any empty strings you find. Thanks!

**Comment by singhkay** [comment]
@template-deploy-bot test this please

**Comment by singhkay** [comment]
@slapointe Looks like some of the parameters named "storageAccount" are causing the deployment to fail. Can you rename this to "newStorageAccount"? I truly appreciate the help here with testing the bot! :)

**Comment by singhkay** [comment]
@template-deploy-bot test this please

**Comment by slapointe** [comment]
I renamed two storage account name that weren't named newStorageAccount, should be good now.

**Comment by singhkay** [comment]
@slapointe Awesome! Looks like we got our first error back from trying to deploy the 201-vm-domain-join. Probably because the password is "changeme" :)

**Comment by slapointe** [comment]
@singhkay I have added a powershell script at the root, or you may want it somewhere else. It's goal is to help testing a template by launching a deployment and generating a random value like your testing bot for ##### values.

The script is compatible with v0.xxx & v1.xxx

**Comment by singhkay** [comment]
@slapointe Sweet! I can definitely see this being useful. Let me see how it works and probably will recommend it in the official contributing guide. I'm doing something similar with the bot + query GitHub API. The shared scripts folder on here might be a better venue for it though.

**Comment by singhkay** [comment]
@template-deploy-bot test this please

**Comment by slapointe** [comment]
@singhkay At the moment it's a script but we could change this to a module and expose the Test-AzureRmTemplateDeployment function. With a module I could provide TAB AutoCompletion for template names. (scanning all template folders)

The experience would be better like this but the user would have to import a module prior calling the function.

What do you think?

**Comment by singhkay** [comment]
@slapointe Love it! We can put in an official recommendation for authors to import the module from shared scripts folder and test the template with it before committing!

Btw, looks like the template failed. Did this deploy for you with 2.8 version of DSC?

**Comment by slapointe** [comment]
There are 3-4 templates that fails, I need to investigate more. I didn't imagine at first that changing the version number would open a can of worms... They probably haven't been working for a while now...

**Comment by slapointe** [comment]
@singhkay For the module, I was thinking to name it: AzureQuickstartTemplatesQualityControl.psm1 and the function: Test-AzureQuickstartTemplate

You like that?

**Comment by singhkay** [comment]
Adding @TravisEz13 from the DSC team to help with figuring out if there is something wrong with DSC configs in them 

@slapointe Name sounds good

**Comment by slapointe** [comment]
The problem mostly seems to be DC & domain join scenarios. I'll continue to investigate later this weekend but I am afraid I won't have much time.

**Comment by slapointe** [comment]
@singhkay One of the thing I saw in a lot in the templates are the use of a parameter named "assetLocation". They usually point it to the template folder on GitHub to fetch DSC packages or other deployment templates. With your new system in place (the bot that test the templates) it will be impossible to perform a one step commit/push when using an assetLocation pointing to the GitHub repo...

Users will have to copy their artifacts elsewhere (public), and temporarily change the assetLocation in the parameters file to let the template use the correct version of artifacts because the pull request will not be done and merged to master yet), They will need to perform a second commit/push to update back the parameters file to point to GitHub again.

Very unpleasant and not fun for you either... We need to think of something for this.

**Comment by singhkay** [comment]
@slapointe Ya, that's a good catch! Let me think about how to make it work in this scenario.

**Comment by singhkay** [comment]
@template-deploy-bot test this please

**Comment by slapointe** [comment]
@singhkay  I am back on this,  trying to figure out why the VM fails at the WaitForDomain DSC step... it doesn't find the domain / DC for some reasons... Will look for someone to give me a hand on this. Or do you have an expert on this on your side?

**Comment by singhkay** [comment]
@slapointe Let's follow up offline with the DSC team. Can you send me an email with the template file you're testing and the DSC error. Thanks!

**Pull request merged**
