### PR TITLE
VMSSDependsonLB

### PR DESCRIPTION
**Pull request by viveksingla08**
Deployment is failing as VMSS should be dependent upon LB

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@ju-shim - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by ju-shim** [comment]
Looking at this now and checking with team. I think this is acceptable, but will test before signing off.

**Review by ju-shim — APPROVED** [review]
Reviewed with PM team, they approved.

**Comment by ju-shim** [comment]
#sign-off

**Comment by ju-shim** [comment]
#sign-off

**Pull request merged**
