### PR TITLE
SerivceBus: Added template for Standard to Premium namespace migration

### PR DESCRIPTION
**Pull request by v-Ajnava**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

* Added template for Standard to Premium namespace migration
*
*

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@v-Ajnava - check the CI failures and format the json

**Comment by v-Ajnava** [comment]
@bmoore-msft , this template is similar to '101-servicebus-create-namespace-geo-recoveryconfiguration' where we initiate the paring of two namesspaces. the cleanup of resource group will fail untill the paring between namespace is broken. 
please suggest on the CI failure

**Comment by bmoore-msft** [comment]
This is the script that get run to tear down the RG, what needs to be added to that to break the pairing (it already has some code to do that)

https://github.com/Azure/azure-quickstart-templates/blob/master/test/ci-scripts/Kill-AzResourceGroup.ps1

**Comment by bmoore-msft** [comment]
@v-Ajnava - it looks like this sample has had some breaking changes in the latest apiVersion... if you can fix those, please resubmit.

**Pull request closed without merging**
