### PR TITLE
powercoinazure-blockchain

### PR DESCRIPTION
**Pull request by powercoinpwr**
### Contributing guide

https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md
### Changelog

*
*
*
*
*

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@powercoinpwr__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@powercoinpwr__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by gatneil** [comment]
sorry for the delay; is this something we still want to merge in?

**Comment by gatneil** [comment]
No response; closing

**Pull request closed without merging**
