### PR TITLE
[AKS] - update api version

### PR DESCRIPTION
**Pull request by mumian**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@mlearned - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@mlearned - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by tfitzmac** [comment]
@mumian and @bmoore-msft - just wanted to check why azuredeploy.json was deleted? Is the intention now to autogenerate the ARM template from the Bicep file? It looks like this ARM template was used in a documentation quickstart which is now broken.

**Comment by bmoore-msft** [comment]
yes, the json file should be generated upon merge... if it's not we need to tickle it again with a commit/PR (which I just did)

**Pull request merged**
