### PR TITLE
Updates ARM template files - DevTest Labs

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template used in ARM template [quickstart](https://docs.microsoft.com/azure/devtest-labs/create-lab-windows-vm-template) article.
- Adds quickstart article's author to `docOwner` in _metadata.json_.
- Updates _README.md_ with link to the quickstart article.
- Updates resource `type` to the latest `apiVersion`.
- Fixes order of template's `parameters` and `resources` properties based on best practices guidance.

### CODE REVIEW

**Comment by davidsmatlak** [comment]
GitHub status page shows degraded performance. The public build couldn't connect to Azure and failed. I'll revisit this pull request Tuesday.

**Comment by bmoore-msft** [comment]
@Juliako - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@Juliako - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
@bmoore-msft I updated the resource's `apiVersion` from the original **2018-09-15** to **2018-10-15-preview** because the ARM toolkit build validation and Azure Resource Explorer shows the preview as the latest valid API. The [DevTestLab API spec](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/devtestlabs) doesn't show the preview version. Please let me know if I should revert the change.

**Comment by bmoore-msft** [comment]
changes look good - TTK pulls the apiVersions from Azure, so it's fine to use a later one that's not doc'd

**Pull request merged**
