### PR TITLE
Move to latest DSC extension version

### PR DESCRIPTION
**Pull request by jodoglevy**
@mgreenegit @charlesjoy as FYI

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jodoglevy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jolevy). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
lgtm, merged. @jodoglevy Any major updates/fixes in DSC 2.15?

**Comment by jodoglevy** [comment]
Thanks @singhkay . 2.13 installs WMF 5 Prod Preview. 2.14 installs WMF 5 RTM, but has an issue moving from WMF 5 Prod Preview to RTM (so will fail on an Azure VM you've used 2.13 on previously). 2.15 fixes that issue.

**Comment by singhkay** [comment]
@jodoglevy Awesome! thanks

**Pull request merged**
