### PR TITLE
DataStax update

### PR DESCRIPTION
**Pull request by benofben**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
Updated from https://github.com/DSPN/azure-resource-manager-dse  These changes include over a year of work with Azure engineering.  Also dropping the three DataStax templates so we only have one.

### Description of the change
See above.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@benofben__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by benofben** [comment]
It looks like the pull is failing CI because the datastax-enterprise dir has been removed.  I'm not sure how to fix this with the CI.  Can you help?

**Comment by benofben** [comment]
Huh.  Now the build error says I need a .parameters in the .parameters file.  @singhkay can you help shepherd this pull request through?  I'm a bit lost on the requirements.

**Comment by benofben** [comment]
Ok.  I think I understand what it's mad about.  Going to close this and try a third (?!!?) pull request...

**Pull request closed without merging**
