### PR TITLE
thecreed-blockchain

### PR DESCRIPTION
**Pull request by thecreedcurrency**
### Contributing guide

https://github.com/thecreedcurrency/TCR
Thecreed [TCR] Azure Node Ubuntu VM
### Changelog

*thecreed azure vm ubuntu v.1[First Commit]
*
*
*
*

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@thecreedcurrency__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@thecreedcurrency__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by gatneil** [comment]
Sorry for the delay; is this something we still want to merge in?

**Comment by gatneil** [comment]
No response; closing

**Pull request closed without merging**
