### PR TITLE
Update SSHKeyManagement.md

### PR DESCRIPTION
**Pull request by derdanu**
Tunnel server port to local client not vice versa.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@derdanu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@rgardler Can you verify this change?

**Comment by singhkay** [comment]
@derdanu Looks like there was an update to this template made by @rgardler and there is a merge conflict. Can you resolve?

**Comment by derdanu** [comment]
I have created a new pull request to fix the merge conflict. #1268

**Pull request closed without merging**
