### PR TITLE
Updating Visual Studio with Visual Studio Online Agent template

### PR DESCRIPTION
**Pull request by nzthiago**
Fixed variables and introduced retries to the VSO Agent install.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nzthiago__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@nzthiago Removing CLA requirement since you're MSFT FTE. To enable automated testing, can you supply a parameter file that will allow us to deploy this template successfully? For things like storage accounts and dns names you can put in 5 # in the value i.e. "#####" and the bot will replace these with random characters. Thanks!

**Comment by nzthiago** [comment]
@singhkay done, updated the params that could be random. The Visual Studio Online Agent ones are passed into a custom script. The custom script will fail with the values in the variables but I don't think that will report a failure for the overall template deployment for the automated testing

**Comment by singhkay** [comment]
@nzthiago I see. We're still testing out the bot on all various scenarios so let's see what happens and can update as necessary. Btw you should probably change the password value to "YourAdminPassw0rd!" since the bot generates lower cased characters to satisfy storage account naming requirements and password needs a capital letter which will make the random generated password fail unfortunately :(

**Comment by nzthiago** [comment]
Done, changed the VM password back, thanks!

**Comment by singhkay** [comment]
@nzthiago awesome! let's test this

@template-deploy-bot test this please

**Comment by singhkay** [comment]
Looks good, merging

**Comment by nzthiago** [comment]
thankyou

**Pull request merged**
