### PR TITLE
[managed-mariadb-with-vnet] update api versions and add outputs

### PR DESCRIPTION
**Pull request by mumian**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@shreyaaithal - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by mumian** [comment]
@shreyaaithal - Do you know the cause of the error message? 

 Status Message: The provided server type value 'Azure Database for MariaDB - Single Server' is invalid. (Code:InvalidElasticServerType)

**Comment by mumian** [comment]
@shreyaaithal - do you know anything about this error message?

Status Message: The provided server type value 'Azure Database for MariaDB - Single Server' is invalid. (Code:InvalidElasticServerType)

**Comment by mumian** [comment]
Emailed Shreya Aithal, Karla Escobar and Deepthi Prasad

**Comment by mumian** [comment]
According to shreyaaithal, MariaDB will be deprecated by September 19, 2025.

**Pull request closed without merging**
