### PR TITLE
[expressroute-private-peering-vnet] update API versions and add outputs

### PR DESCRIPTION
**Pull request by mumian**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@duongau - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by mumian** [comment]
@duongau - do you know anything about the following error message?


Status Message: Basic IP configuration for ExpressRoute Virtual Network Gateways is not supported. Please create and associate a Standard IP. /subscriptions/0cec7090-2e08-4498-9337-eb96ade50821/resourceGroups/azdo-ce648cde-b086-46d0-b570-90742680ec40/providers/Microsoft.Network/virtualNetworkGateways/er-gw (Code: PublicIpWithBasicSkuNotAllowedOnExpressRouteGateways)

**Comment by duongau** [comment]
@mumian please reach out to @AbdullahBell internally. He will be able to connect you to the ExpressRoute PG regarding this change going forward.

**Comment by azure-quickstarts** [comment]
@duongau - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Pull request merged**
