### PR TITLE
Updated sample to allow minecraft version to be supplied as param on template

### PR DESCRIPTION
**Pull request by DigitalBanana**
### Changelog
* azuredeploy.json - added additional param minecraftServerVersion
azuredeploy.parameters.json - added additional param minecraftServerVersion
* install_minecraft.sh - added command line param (minecraftServerVersion) and reordered $9 and $10

### Description of the change
As minecraft 1.9 is now out and not backwards compatabile with 1.9 updated this template to allow minecraft server version to be supplied as a param (defaulting to 1.9). Some other files changed but these were just whole i had my fork open and both have been reverted (azuredeploy.json temporailry changed .sh file location to my fork, README.md temporarily changed template url to my fork)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DigitalBanana__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@DigitalBanana__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by singhkay** [comment]
@DigitalBanana Thanks for the update, merged! 

cc: @gbowerman

**Comment by gbowerman** [comment]
nice addition, thanks.

**Comment by gbowerman** [comment]
People are reporting errors in the log with the new check-in: 
2016/03/20 22:40:34 --2016-03-20 22:39:30--  https://s3.amazonaws.com/Minecraft.Download/versions/true/minecraft_server.true.jar
2016/03/20 22:40:34 Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.81.147
2016/03/20 22:40:34 Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.81.147|:443... connected.
2016/03/20 22:40:34 HTTP request sent, awaiting response... 403 Forbidden
@DigitalBanana @singhkay can you back this out and investigate?

**Comment by DigitalBanana** [comment]
sure - it looks like some optional params are not being supplied causing the params passed to the sh script to fail - whats the best way to back it out while i investigate?

**Comment by gbowerman** [comment]
Sorry, it looks like your PR is good @DigitalBanana. The deployment error occurred because someone put a space in their world name, so it counted as 2 parameters in the bash script. 

If we make any change it should probably just be to add some warnings about parameter values to the readme..

**Comment by DigitalBanana** [comment]
Hi guy,

Yeah I reordered the params as I guessed that was the case. It would happen now with my latest pull request as all the required params come first.

 Another option could be to change the way the params work in armt by sending unsupplied params as "''" rather than " " as currently....

Cheers

Dave

Sorry, it looks like your PR is good @DigitalBanana<https://github.com/DigitalBanana>. The deployment error occurred because someone put a space in their world name, so it counted as 2 parameters in the bash script.

If we make any change it should probably just be to add some warnings about parameter values to the readme..

-

**Pull request merged**
