### PR TITLE
CustomScript rollout - stage #1

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
cc:  @bmoore-msft @gatneil PTAL
See #2340.

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
@gatneil can you please take a look at test failures, they don't seem pertinent to the changes.

**Comment by gatneil** [comment]
It looks like in some cases we have publisher "Microsoft.Azure.Extension" with type "CustomScript" and in other cases we have publisher "Microsoft.Compute" with type "CustomScriptExtension". Is this on purpose?

**Comment by ahmetalpbalkan** [comment]
@gatneil Microsoft.Compute one is the Windows CustomScript extension. We don't touch that just yet.

We have plans to merge them all in this new extension. Unfortunately the organization names (such as Microsoft.Compute or Microsoft.OSTC) ended up in extension names, the new extension fixes that (see: [Conway's Law](https://en.wikipedia.org/wiki/Conway%27s_law)).

**Comment by gatneil** [comment]
Cool. Otherwise, the PR looks good. You're correct that the CI errors are unrelated to your changes. The azuredeploy.parameters.json files should be updated on 2 of them so they utilize the CI properly, but I can do that in a follow-up PR :)

**Pull request merged**
