### PR TITLE
Blitz

### PR DESCRIPTION
**Pull request by KemBits**
### Changelog
* Added template files for Blitz

### Description of the change
Created/modified template files for inclusion to the BaaS program.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@KemBits__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@KemBits__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by singhkay** [comment]
@KemBits Looks like extension failures. Can you check the VM Instance view when you deploy and fix ?

**Comment by KemBits** [comment]
It looks like it mixed up with the repo I forked from. I'll cancel this pull and redo. :)

**Pull request closed without merging**
