### PR TITLE
DataStax update

### PR DESCRIPTION
**Pull request by benofben**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
Not filling this out a third time.

### Description of the change

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@benofben__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by benofben** [comment]
This is amusing.  I now seem to be stuck in a catch 22 where the template is failing to find the subtemplate.  @singhkay Am I reading the error here correctly?

**Comment by benofben** [comment]
Hi Kay,  I've agreed to the CLA.  What happens next here?

**Comment by azurecla** [comment]
__@benofben__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by singhkay** [comment]
@benofben Thanks for signing the CLA, merged.

**Pull request merged**
