### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ibenbouzid**
Skype for Business lab

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ibenbouzid__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@ibenbouzid__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by ibenbouzid** [comment]
Hi,
Could you please give me an update on this.
Thanks.

**Comment by gatneil** [comment]
I notice you seem to be using // as comments; does this work? I tried this a while back and was given an error that I had invalid json (technically it is invalid according to the strict json standard, but some parsers are lenient on it)

**Comment by ibenbouzid** [comment]
Hi,
Yes it is not recommended it works for however i had some issues. I use it only when i don't want to delete something.  --Imad

      De : Neil Sant Gat <notifications@github.com>
 À : Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com> 
Cc : Imad Benbouzid <imad_benb@yahoo.fr>; Mention <mention@noreply.github.com>
 Envoyé le : Mercredi 1 mars 2017 5h53
 Objet : Re: [Azure/azure-quickstart-templates] Master (#2983)
   
I notice you seem to be using // as comments; does this work? I tried this a while back and was given an error that I had invalid json (technically it is invalid according to the strict json standard, but some parsers are lenient on it)—

**Comment by bmoore-msft** [comment]
Closing due to missing files

**Pull request closed without merging**
