### PR TITLE
Remove BlockApps Strato Quickstart Template 

### PR DESCRIPTION
**Pull request by ililic**
We've cleared the Azure Marketplace - the Quickstart template should be removed: https://azure.microsoft.com/en-us/marketplace/partners/consensys/blockapps-strato/

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ililic__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by ililic** [comment]
@singhkay - If I'm removing a template is there a different procedure?

**Comment by singhkay** [comment]
@ililic Is there a reason to not have it here? For users who want to view the source and not have to go to marketplace/portal?

**Comment by ililic** [comment]
@singhkay: The quickstart template was an initial step @marleyg requested until we were on the Azure Marketplace. 

The Strato VM contains a proprietary/closed source components (our RESTFUL API, for example) that we want to be able to license / monetize rather than have a free 1click deployment. 

I will work with the team and @ryanreich to replace this quickstart with one containing our open source components. In the interim we'd like Strato to be a marketplace-only deployment.

**Comment by singhkay** [comment]
@ililic Alright makes sense, merging.

**Comment by ililic** [comment]
Ty @singhkay - will prioritize Getting EthereumH open source components up. Looking forward to adding a few more quickstarts.

**Comment by singhkay** [comment]
@ililic Awesome!

**Pull request merged**
