### PR TITLE
[Do not merge] New template to create default Key Vault

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- New template that creates a Key Vault with default settings and doesn't include keys, secrets, or certificates.
- Deploys a key vault with same settings as a [default key vault](https://docs.microsoft.com/azure/key-vault/general/quick-create-portal) created on Azure portal.
- Quickstart article is in progress and will publish after the template is live.

### CODE REVIEW

**Comment by davidsmatlak** [comment]
I'll continue to troubleshoot the template build errors next week.

**Comment by davidsmatlak** [comment]
Updated the template and parameter file and the build was successful.

**Comment by davidsmatlak** [comment]
@mumian The new key vault template is ready to merge. I'll finish the quickstart article this week and publish after the template is live.

**Comment by davidsmatlak** [comment]
Updated the README.md file and pushed the update.

**Comment by davidsmatlak** [comment]
Made one additional change to _README.md_ and pushed the change.

**Comment by bmoore-msft** [comment]
@davidsmatlak - this sample seems more or less identical to the existing 101 key vault sample, what's the differentiation we're trying to show here?

**Comment by mumian** [comment]
@bmoore-msft - This is a part of the ARM horizontal project.  We are creating a quickstart article for each of the Azure services to cover the most basic configuration.  Each quickstart article deploys a quickstart template.  The current Key Vault document are broken into 3 areas - key vault only, key vault secret, and key vault key.  This new template is for the key vault only quickstart article.

**Comment by davidsmatlak** [comment]
Thanks @mumian and @bmoore-msft. This template creates a Key Vault with default settings the same as a [default key vault](https://docs.microsoft.com/azure/key-vault/general/quick-create-portal) created on Azure portal. The development of the quickstart article for this template is in progress.

**Comment by bmoore-msft** [comment]
Ok, that makes sense... it's probably worth a quick sync offline to make sure we're aligned on what we want to do for the "ARM Horizontal Project"  (which is new to me)

**Comment by davidsmatlak** [comment]
Closing as **Do not merge**.

**Pull request closed without merging**
