### PR TITLE
 Added DLWorkspace cluster deployment template

### PR DESCRIPTION
**Pull request by PhDN**
## DLWorkspace Overview

Deep Learning Workspace (DLWorkspace) is an open source toolkit that allows AI scientists to spin up an AI cluster in turn-key fashion. This template will spin up a DLWorkspace cluster in Azure. Once setup, the DLWorkspace cluster in Azure provides web UI and/or restful API that allows AI scientist to run job (interactive exploration, training, inferencing, data analystics) on the cluster with resource allocated by DL Workspace cluster for each job (e.g., a single node job with a couple of GPUs with GPU Direct connection, or a distributed job with multiple GPUs per node). DLWorkspace also provides unified job template and operating environment that allows AI scientists to easily share their job and setting among themselves and with outside community. DLWorkspace out-of-box supports all major deep learning toolkits (TensorFlow, CNTK, Caffe, MxNet, etc..).

For more information about the DLWorkspace toolkit, visit https://github.com/Microsoft/DLWorkspace/tree/master

### CODE REVIEW

**Comment by PhDN** [comment]
A note on 'azuredeploy.json' template: The template does work properly even though it does not pass the ARM template validation tool. Instead of having 'sourceAddressPrefix' in the Security Rules section, we have 'sourceAddressPrefixes' in order to recieve an array of input values.

**Comment by bmoore-msft** [comment]
The reason why CI is failing is because your parameter file has some invalid values for the template, let's get those cleaned up and the other CI errors as well...

**Comment by bmoore-msft** [comment]
I'm not able to deploy the template manually either - same error that CI is getting.  We need to figure out how to deploy as it's likely customers will run into the same failures.

**Comment by PhDN** [comment]
Is it possible to have you @bmoore-msft contact either Jin Li <Li.Jin@microsoft>, or Sanjeev Mehrotra <sanjeevm@microsoft.com> to discuss potential solutions to this issue? Both Jin Li and Sanjeev Mehrotra are members of the Cloud Computing and Storage team at MSR who are still actively working on the deployment of the DLWorkspace project onto Azure.

**Comment by bmoore-msft** [comment]
email sent

**Comment by bmoore-msft** [comment]
closed per email conversation

**Pull request closed without merging**
