### PR TITLE
Update DevTest Labs metadata to contain specific keywords for discoverability

### PR DESCRIPTION
**Pull request by ryanvog**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ryanvog__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ryanvog). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@ryanvog I see you added a ci_skip files to all the templates. Are all of these templates not able to be tested by the CI?

**Comment by ryanvog** [comment]
There are resources required to exist for our templates to be deployable (i.e. lab ID, etc).  Ideally, we would have a mocking framework to accomplish this, but to date, without it, our templates won't pass the CI.

**Comment by singhkay** [comment]
@ryanvog Let's figure out something offline. This is merged.

**Pull request merged**
