### PR TITLE
Add sample: Front Door Premium (Preview) with Azure Functions origin and Private Link

### PR DESCRIPTION
**Pull request by johndowns**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Add sample - Front Door Premium (Preview) with Azure Functions origin and Private Link

### CODE REVIEW

**Comment by johndowns** [comment]
Note that the ARM TTK is warning about the location parameter being hard-coded. This is intentional because during its preview, [Front Door restricts the regions that can be used for Private Link origins](https://docs.microsoft.com/en-us/azure/frontdoor/standard-premium/concept-private-link#limitations). Once this restriction is removed I plan to submit an update to this sample.

**Comment by bmoore-msft** [comment]
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by bmoore-msft** [comment]
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by bmoore-msft** [comment]
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Pull request merged**
