### PR TITLE
viptokens-ubuntu-vm

### PR DESCRIPTION
**Pull request by viptokens**
--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------

Thank you for deciding to contribute to this repository, we're thrilled to have you contribute a template or a fix! :tada: Before we proceed, please be sure to review the contribution guidelines that will make the review process go smoother.
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

We've created an outline of recommended sections to fill out that will help make this Pull Request awesome!

--------------------MESSAGE FROM ADMIN, DELETE BEFORE SUBMITTING----------------------
CLA succesfully signed

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@viptokens__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by viptokens** [comment]
http://viptokens.club

**Comment by gatneil** [comment]
Sorry for the delay; is this still something we want to merge in?

**Comment by gatneil** [comment]
No response; closing

**Pull request closed without merging**
