### PR TITLE
scripts for couchbase-on-ubuntu updated with corrections to storage location use, deployment steps and additional jumpbox options.

### PR DESCRIPTION
**Pull request by cihanb**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
* Added options for jumpbox deployment
* Corrected Couchbase Server provisioning for 4.1
* Corrected storage location during cluster provisioning
* additional enhancements to variable naming and README

### Description of the change

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@cihanb__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by cihanb** [comment]
Corrected with comments from the previous pull: https://github.com/Azure/azure-quickstart-templates/pull/2028

**Comment by singhkay** [comment]
@cihanb lgtm, one minor nit. Can you organize the files like shown here? https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/namingConvention.png

**Comment by cihanb** [comment]
done restructuring files.

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
