### PR TITLE
Release: BitShares on Azure BaaS

### PR DESCRIPTION
**Pull request by ryanRfox**
### Changelog
* Confirm desire to keep Ubuntu 15.10
* Change API version
* Change typeHandlerVersion from 1.2 to 1.4 here
* Add the autoUpgradeMinorVersion property
* Chagne storageAccountName per recommendation

### Description of the change
Fixing up the template parameters and syntax to ensure proper initial submission.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ryanRfox__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@ryanRfox Does the extension run for you? I tried deploying this manually and the extension fails to run. From the VM instance view, I'm seeing

```
"extensionHandlers": [
      {
        "type": "Microsoft.OSTCExtensions.CustomScriptForLinux",
        "typeHandlerVersion": "1.4.1.0",
        "status": {
          "code": "ProvisioningState/NotReady",
          "level": "Info",
          "displayStatus": "Not Ready",
          "message": "(000003)Invalid status/status: failed"
        }
      }
    ]
```

If I look in the agent logs, I see
```
2016/03/09 20:32:09 CustomScript started to handle.
2016/03/09 20:32:09 [CustomScript-0.0]cwd is /var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.4.1.0
2016/03/09 20:32:09 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.0]Change log file to /var/log/azure/Microsoft.OSTCExtensions.CustomScriptForLinux/1.4.1.0/extension.log
2016/03/09 20:32:38.326135 ERROR Failed to decode json event file: Expecting value: line 1 column 1 (char 0)
```

When I tried to run the script on an Ubuntu 15.10 install
`kay@ubuntu:~$ sudo sh /home/kay/Documents/build_bitshares.sh From_PPA`

I get
```
W: Failed to fetch cdrom://Ubuntu 15.10 _Wily Werewolf_ - Release amd64 (20151021)/dists/wily/restricted/binary-amd64/Packages  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs

W: Failed to fetch cdrom://Ubuntu 15.10 _Wily Werewolf_ - Release amd64 (20151021)/dists/wily/main/binary-i386/Packages  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs

W: Failed to fetch cdrom://Ubuntu 15.10 _Wily Werewolf_ - Release amd64 (20151021)/dists/wily/restricted/binary-i386/Packages  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs

E: Some index files failed to download. They have been ignored, or old ones used instead.
Command exited with non-zero status 100
2.25user 0.45system 0:09.03elapsed 29%CPU (0avgtext+0avgdata 6552maxresident)k
16280inputs+325064outputs (19major+4955minor)pagefaults 0swaps
```

**Comment by ryanRfox** [comment]
Good morning,

I am not able to test this script directly, as it references the /Azure/master branch.  However, my /ryanRfox/review branch 'should be' a clone thereof with the referencing URLs modified.


I've pushed a small update which removes the installation of the swapfile, but that appears to come long after the published error would be presented.  It's as if the VM is unable to locate the Linux installation media.  This I have never seen before.


Thoughts on how to troubleshoot further?

Best,

Fox


________________________________

**Comment by singhkay** [comment]
@ryanRfox Looks like that update made the deployment gods happy! merging

**Pull request merged**
