### PR TITLE
Update ARM templates for Splunk deployment

### PR DESCRIPTION
**Pull request by rarsan**
### Changelog
* Update templates to use custom marketplace image 'splunk-enterprise-base-image'
* Update to latest Splunk version 6.4.0
* Remove use of reference() for fast fail
* Update CustomScriptForLinux extension to version 1.5

### Description of the change
Minor release with updated VM base image and Splunk Enterprise version.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rarsan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by rarsan** [comment]
Can one of the maintainers take a look at why travis is failing? It seems it cannot find the nested templates. The validation step works fine in my environment.

**Comment by singhkay** [comment]
@sedouard Here's the latest example of this https://travis-ci.org/Azure/azure-quickstart-templates/builds/131570063#L227

**Comment by rarsan** [comment]
@singhkay , @sedouard 
Aren't the nested template links supposed to be converted to point to the fork at CI run-time?

**Comment by sedouard** [comment]
@rarsan can you update your branch and push. there's some diagnostics i merged into master i'd like to try on your pr.

The problem is that our CI server isn't getting the `TRAVIS_COMMIT_RANGE` variable in this PR. As a result it can't relink your `raw.githubusercontent.com` links to point to your fork since it doesn't know what PR the template comes from.

**Comment by rarsan** [comment]
I just updated this PR. Thanks for taking a look.

**Comment by sedouard** [comment]
Cool. I found out the issue and merged the fix in #1997. #1998 is a copy of this PR and I confirm it doesn't get hung up on the template linking issue.

However the error in the #1998 run has something to do with accepting the market place terms & conditions. Which I can't really do anything about.

@singhkay check it out https://travis-ci.org/Azure/azure-quickstart-templates/builds/132416559.

I think you need to do something on the test subscription but I'm not really sure what button's/nobs that need to be hit.

**Comment by rarsan** [comment]
Thanks @sedouard 
This is probably happening because it's using a marketplace vm image as a base image.
It was told that to accept the legal terms, the template needs to be created (only once) from the UI portal for the first-time via either of these 2 links:

* https://azure.microsoft.com/en-us/marketplace/partners/splunk/splunk-enterprisebyol/
* https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Frarsan%2Fazure-quickstart-templates%2Fmaster%2Fsplunk-on-ubuntu%2Fazuredeploy.json

Do you have access to the test subscription to kick that off?

**Comment by sedouard** [comment]
@rarsan done. 🍻

**Comment by rarsan** [comment]
Nice work @sedouard . Thanks!

**Comment by rarsan** [comment]
Is anything else required for this PR? TIA.

**Comment by singhkay** [comment]
@rarsan lgtm, merged

**Pull request merged**
