### PR TITLE
Migrate bicep example: 201/servicebus-create-queue (IGNORE BEST PRACTICE FAILURES)

### PR DESCRIPTION
**Pull request by StephenWeatherford**
Added bicep support to this sample by integrating bicep.main from the example in https://github.com/Azure/bicep/tree/main/docs/examples/201/servicebus-create-queue

The corresponding PR for the modified bicep example is here: https://github.com/Azure/bicep/pull/3317

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@spelluru - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@spelluru - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@spelluru - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@spelluru - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@spelluru - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@spelluru - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by StephenWeatherford** [comment]
@bmoore-msft the BP violations are unavoidable due to us-gov apiversion requirements:

   [-] apiVersions Should Be Recent (119 ms) 
##[error]        Api versions must be the latest or under 2 years old (730 days) - API version 2017-04-01 of Microsoft.ServiceBus/namespaces is 1581 days old
        Valid Api Versions:
        2021-01-01-preview

##[error]        Api versions must be the latest or under 2 years old (730 days) - API version 2017-04-01 of Microsoft.ServiceBus/namespaces/queues is 1581 days old
        Valid Api Versions:
        2021-01-01-preview

**Pull request merged**
