### PR TITLE
Updated ARM Template for Linux VM

### PR DESCRIPTION
**Pull request by dheerajd-msys**
Updated Ubuntu ARM template, so as to deploy either Ubuntu/Centos VM

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dheerajd-msys__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@dheerajd-msys__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@dheerajd-msys Can you sign the CLA?

**Comment by azurecla** [comment]
__@dheerajd-msys__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by dheerajd-msys** [comment]
Hi @singhkay,

Thanks for reviewing the PR. I have signed the CLA
Had a couple of queries:-
1. How can we proceed with acomghbot mentioning errors related to chef-json-parameters-ubuntu-vm folder which we have removed.
2. Regarding travis failure, i just see "Failed'.\nCannot read property 'forEach' of undefined" error.
Any suggestions which might help me in pinpointing the actual error.

**Comment by singhkay** [comment]
@dheerajd-msys This probably won't pass the CI since this needs a Chef server to be setup and the key, recipe to run succesfully. CI can't do those things atm. Can you validate this on your end?

**Comment by dheerajd-msys** [comment]
Hi @singhkay,

I have validated the template at my end, it is working properly and vm(node) does gets registered to chef server.
Let me know if anything else is required to be done from my side.

**Comment by singhkay** [comment]
@dheerajd-msys Thanks for the validation, merged!

**Pull request merged**
