### PR TITLE
Location fix

### PR DESCRIPTION
**Pull request by marcvaneijk**
Changed resource location from parameter to resourceGroup().location.
Deleted location parameter from deployment template, nested templates
and parameter file.

### CODE REVIEW

**Comment by singhkay** [comment]
@netwmr01 Can you review this change and see if you need to have a different location for resources than the resource group in your template?

**Comment by netwmr01** [comment]
we don't need to have different resources in different location as the parent resources group. That being said, why the change and why now?

**Comment by singhkay** [comment]
@netwmr01 We recently created a "Best Practices" guide for templates https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

Now we're trying to make the existing templates consistent with those so that any future templates that start off from existing templates at least have a base of "best practices" in place.

**Comment by netwmr01** [comment]
@singhkay did this change pass the Travis CI build?

**Comment by singhkay** [comment]
@marcvaneijk Can you test this out locally?

**Pull request merged**
