### PR TITLE
Install and configure mesos-dns on masters and agents

### PR DESCRIPTION
**Pull request by artemharutyunyan**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@artemharutyunyan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by anhowe** [comment]
If the master was an agent, the /etc/resolv.conf will be overwritten.  Is that ok?

**Comment by anhowe** [comment]
for the zk config don't you want to use: zk://10.0.0.5:2181,10.0.0.6:2181,10.0.0.7:2181/mesos with all ip addresses.  If so replace that with $zkmesosconfig

**Comment by artemharutyunyan** [comment]
We've established that the patch will not be actually rewriting resolv.conf, but will be amending it, as for the zk configuration, it's safer for the time being to just set it to 127.0.0.1, because if something is wrong with the box and the zk is not functioning on it we'd rather see mesos-dns fail too.

**Comment by azurecla** [comment]
__@artemharutyunyan__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Pull request merged**
