### PR TITLE
Creating a fast budget template

### PR DESCRIPTION
**Pull request by HamzaBoukraa**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog
* Creating a fast budget template

### CODE REVIEW

**Comment by HamzaBoukraa** [comment]
@bmoore-msft Hello Brian, Do you have an idea please how to fix the authorization issue in this build ?
https://dev.azure.com/azurequickstarts/azure-quickstart-templates/_build/results?buildId=29024&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=7bf03a3b-69d5-5660-244f-21e634d6903f

Thanks in advance.

**Comment by bmoore-msft** [comment]
What permissions does a user need to be able to deploy this template?  It looks like they need to be a contributor at subscription scope.  If so, then you'll need to document in the readme and set the flag for manual validation in metadata.json

**Comment by bmoore-msft** [comment]
@HamzaBoukraa - this fails to deploy in AzureGov - is it supported there?  (if not we need to update metadata.json and the readme)

**Comment by bmoore-msft** [comment]
@HamzaBoukraa - ping...

**Comment by bmoore-msft** [comment]
Closing abandoned request - please reopen if you can address the feedback.

**Pull request closed without merging**
