### PR TITLE
Adding Deploy to Azure Gov link.

### PR DESCRIPTION
**Pull request by sdubeymsft**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

*
*
*

### CODE REVIEW

**Comment by sdubeymsft** [comment]
@dougbrad - Please review my changes for adding Deploy to Azure Gov link.

**Comment by bmoore-msft** [comment]
@sdubeymsft - I'm unable to deploy this to FF, correlationId is: 8f36fca9-786c-449f-8483-a474dafc906f if you want to have a look.

**Comment by KenMAG** [comment]
I have a solution to this that is working. I would like to contribute.

**Comment by KenMAG** [comment]
I should clarify. My solution is tested with RHEL 7.4. I had an agent/OS version issue with Ubuntu 18.04. All I did was add a domain parameter. 
**"domain": {
            "type": "string"
        }**
and
"settings": {

                    "workspaceId": "[parameters('workspaceId')]",

                    **"domain": "[parameters('domain')]"**

                    },

**Comment by bmoore-msft** [comment]
@sdubeymsft - I still get the same error about pricing tier...

**Comment by bmoore-msft** [comment]
Closing abandoned request - please reopen if you can address the feedback.

**Pull request closed without merging**
