### PR TITLE
Fix deployment on 101-data-lake-store-encryption-key-vault

### PR DESCRIPTION
**Pull request by MCKLMT**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Fix deployment

### CODE REVIEW

**Comment by MCKLMT** [comment]
@bmoore-msft This template needs manual validation.

**Comment by bmoore-msft** [comment]
I think it can be automated, we just need to create the vault in the prereqs instead of use the existing one... by creating the vault, the SP will be able to add an accessPolicy to it...

**Comment by bmoore-msft** [comment]
@MCKLMT - this looks good, what do you think about creating a module for this "encryption key" scenario?

**Comment by MCKLMT** [comment]
> @MCKLMT - this looks good, what do you think about creating a module for this "encryption key" scenario?

Sure, I can if you guide me a little. 😇😅

**Comment by bmoore-msft** [comment]
Take the prereq template you have and work it into one of these...  https://github.com/Azure/azure-quickstart-templates/tree/master/modules

Hand wavy I know, but does it help?

**Pull request merged**
