### PR TITLE
Azure RM templates for Azure DTL (Lab VM template from VHD or Azure marketplace image).

### PR DESCRIPTION
**Pull request by mithunshanbhag**
Change Description:

1. Renaming the "201-dtl-create-vmtemplate" to "201-dtl-create-vmtemplate-from-vm" based on user feedback. 

2. New Azure RM template for converting an existing lab VHD to a lab VM template (201-dtl-create-vmtemplate-from-vhd) . 

3. New Azure RM template for converting an existing azure marketplace image to a lab VM template (201-dtl-create-vmtemplate-from-azure-image) . 

4. Accordingly the helper cmdlets have been updated.

### CODE REVIEW

**Comment by mithunshanbhag** [comment]
Here is the why the checks are failing..... 

We supply bogus/fake values in the azuredeploy.parameters.json.

Our templates need the names of existing Azure resources for the deployment to succeed.

What is the recommendation to work around this issue? How does one supply mock values in the parameters file?

**Comment by sedouard** [comment]
@mithunshanbhag templates requiring pre-existing resources cannot be validated since CI runs assume you are starting from nothing. the most we've been able to do is storing a required vhd in the CI storage account for future CI runs.

To bypass CI runs for a template folder place a file called `.ci_skip` in the root of the folder.

**Comment by mithunshanbhag** [comment]
@sedouard Done. Thanks for the tip!

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
