### PR TITLE
Fixed incorrect URLs, default values and apiVersion

### PR DESCRIPTION
**Pull request by jmaza**
### Changelog
* Fixed incorrect type for defaultValue in 'sqlStorageDisksCount' parameter
* 'sqlStorageWorkloadType' defaultValue was not an allowedValue and was producing an error
* apiVersion in deployments resource was invalid
* fixed URLs for templates

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jmaza__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@jmaza Thanks for fixing these! Looks like there's one more fix needed before this can be run successfully. Can you take a look? https://travis-ci.org/Azure/azure-quickstart-templates/builds/131469944#L225

**Comment by jmaza** [comment]
@singhkay You're welcome! These templates have been useful for me. I fixed the 'long computer name' issue and now it seems like everything is fine; but for some reason I'm getting: 'AssertionError: Template Validiation Failed'. Could this be something external?

**Comment by singhkay** [comment]
@jmaza Yep, looks like @weidaiMS might need to look at the error

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
