### PR TITLE
created data factory copy with stored procedure template

### PR DESCRIPTION
**Pull request by sharonlo101**
### Contributing guide

https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md
### Changelog

*
*
*
*
*

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sharonlo101__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by sharonlo101** [comment]
Didn't have my github appropriately linked with Microsoft set-up but now it is. Not sure how to re-run azurecla to change the flag.

**Comment by gatneil** [comment]
Sorry for the delay; you want to close, then re-open the PR. That should make it recognize your new linked credentials. Unfortunately there are merge conflicts now, though, so those need to be addressed

**Comment by gatneil** [comment]
No activity; closing

**Pull request closed without merging**
