### PR TITLE
Fix parse port mapping

### PR DESCRIPTION
**Pull request by micheljung**
### Changelog
* Fixed port mapping in docker-parse

### Description of the change
Port mapping was 8080->80 but should be 80->8080 (host->container)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@micheljung__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@felixrieseberg Can you review this change?

**Comment by felixrieseberg** [comment]
👍  LGTM

**Comment by singhkay** [comment]
Thanks @felixrieseberg! merged

**Pull request merged**
