### PR TITLE
github-enterprise: Update supported regions, description, and NSG

### PR DESCRIPTION
**Pull request by gnawhleinad**
Updating the list of supported regions that have premium storage.

Fixes https://github.com/Azure/azure-quickstart-templates/issues/1304. Closes https://github.com/Azure/azure-quickstart-templates/pull/1308 (merged).

/ref: https://help.github.com/enterprise/2.5/admin/guides/installation/installing-github-enterprise-on-azure/, https://azure.microsoft.com/en-us/regions/#services

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gnawhleinad__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@gnawhleinad Please see how to make your template run succesfully through our CI https://github.com/Azure/azure-quickstart-templates/tree/master/1-CONTRIBUTION-GUIDE#travis-ci

**Comment by gnawhleinad** [comment]
Not sure I understand the error message:

>     "error": "Deployment provisioning state was not successful\n####data is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only.\n",

It also outputs:

>             "newStorageAccountName": {
                "value": "ci798198b8107d6dba"
            },

which is 18 characters with only numbers and lower-case letters.

I was also able to locally run:

```bash
$ azure group template validate --resource-group hodor --template-file github-enterprise/azuredeploy.json --parameters-file github-enterprise/azuredeploy.parameters.json
info:    Executing command group template validate
+ Initializing template configurations and parameters                          
+ Validating the template                                                      
info:    group template validate command OK
```

**Comment by singhkay** [comment]
It's better to just eliminate the storage account. See #944. Also see #966 for dns prefix parameter.

**Comment by gnawhleinad** [comment]
> It's better to just eliminate the storage account.

https://github.com/gnawhleinad/azure-quickstart-templates/commit/b94235c899a5a5b90c8724552bb37f3e1b379417 didn't have the storage account but it still failed the test.

**Comment by singhkay** [comment]
@gnawhleinad Not sure what you mean but there is a storage account that is being created https://github.com/gnawhleinad/azure-quickstart-templates/blob/patch-1/github-enterprise/azuredeploy.json#L105

Also looking at this closer, I see why it failed. You have a parameter accountPrefix that has a value "####"  and is used for a lot of variables 
https://github.com/gnawhleinad/azure-quickstart-templates/blob/patch-1/github-enterprise/azuredeploy.parameters.json#L5

**Comment by singhkay** [comment]
@gnawhleinad Also see this https://github.com/Azure/azure-quickstart-templates/issues/1304

**Comment by singhkay** [comment]
@gnawhleinad Here's another PR that is submitted by @LeCampusAzure. Can you merge these changes as well otherwise one of these will run into a merge conflict

**Comment by gnawhleinad** [comment]
> Can you merge these changes as well otherwise one of these will run into a merge conflict

:+1:!

**Comment by singhkay** [comment]
@gnawhleinad Awesome! Btw don't forget to change the date in the metadata file. Will help show up the github template on top of https://azure.microsoft.com/en-us/documentation/templates

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
