### PR TITLE
WIP:  Significant performance enhancements to chef-ha-cluster

### PR DESCRIPTION
**Pull request by irvingpop**
### Contributing guide

https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md
### Changelog
-  Tune the default instance sizes to better suit the load profile of chef HA
-  Leverage local SSD to enhance performance of both frontends and backends
-  Apply recommended performance tuning settings for both chef-backend and chef-server-core
-  These settings have been validated using load-testing tools

### Description of the change

These settings significantly enhance the performance and capacity of chef-ha.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@irvingpop__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by gatneil** [comment]
Is this still WIP?

**Comment by irvingpop** [comment]
Yes - unfortunately we're still pending package updates from two Chef packages before I'd recommend this to folks.   

@N6UDP and I were also discussing some way to make the ephemeral stores durable, but I'd like to propose that push that to future work.

Finally, I got a suggestion from Stuart Preston to use Key Vault instead of another blob store - but that is also out of scope for this PR.

**Comment by gatneil** [comment]
Ok cool. I'm adding the "awaiting reponse from author" flag; leave a comment on here to let me know when it's ready :)

**Comment by gatneil** [comment]
Still WIP?

**Comment by irvingpop** [comment]
@gatneil Yes, but just a few days longer!   We finally released the chef-backend 1.2.x packages to stable so I just need to update this PR, test and then rebase.

**Comment by gatneil** [comment]
Cool; just wanted to check in :)

**Comment by irvingpop** [comment]
Thanks for your patience @gatneil this is rebased, retested and ready for merge

**Comment by gatneil** [comment]
Thanks for the contribution! :)

**Pull request merged**
