### PR TITLE
Updates ARM template files - Batch

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

This pull request replaces Azure/azure-quickstart-templates#8187

- Updates template used in ARM template [quickstart](https://docs.microsoft.com/azure/batch/quick-create-template) article.
- Adds quickstart article's author to `docOwner` and fixes a typo in _metadata.json_.
- Updates _README.md_ with link to the quickstart article and **Deploy to Azure Gov** button.
- Fixes existing links for deploy button and visualize button that caused build errors because links are case-sensitive.
- Updates resource `type` to the latest `apiVersion`.
- Fixes indentation.

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@JnHs - check this PR for updates that may be needed to documentation that references this sample.

**Review by JnHs — APPROVED** [review]

**Comment by bmoore-msft** [comment]
@JnHs - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
Submitting some additional changes to fix build errors for the _README_ deploy buttons. Logs show errors that URI are case-sensitive.

**Comment by bmoore-msft** [comment]
@JnHs - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@JnHs - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
Resolved all the build errors.

**Pull request merged**
