### PR TITLE
Updates ARM template files - Event Hubs

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template used in ARM template [quickstart](https://docs.microsoft.com/azure/event-hubs/event-hubs-resource-manager-namespace-event-hub) article.
- Adds quickstart article's author to `docOwner` in _metadata.json_.
- Updates title for the quickstart article's link in _README.md_.
- Fixes template property order based on best practices guidance.

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@spelluru - check this PR for updates that may be needed to documentation that references this sample.

**Comment by spelluru** [comment]
@bmoore-msft - Thank you. will do.

**Comment by bmoore-msft** [comment]
@spelluru - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@spelluru - check this PR for updates that may be needed to documentation that references this sample.

**Pull request merged**
