### PR TITLE
Upgrading Moodle templates to latest version of Moodle

### PR DESCRIPTION
**Pull request by vinhub**
Also bringing the templates up to latest recommendations.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vinhub__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
lgtm, will wait for CI to complete before merging

**Comment by vinhub** [comment]
@singhkay Looks like CI failed due to timeout. Is there a way for me to find out what might have gone wrong? The error simply says "The job exceeded the maxmimum time limit for jobs, and has been terminated."

**Comment by singhkay** [comment]
@vinhub Looks like it failes because the app is getting deployed on Standard_A0. Try changing that to a faster VM.

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
