### PR TITLE
secure-virtual-wan quickstart

### PR DESCRIPTION
**Pull request by RyanLWilliams**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Added Secure Wan Quickstart.

### CODE REVIEW

**Comment by RyanLWilliams** [comment]
Deployment fails after removing default values for template as requested. Also has best practice violations for Found hardcoded reference to login.microsoftonline.com which is required for P2S Configuration

**Comment by bmoore-msft** [comment]
When you remove the defaultValues, you need to add values in the parameter file to supply the value.

Use the environment() function to get the login endpoint.

**Comment by RyanLWilliams** [comment]
Hi @bmoore-msft , I have resolved all remaining issues, can this be approved?

**Comment by RyanLWilliams** [comment]
Closing this due to no response

**Pull request closed without merging**
