### PR TITLE
Update metadata.json

### PR DESCRIPTION
**Pull request by dwaiba**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
* Updated metadata.json with right text
*
*
*
*

### CODE REVIEW

**Comment by dwaiba** [comment]
@singhkay Requesting Merge for proper Name change via  #2094

**Comment by singhkay** [comment]
@dwaiba The intent of the folder name doesn't match the itemDisplayName anymore. I suggest changing the folder name as well or splitting the added functionality over dynamic data disks into another template.

**Comment by dwaiba** [comment]
@singhray  I will change the folder name to something more meaningful.

**Comment by singhkay** [comment]
@dwaiba Any update on this?

**Comment by dwaiba** [comment]
@singhkay striped disks is MDADM RAID0. Will like to leave meta-data as such. Users can enjoy the extra goodies as is intended . Closing this for now.

**Pull request closed without merging**
