### PR TITLE
Update API version on 101-aci-dynamicsnav

### PR DESCRIPTION
**Pull request by MCKLMT**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Update API version
* Minor fixes

### CODE REVIEW

**Comment by MCKLMT** [comment]
I removed US Gov support on this template because ACI resources are not available. 🤷🏻‍♂️

**Comment by bmoore-msft** [comment]
@MCKLMT - Which resource is missing?  Microsoft.ContainerInstance/containerGroups is deployed to Azure Gov...

**Comment by MCKLMT** [comment]
I receive an error message saying there is no more resources available in US Gov.

**Comment by bmoore-msft** [comment]
ok, can you try deploying in usgovarizona?  If it's technically supported, but failing, that probably the correct way to "badge" it... so it is what it is in that case...

**Comment by MCKLMT** [comment]
``` Status Message: The requested resource is not available in the location 'usgovarizona' at this moment. Please retry with a different resource request or in another location. Resource requested: '2' CPU '2' GB memory 'Windows Server 2016 - Before 2B' OS (Code:ServiceUnavailable)```

Any idea?

**Comment by bmoore-msft** [comment]
not off the top but that's fine - it's reporting accurately...  Can ping container support if you have time to track it down.

**Pull request merged**
