### PR TITLE
Adding SQL FCI Zone Aware Template

### PR DESCRIPTION
**Pull request by albertwo1978**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

*
*
*

### CODE REVIEW

**Comment by bmoore-msft** [comment]
why are we skipping CI?

**Comment by albertwo1978** [comment]
SQL FCI has a prereq for Windows Server Active Directory (which is not deployed in the template). Looking at a few of the other examples, it seemed .ci_skip was included.

If it’s not, happy to remove and resubmit Pull.

**Comment by albertwo1978** [comment]
Added verbiage to explain that an existing VNET and Domain are required. Also have link to Zone aware template in the Readme.

**Comment by bmoore-msft** [comment]
If it's just AD can we add the prereqs per: https://github.com/Azure/azure-quickstart-templates#template-pre-requisites

**Comment by bmoore-msft** [comment]
Closing abandoned request - please reopen if you can address the feedback.

**Pull request closed without merging**
