### PR TITLE
update api-version, add bicep support

### PR DESCRIPTION
**Pull request by markjbrown**
## Changelog

* update api-version
* add bicep support

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@SnehaGunda - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by azure-quickstarts** [comment]
@SnehaGunda - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by markjbrown** [comment]
@bmoore-msft Hey Brian. Do you know why I get this error message from the bicep test? Looks like all my PR's failed with this error.

The api-version I used is fully available for templates, SDKs, etc.

**Comment by bmoore-msft** [comment]
@StephenWeatherford was looking into this... it's a warning show it shouldn't fail the task, though I'm not 100% on which bits to flip so that we fail on errors and not warnings.

**Comment by StephenWeatherford** [comment]
@bmoore-msft @markjbrown Yes, they are valid apiVersions, but the bicep tools don't have type info about them yet.  Therefore you will not get full validation and intellisense for them.  Thus the experience for customers is degraded when editing.

Seems like it should be best practice to use versions that the bicep tools know about.  Thoughts?

The most recent that the bicep tools currently have knowledge of is 2021-03-15.
image

**Comment by StephenWeatherford** [comment]
For example, if I mistype the "kind" property with the current code, there is no error:
image

If I go back to a known version, I now see the error:
image

**Comment by bmoore-msft** [comment]
I don't think we should restrict the versions users can submit - as long as the template deploys successfully.

The action for us is to not fail the task when only a warning is written in the console.

**Comment by azure-quickstarts** [comment]
@SnehaGunda - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by azure-quickstarts** [comment]
@SnehaGunda - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by azure-quickstarts** [comment]
@SnehaGunda - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by markjbrown** [comment]
Hey @bmoore-msft and @StephenWeatherford is there something else you need me to do on this PR? I can't quite tell if there is an action for me.

Thanks.

**Comment by StephenWeatherford** [comment]
@markjbrown Not at the moment, I believe I've fixed the pipeilne issue, am re-running.

**Comment by azure-quickstarts** [comment]
@StephenWeatherford Test: SnehaGunda - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by azure-quickstarts** [comment]
@SnehaGunda - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by StephenWeatherford** [comment]
@bmoore-msft The bicep warnings no longer cause build failure.  The missing bicep badge can wait - they won't work until we switch to the bicep pipeline and I'm going to have to get those added en masse afterwards anyway.

**Comment by azure-quickstarts** [comment]
@StephenWeatherford (IGNORE THIS DUPLICATE COMMENT - TESTING): SnehaGunda - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in the metadata.]

**Comment by azure-quickstarts** [comment]
@SnehaGunda - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by azure-quickstarts** [comment]
@StephenWeatherford (IGNORE THIS DUPLICATE COMMENT - TESTING): SnehaGunda - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in the metadata.]

**Comment by azure-quickstarts** [comment]
@SnehaGunda - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by markjbrown** [comment]
@StephenWeatherford where does the metadata for these automated docs references come from?

Thanks.

**Comment by StephenWeatherford** [comment]
metadata.json

**Pull request merged**
