### PR TITLE
docker-swarm-cluster-simple: README fixes

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
@rgardler please review in the rich diff mode.

image

No need to set `DOCKER_TLS_VERIFY=` it's already empty by default.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ahmetalpbalkan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ahmetb). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rgardler** [comment]
@ahmetalpbalkan If DOCKER_TLS_VERIFY has been set previously for connection to a different connection it is not blank by default. Therefore it is safer to include it in the instructions, it hurts no-one to run an unnecessary command but can cause confusion if not documented

**Comment by ahmetalpbalkan** [comment]
@rgardler I prefer --tls=false in that case. A residue in env is probably PEBKAC. :-)

**Comment by rgardler** [comment]
@ahmetalpbalkan that's a new acronym for me :-)

The recommended 'eval "$(docker-machine env name)"' will set DOCKER_TLS_VERIFY and the person in the chair operating the keyboard knows nothing about it (this is exactly how why I originally wrote the set it to blank).

But either way, it is a documentation issue, some folks will prefer --tls=false, others DOCKER_TLS_VERIFY, personally I prefer a .config file but I don't think Docker supports one of those ;-)

**Pull request merged**
