### PR TITLE
Adding Azure CDN deployment templates

### PR DESCRIPTION
**Pull request by kuangweizhang**
Following templates will enable user to create Azure CDN related resources. Azure CDN resource provider is currently in private preview.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kuangweizhang__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@kuangweizhang Are you an MSFT FTE? If so, can you please send me an email offline. Thx!

**Comment by azurecla** [comment]
__@kuangweizhang__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by singhkay** [comment]
@template-deploy-bot test this please

**Comment by singhkay** [comment]
@kuangweizhang Looks like the deployment failed for the profileName "uejuugzf". Are there any allowed values that need to be taken care of?

**Comment by singhkay** [comment]
@template-deploy-bot test this please

**Comment by singhkay** [comment]
@template-deploy-bot test this please

**Comment by tmcgannon** [comment]
When will the CDN resource provider be available to the public?  Or can I apply to use the private preview?

**Comment by singhkay** [comment]
@kuangweizhang Can you take a look at @tmcgannon's question?

**Comment by kuangweizhang** [comment]
@tmcgannon Hi Tom, CDN resource provider will be available to the public very soon! Please check back on this in just a few days.
Private preview is only available for Microsoft internal users. If you are a Microsoft FTE, please ping me offline.

**Pull request merged**
