### PR TITLE
Add sample: Front Door Standard/Premium with App Service environment (ILB ASE) origin and private endpoint

### PR DESCRIPTION
**Pull request by johndowns**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Add sample - Front Door Standard/Premium with App Service environment (ILB ASE) origin and private endpoint

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Comment by johndowns** [comment]
The ARM TTK is complaining about an empty array property on line 341. However, the RP API spec lists this as mandatory, and the Bicep tooling shows a warning if I omit it - so I'll leave it there unless told otherwise.

**Comment by bmoore-msft** [comment]
Is it actually required?  (trying to figure out which is incorrect)  We can add an exception in the TTK but if it's not actually required we should fix spec/docs...

**Comment by johndowns** [comment]
I actually just tried it and it looks like it's not required even though the schema says it is. What would you like to do?

**Comment by bmoore-msft** [comment]
remove it from your sample and file a bug against the swagger spec.

**Comment by johndowns** [comment]
Done. https://github.com/Azure/azure-rest-api-specs/issues/13216

**Comment by bmoore-msft** [comment]
@johndowns - check this PR for updates that may be needed to documentation that references this sample.  [this is an automated message]

**Pull request merged**
