### PR TITLE
MS Dynamics NAV

### PR DESCRIPTION
**Pull request by tfenster**
With this quickstart template you can deploy a Dynamics NAV container

### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

*
*
*

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@tfenster can you check the CI failures?

**Comment by tfenster** [comment]
The first failure seems to be because some name ist too long. But as there are things like "101-application-gateway-public-ip-ssl-offload" I am not sure which name is the problem here?

The second failure is because I am using a private repo set up by Freddy Kristiansen from Microsoft. I am not the owner and therefore won't share it as I didn't find a way to encrypt it without tying it to my registry. Or did I misunderstand how the key vault works? Or I could ask him if he would want to share it with you but I am not sure if you would be willing to support that kind of scenario where automated CI will always fail?

**Comment by bmoore-msft** [comment]
The first is referring to metadata.json - the properties in that file have maxlengths (you can read in that schema or the readme for the repo).

re: the second, the image needs to be public (or accessible) no point in having a sample no one can deploy...

**Comment by tfenster** [comment]
Ok, I've fixed the maxlength problem, thanks for pointing me in the right direction. 

For the second problem, I would think that everyone interested in this specific sample should have the password, but I get your point. The images should become publicly available in the next weeks and I'll then get back and update the sample. Should I close the PR until then or can I leave it open?

**Comment by bmoore-msft** [comment]
Let's close it for now and the reopen when the images are available to the public

**Comment by tfenster** [comment]
Good timing, the images were made available publicly today and as you can see, build succeeds now as well :)

**Comment by tfenster** [comment]
Hi @bmoore-msft, is there anything I need to change in addition to the build passing?

**Pull request closed without merging**
