### PR TITLE
Installing Guest Attestation extension by default for Trusted Launch enabled Windows VMs

### PR DESCRIPTION
**Pull request by sirfamelin**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Adding changes to install the Guest Attestation extension for Trusted Launch Windows VMs with Secureboot and vTPM enabled.

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@cynthn - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Review by bmoore-msft — CHANGES_REQUESTED** [review]
Let's update the readme with some detail about these changes - also check the pipeline results for other changes that need to be made.

**Comment by azure-quickstarts** [comment]
@cynthn - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@cynthn - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@cynthn - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by sirfamelin** [comment]
> Let's update the readme with some detail about these changes - also check the pipeline results for other changes that need to be made.

Updated the readme and addressed all the pipeline checks

**Comment by azure-quickstarts** [comment]
@cynthn - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Pull request merged**
