### PR TITLE
Adding Augur prediction market template

### PR DESCRIPTION
**Pull request by kevinday**
This PR adds a template to spin up an private Augur prediction market on Azure.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kevinday__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@kevinday__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by realcodywburns** [comment]
changing "dateUpdated": "2016-8-25" >> "dateUpdated": "2016-08-25" in augur-on-ubuntu/metadata.json will clear the current error

**Comment by gatneil** [comment]
I have the same comments on this PR as in your other one: https://github.com/Azure/azure-quickstart-templates/pull/2574 :) Please address

**Comment by gatneil** [comment]
No activity; closing

**Pull request closed without merging**
