### PR TITLE
(AZUREVAVS-105) Release 1.2MPP

### PR DESCRIPTION
**Pull request by sasdaberg**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Review by bmoore-msft — CHANGES_REQUESTED** [review]
Can you move this sample to the application-workloads/sas folder and remove the uppercase chars from the folder name?

**Comment by sasdaberg** [comment]
> Can you move this sample to the application-workloads/sas folder and remove the uppercase chars from the folder name?

Would it be possible to deliver your requested change in our next release?

This PR change fixes a broken third party dependency which is causing our QS deployment to fail.  We have already waited two weeks since delivering this fix and changing the project location would require a round a testing on our side which will delay this fix even longer.

FYI:  We are already planning our next release to be delivered to our test team this week.  This next release addresses the two Azure best practices issues we currently have.  We should be able to include the path changes in this release too.

**Comment by bmoore-msft** [comment]
I will go ahead and merge - let's update it quickly though.  This sample has already been copied to the correct location and that copy won't have these changes.  Also, since it has been copied to the new location, we're removing the duplicate samples from the root, so if not done soon we'll lose those changes.

**Comment by sasdaberg** [comment]
Roger that.  Working on testing the new location now.  I'll make sure my current changes are included in my next PR too.

**Pull request merged**
