### PR TITLE
Multiple fixes to SharePoint Templates

### PR DESCRIPTION
**Pull request by simongdavies**

### CODE REVIEW

**Comment by singhkay** [comment]
@simongdavies Can you CI the parameters files? https://github.com/Azure/azure-quickstart-templates/tree/master/1-CONTRIBUTION-GUIDE#travis-ci Also looks like the parameters file for ha template doesn't have the schema style declaration

**Comment by singhkay** [comment]
@simongdavies Looks like this template takes longer to deploy than TravisCI's limit. I'll verify by deploying locally.

"The job exceeded the maxmimum time limit for jobs, and has been terminated."

**Comment by singhkay** [comment]
@simongdavies Deployed locally succesfully. However, this parameter confused me if it needed a value or not in case of new value in spWebIPNewOrExisting. Maybe this should have a default value of "" as well https://github.com/simongdavies/azure-quickstart-templates/blob/master/sharepoint-server-farm-ha/azuredeploy.json#L196

Also spWebIPNewOrExisting should probably be moved above spWebIPRGName and spWebIPAddressName

**Comment by simongdavies** [comment]
@singhkay updated as suggested, deploy is running again but will probably timeout

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
