### PR TITLE
Adding templates for deploying TFS in Azure

### PR DESCRIPTION
**Pull request by chrisamert**
tfs-basic-domain - Creates a self-contained, single VM TFS deployment including TFS, SQL Express and a Domain Controller

tfs-basic-workgroup - Creates a self-contained, single VM TFS workgroup deployment, including TFS and SQL Express

tfs-dual-server - Creates a TFS deployment with three VMS.  One Domain Controller, one running SQL Server Standard, and one with TFS

tfs-standard-existing - Creates a new TFS Deployment in an existing domain, configured against an existing SQL instance

### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### CODE REVIEW

**Comment by jackpot1136** [comment]
Great work.

**Comment by chrisamert** [comment]
Looks like the CI build timed out.  Is there a way to increase that timeout?  A couple of these templates are expected to take > 1hr to deploy.

**Comment by bmoore-msft** [comment]
for starters, let's break these into one sample per pr

**Comment by chrisamert** [comment]
I'll do that, thanks

**Pull request closed without merging**
