### PR TITLE
update api

### PR DESCRIPTION
**Pull request by vhorne**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@vhorne - this sample passed the last test run, but is failing with the new apiVersions... was there a breaking change in the new apiVersion?

**Comment by vhorne** [comment]
@bmoore-msft Ya, we were asked to use the newer API to allow for new firewall functionality that recently released.

**Comment by bmoore-msft** [comment]
I'm with you - was there a breaking change in it though?  Can't think of another reason why this would fail all of a sudden

**Comment by vhorne** [comment]
@bmoore-msft No, I think the team was having some regional issues with the service. Should be fixed now...

**Comment by bmoore-msft** [comment]
Looks like there are still issues (unless you recognize this error)...

**Comment by vhorne** [comment]
@bmoore-msft 
I've successfully deployed this template several times, so I'm not sure what the problem is here:
image

**Comment by vhorne** [comment]
@bmoore-msft 
I closed and reopened this PR, and it now shows "All checks have passed - 3 successful checks"

**Pull request merged**
