### PR TITLE
Update template sharepoint

### PR DESCRIPTION
**Pull request by Yvand**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Added

- Template
  - Added value `Subscription-latest` to parameter `sharePointVersion`, to install the January 2023 CU on SharePoint Subscription
- Configuration for DC
  - Create additional users in AD, in a dedicated OU `AdditionalUsers`
- Configuration for SQL
  - Install SQL module `SqlServer` (version 21.1.18256) as it is the preferred option of `SqlServerDsc`
- Configuration for all SharePoint versions
  - Create various desktop shortcuts
  - Configure Windows explorer to always show file extensions and expand the ribbon
  - Enqueue the creation of the personal sites of the admin and all users in OU `AdditionalUsers`, for both Windows and trusted authentication modes
  - Add the OU `AdditionalUsers` to the User Profile synchronization connection
  - Grant the domain administrator `Full Control` to the User Profile service application
- Configuration for SharePoint Subscription and 2019
  - Set OneDrive NGSC registry keys to be able to sync sites located under MySites path

### Changed

- Template
  - Revert SQL image to SQL Server 2019, due to reliability issues with SQL Server 2022 (SQL PowerShell modules not ready yet)
  - If user chooses SharePoint 2013, template deploys SQL Server 2014 SP3 (latest version it supports)
- Configuration for DC
  - Review the logic to allow the VM to restart after the AD FS farm was configured (as required), and before the other VMs attempt to join the domain
- Configuration for all VMs except DC
  - Review the logic to join the AD domain only after it is guaranteed that the DC is ready. This fixes the most common cause of random deployment errors

### CODE REVIEW

**Comment by Yvand** [comment]
@alex-frankel this PR is ready for your review
Also, I added again the tag `sharepoint` to the README, but I'm sure it will be deleted, as it happened last time by commit f8ed6543705f3819d3c0f03744ac27dfe540bfc9.
Is it possible to add this tag to this template?

**Comment by alex-frankel** [comment]
Based on looking at [this script](https://github.com/Azure/azure-quickstart-templates/blob/master/test/ci-scripts/Update-ReadMe.ps1#L77), this list is static.

What is the goal in adding the `sharepoint` tag?

**Comment by Yvand** [comment]
@alex-frankel I assume the tags are the values in 'Products' filter in <https://learn.microsoft.com/en-us/samples/browse/>, and since this template deploys SharePoint, tag `sharepoint` is very relevant

**Comment by Yvand** [comment]
@alex-frankel is this PR still in your radar?

**Comment by alex-frankel** [comment]
> @alex-frankel I assume the tags are the values in 'Products' filter in https://learn.microsoft.com/en-us/samples/browse/, and since this template deploys SharePoint, tag `sharepoint` is very relevant

Looks like, at least for now, the QuickStarts CI does not support this, but I will do some investigation to confirm that.

**Pull request merged**
