### PR TITLE
Open edX templates uri fix

### PR DESCRIPTION
**Pull request by chenriksson**
Open edX templates uri fix (I reversed template subfolder and branch in uri during initial PR)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@chenriksson__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (chenriks). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by chenriksson** [comment]
Any idea what this exception means?

Server Error:{
    "error": {
        "code": "ENOTFOUND",
        "errno": "ENOTFOUND",
        "syscall": "getaddrinfo",
        "hostname": "arm-validator.40.118.211.57.xip.io"
    }
}

**Comment by singhkay** [comment]
@chenriksson Transient dns service failure. i've kicked off deployment again.

**Comment by singhkay** [comment]
lgtm, merged

**Comment by chenriksson** [comment]
Thanks!

**Pull request merged**
