### PR TITLE
Add template: n Number IIS VM DSC

### PR DESCRIPTION
**Pull request by wilbug1**
### Contributing guide

https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md
### Changelog

*
*
*
*
*

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@wilbug1__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@wilbug1 We have a few existing IIS templates in the repo already. Can you look into enhancing these with your changes instead of a new template? https://github.com/Azure/azure-quickstart-templates/search?l=json&q=iis&utf8=✓ Thanks!

**Comment by gatneil** [comment]
If the existing IIS templates are good, shall we close this PR?

**Comment by gatneil** [comment]
No response; closing

**Pull request closed without merging**
