### PR TITLE
Update servicebusIngestion.ps1

### PR DESCRIPTION
**Pull request by PerninManon**
If several rules exist, an error is raised because « A duplicate property 'SharedAccessKeyName' was found in the Service Bus connection string. ».
By selecting specifically one rule the problem is solved : "RootManageSharedAccessKey".

### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

*
*
*

### CODE REVIEW

**Comment by msftgits** [comment]
Closing & reopening to validate whether there is a CLA for this contribution

**Comment by krnese** [comment]
thanks @PerninManon .
@tianderturpijn - can you have a look?

**Comment by tianderturpijn** [comment]
Thank you @PerninManon
I had this fix already in a new build, so it's included in my latest update.
Let me know if this works for you.

**Comment by bmoore-msft** [comment]
@PerninManon - can you check the merge conflicts?

**Comment by bmoore-msft** [comment]
Closing due to no activity and merge conflicts

**Pull request closed without merging**
