### PR TITLE
Diagnostic setting for Azure Storage account

### PR DESCRIPTION
**Pull request by normesta**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@normesta - do you know how to enable the feature preview for the sample?

**Comment by normesta** [comment]
Hi @bmoore-msft - the feature is enable by way of filling out a form and having a subscription white listed. I think that is why this template submission initially failed. I think there are other issues with this sample here so I more or less left it in a failed state for now. I'll likely just close this out as I've published the template via another mechanism.  When the feature goes GA and the whitelist is no longer needed, I'll attempt another submission to the gallery. Are you an admin on this repo?  Are you asking because you are trying to address open pull requests on this repo?

**Comment by bmoore-msft** [comment]
yes - I review the PRs before merging to the repo...

If we want to have this working for preview, then add some instructions to the readme to help users know what steps to take...  I'll follow those steps for the test subscription as validation.  If you want to close out until GA, that's fine too.

**Comment by normesta** [comment]
Thanks Brian. I'll hold off for now. Thx!

**Pull request closed without merging**
