### PR TITLE
Use latest version of dsc extension

### PR DESCRIPTION
**Pull request by jodoglevy**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jodoglevy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jolevy). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@jodoglevy Can you check the CI error? https://travis-ci.org/Azure/azure-quickstart-templates/builds/139354832#L224

**Comment by jodoglevy** [comment]
Error seems to be:  AssertionError: dsc-extension-azure-automation-pullserver/azuredeploy.parameters.json -  Parameter "registrationKey" is missing its value field
      + expected - actual

Assuming this means they want a default value specified for the parameter registrationKey, that's not possible. It is a securestring that is specific to the user's automation account, so the user always needs to pass it.

**Comment by jodoglevy** [comment]
@singhkay given that, can i ignore or is there something to fix?

**Comment by singhkay** [comment]
@jodoglevy yeah we can ignore that, CI can't generate that value. merged

**Comment by jodoglevy** [comment]
@singhkay ty

**Pull request merged**
