### PR TITLE
Firewall availability zone - update resource API versions and create …

### PR DESCRIPTION
**Pull request by mumian**
…the Bicep file

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by mumian** [comment]
@vhorne - Hi Vic, I am getting the following error.  Do you have any ideas on how to fix the issue? 

Status Message: Azure Firewall /subscriptions/0cec7090-2e08-4498-9337-eb96ade50821/resourceGroups/azdo-6ca0133c-6554-4b02-9f87-be6c5a025336/providers/Microsoft.Network/azureFirewalls/firewall1 has zone constraint 1, 2, 3, but Public IP /subscriptions/0cec7090-2e08-4498-9337-eb96ade50821/resourceGroups/azdo-6ca0133c-6554-4b02-9f87-be6c5a025336/providers/Microsoft.Network/publicIPAddresses/publicIP1 referenced by the azure firewall has no zones (Code: ZonalAzureFirewallCannotReferenceNoZonePublicIp)

**Comment by mumian** [comment]
@vhorne - can you take a look of this PR?  Or do you know anybody who can help?  Thanks.

**Comment by azure-quickstarts** [comment]
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@vhorne - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by mumian** [comment]
Can't update the PR.  Close this one, and create a new one.

**Pull request closed without merging**
