### PR TITLE
create an IoT Hub Device Provisioning Service

### PR DESCRIPTION
**Pull request by mumian**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by mumian** [comment]
@bmoore-msft - can you take a look at the error message?  The template deployed successfully when I tested it on my computer.

**Comment by bmoore-msft** [comment]
I get the same error, I would try reaching out to the IoT folks...

**Comment by wesmc7777** [comment]
@mumian The only thing I really see that might be wrong is the ApiVersion shown [here](https://github.com/Azure/azure-quickstart-templates/pull/8389/commits/6f31e9752ee4037d92f120635c74e5abb15a933c). However, it's still failing for some reason. I'm trying to figure out how to look at those deployment scripts that are running I wonder if they are actually waiting on the IoT hub deployment to fully complete first based on the `dependOn` attribute

**Comment by mumian** [comment]
@bmoore-msft - can you take a look of @wesmc7777's comment?

**Comment by bmoore-msft** [comment]
I don't think it's a timing issue in ARM - reference() will issue the GET and if it returns it should be correct/complete.  This looks like an RP issue - either they are expecting some syntax they're not getting (which without docs is tough to debug ;)) or the GET on the resource isn't telling the truth.

**Comment by wesmc7777** [comment]
@bmoore-msft Aware of a way we could log that connection string to examine it?

**Comment by bmoore-msft** [comment]
Just set the same property value to an output...

**Comment by wesmc7777** [comment]
Hmm, not getting anything for some reason...

2020-10-12T23:26:44.8100875Z Parameters              : 
2020-10-12T23:26:44.8113504Z                           Name                       Type                       Value     
2020-10-12T23:26:44.8114705Z                           =========================  =========================  ==========
2020-10-12T23:26:44.8116358Z                           iotHubName                 String                     cib9b8c7c375234682
2020-10-12T23:26:44.8117612Z                           provisioningServiceName    String                     cie034950eea794bd0
2020-10-12T23:26:44.8118798Z                           location                   String                     usgovvirginia
2020-10-12T23:26:44.8120065Z                           skuName                    String                     S1        
2020-10-12T23:26:44.8121240Z                           skuUnits                   String                     1         
2020-10-12T23:26:44.8122303Z                           
**2020-10-12T23:26:44.8123148Z Outputs                 : **
2020-10-12T23:26:44.8124206Z DeploymentDebugLogLevel :

**Comment by wesmc7777** [comment]
@bmoore-msft @mumian ok I have this all resolved in [PR 8414](https://github.com/Azure/azure-quickstart-templates/pull/8414)

**Comment by mumian** [comment]
Close this PR as Wes has created another PR.

**Pull request closed without merging**
