### PR TITLE
AKS zero-downtime deployment with Jenkins

### PR DESCRIPTION
**Pull request by ArieShout**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

* Add quick start template for AKS zero-downtime deployment with Jenkins

### CODE REVIEW

**Comment by bmoore-msft** [comment]
Why are we skipping ci?

**Comment by ArieShout** [comment]
@bmoore-msft that's not intended. I copied the base files template from `301-jenins-aptly-spinnaker-vmss`. Just removed `.ci_skip`.

**Comment by bmoore-msft** [comment]
Thanks @ArieShout - check the CI failure... since containers have limited region availability, add a parameter named 'location' and set the defaultValue for one of the allowedValues

**Comment by ArieShout** [comment]
Hi @bmoore-msft ,

I tried to add the `location` parameter in the `parameters` section, but it's still failing the same. I can see the `location` is restricted when I deploy it manually, but it seems the CI is not regarding the `location` parameter when it creates the resource group before deploying the target template.
So I updated the `Microsoft.ContainerService/managedClusters` resource to use the value in `location` parameter, rather than `resourceGroup().location` as suggested. Now it's failing on the service principal.
The `GEN-UNIQUE` as used in other template doesn't work for the service principal field because the managed cluster expects a working service principal to provision necessary resources. Do we have any workaround on this kind of situation?

**Comment by ArieShout** [comment]
Hi @bmoore-msft , could you advise how we can workaround the issue that the template requires a working service principal to pass the deployment CI test?

Thanks,

**Comment by bmoore-msft** [comment]
you'll need to use an MSI - https://docs.microsoft.com/en-us/azure/active-directory/msi-overview

Some samples: https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-msi-linux

**Comment by ArieShout** [comment]
@bmoore-msft MSI is not applicable in this case. The AKS deployment requires a working service principal explicitly. There is no ARM template configuration entry to restrict it to use MSI instead. 

Can we skip the CI build in this case?

**Comment by ArieShout** [comment]
As confirmed, ACS/AKS requires a working service principal configuration in the ARM template explicitly. (When we create ACS/AKS from Azure CLI we can omit the service principal parameters and it will generate one before the underlying ARM deployment, which leads to the previous confusion).

As a result, we cannot inject some dummy values for the service principal parameter, or use MSI as a replacement.

As I checked, some ACS related templates also fail the CI build (dummy reference https://github.com/Azure/azure-quickstart-templates/pull/4250). 

@bmoore-msft  Can we add `.ci_skip` to skip the CI build verification in this case?

**Pull request merged**
