### PR TITLE
Add Bicep and update API versions

### PR DESCRIPTION
**Pull request by mumian**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@Blackmist - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@Blackmist - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by mumian** [comment]
@Blackmist - can you take a look at line 378-381 in main.bicep?  Shall we choose between new and existing resources?  ContainerRegistryOption has three choices.  The code only covers two.  Same ask for line 416 and line 417.  Thanks.

**Comment by Blackmist** [comment]
> @Blackmist - can you take a look at line 378-381 in main.bicep? Shall we choose between new and existing resources? ContainerRegistryOption has three choices. The code only covers two. Same ask for line 416 and line 417. Thanks.

@mumian We should keep all 3 options. The behavior for AzureML is:
* If no container registry is provided (none option) it will automatically create one dynamically when needed (when you perform a task that needs to build a Docker image). This may be OK for some customers. For example, they might not plan on building images, but instead only using the ones Microsoft provides.
* The new option would use the template to create a new ACR as part of the deployment and wire up AzureML to use it.
* The existing would wire up AzureML to use an existing ACR instance.

The none option has no code by design I'm guessing. It is the default behavior when creating AzureML.

For 416 & 417, you mean the subnets that are created? And that the "subnetName" that the user can specify isn't listed? I am guessing that this is there to allow the user to optionally create a subnet for resources. Technically, everything for AzureML can be in one subnet, but customers sometimes want to isolate training to one subnet, scoring to another, and resources (storage, acr, etc) to yet another subnet. This seems more like a nicety to me. @deeikele for more context as he was more involved in creation of this template.

**Comment by mumian** [comment]
@Blackmist - I probably didn't explain the problem clearly enough.  On line 378, the existing storage account id is assigned.  Do we need to check whether the storageAccountOption is 'new' or 'existing' before we assign either the existing storage account ID or the new storage account ID.

**Comment by Blackmist** [comment]
> @Blackmist - I probably didn't explain the problem clearly enough. On line 378, the existing storage account id is assigned. Do we need to check whether the storageAccountOption is 'new' or 'existing' before we assign either the existing storage account ID or the new storage account ID.

Nope. Effectively they are the same as far as creating the AzureML workspace resource is concerned. It just wants the ID of the resource, regardless of whether it is for an already existing resource or one that the template created. The caveat being that the "new" path for resources such as storage needs to create those resources before creating the AzureML workspace resource.

**Comment by azure-quickstarts** [comment]
@Blackmist - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@Blackmist - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by mumian** [comment]
@bmoore-msft - can you take a look at this PR?  The error code is: 

New-AzResourceGroupDeployment : 6:41:57 PM - Error: Code=InvalidTemplate; Message=Deployment template validation failed: 'The template resource '[format('{0}/{1}', reference(resourceId('Microsoft.Network/privateDnsZones', parameters('privateAznbDnsZoneName')[toLower(environment().name)]), '2020-06-01', 'full')[toLower(environment().name)], uniqueString(parameters('vnetId')))]' at line '1' and column '5244' is not valid: The template function 'reference' is not expected at this location. Please see https://aka.ms/arm-template-expressions for usage details.. Please see https://aka.ms/arm-template-expressions for usage details.'.

In the built azuredeploy.json, the two name-properties are built differently from main.bicep:

            {
              "condition": "[equals(parameters('privateEndpointType'), 'AutoApproval')]",
              "type": "Microsoft.Network/privateDnsZones/virtualNetworkLinks",
              "apiVersion": "2020-06-01",
              "name": "[format('{0}/{1}', parameters('privateDnsZoneName')[toLower(environment().name)], uniqueString(parameters('vnetId')))]",
              "location": "global",
              "tags": "[parameters('tagValues')]",
              "properties": {
                "virtualNetwork": {
                  "id": "[parameters('vnetId')]"
                },
                "registrationEnabled": false
              },
              "dependsOn": [
                "[resourceId('Microsoft.Network/privateDnsZones', parameters('privateDnsZoneName')[toLower(environment().name)])]",
                "[resourceId('Microsoft.Network/privateEndpoints', format('{0}-PrivateEndpoint', parameters('workspaceName')))]"
              ]
            },
            {
              "condition": "[equals(parameters('privateEndpointType'), 'AutoApproval')]",
              "type": "Microsoft.Network/privateDnsZones/virtualNetworkLinks",
              "apiVersion": "2020-06-01",
              "name": "[format('{0}/{1}', reference(resourceId('Microsoft.Network/privateDnsZones', parameters('privateAznbDnsZoneName')[toLower(environment().name)]), '2020-06-01', 'full')[toLower(environment().name)], uniqueString(parameters('vnetId')))]",
              "location": "global",
              "tags": "[parameters('tagValues')]",
              "properties": {
                "virtualNetwork": {
                  "id": "[parameters('vnetId')]"
                },
                "registrationEnabled": false
              },
              "dependsOn": [
                "[resourceId('Microsoft.Network/privateDnsZones', parameters('privateAznbDnsZoneName')[toLower(environment().name)])]",
                "[resourceId('Microsoft.Network/privateEndpoints', format('{0}-PrivateEndpoint', parameters('workspaceName')))]"
              ]
            },

**Comment by bmoore-msft** [comment]
This looks to be a bicep issue - I would see if you can get a repro to them...

**Comment by azure-quickstarts** [comment]
@Blackmist - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@Blackmist - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by mumian** [comment]
@bmoore-msft, @Blackmist - can you take a look at this PR?  I am getting the following error:

2022-12-07T15:30:36.4720822Z New-AzResourceGroupDeployment : [31;1m3:30:36 PM - The deployment 'mainTemplate-deployment' failed with error(s). Showing 2 out of 2 error(s).
2022-12-07T15:30:36.4726940Z Status Message: No registered resource provider found for location 'westcentralus' and API version '2022-05-01' for type 'privateEndpoints'. The supported api-versions are '2019-02-01, 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01, 2019-12-01, 2020-01-01, 2020-03-01, 2020-04-01, 2020-05-01, 2020-06-01, 2020-07-01, 2020-08-01, 2020-11-01, 2021-01-01, 2021-02-01, 2021-03-01, 2021-04-01, 2021-05-01, 2021-06-01, 2021-08-01, 2021-12-01, 2022-01-01'. The supported locations are 'westus, eastus, northeurope, westeurope, eastasia, southeastasia, northcentralus, southcentralus, centralus, eastus2, japaneast, japanwest, brazilsouth, australiaeast, australiasoutheast, centralindia, southindia, westindia, canadacentral, canadaeast, westcentralus, westus2, ukwest, uksouth, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth, switzerlandnorth, germanywestcentral, norwayeast, westus3, jioindiawest, swedencentral, qatarcentral'. (Code:NoRegisteredProviderFound)
2022-12-07T15:30:36.4732841Z Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details. (Code: DeploymentFailed)

**Comment by bmoore-msft** [comment]
Not sure - I'll run the pipeline again to see if it's transient - if not, probably need to reach out to NRP/Support.

**Comment by azure-quickstarts** [comment]
@Blackmist - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Pull request merged**
