### PR TITLE
Update VM size to Ev3 and add VM parameters, 4.0

### PR DESCRIPTION
**Pull request by guyhay**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@guyhay - what's the plan for these in FF?   I know you were looking into that from a past PR.  Now it looks like the ES sizes are supported by not E?

**Comment by guyhay** [comment]
We should have fixed this with the deployment of su12.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bmoore-msft** [comment]
ok, we'll need to trigger a new pipeline run when that's finished...

**Comment by guyhay** [comment]
It's already done to the best of my knowledge.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guyhay** [comment]
Feb 11th it was deployed

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bmoore-msft** [comment]
Any ideas why it's not working then?

**Comment by guyhay** [comment]
I'll have to go find out.  I see that it's still rejecting on
Status Message: DeploymentDocument 'CsmDocument_2_0' failed the validation. Error: 'VM size 'standard_e4_v3' provided in the request is not allowed. Valid values are: STANDARD_D12,STANDARD_D12_V2,STANDARD_D13,STANDARD_D13_V2,STANDARD_D14,STANDARD_D14_V2,STANDARD_D3,STANDARD_D3_V2,STANDARD_D4,STANDARD_D4_V2,STANDARD_D5_V2,STANDARD_DS12_V2,STANDARD_DS13_V2,STANDARD_DS14_V2,STANDARD_DS3_V2,STANDARD_DS4_V2,STANDARD_DS5_V2,STANDARD_A2_V2,STANDARD_E16S_V3,STANDARD_E20S_V3,STANDARD_E2S_V3,STANDARD_E32S_V3,STANDARD_E4S_V3,STANDARD_E64S_V3,STANDARD_E8S_V3,STANDARD_A3,STANDARD_A4,STANDARD_A5,STANDARD_A6,STANDARD_A7' (Code:InvalidDocumentErrorCode)

@Xue Shan Zhao<mailto:Xue.Zhao@microsoft.com> can you or one of your team help me here.  As I understand it SU12 was deployed to FairFax earlier in Feb.  I'm still seeing failures when I try and use the new Ev3 VM sizes.

Guy

**Comment by guyhay** [comment]
Loop Silan for help. @Silan Hu<mailto:silahu@microsoft.com>

From: Guy Haycock <guyhay@microsoft.com>
Sent: 2021年2月27日 7:08
To: Azure/azure-quickstart-templates <reply@reply.github.com>; Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com>; Xue Shan Zhao <Xue.Zhao@microsoft.com>
Cc: Mention <mention@noreply.github.com>; Mimi Gentz <mimig@microsoft.com>
Subject: RE: [Azure/azure-quickstart-templates] Update VM size to Ev3 and add VM parameters, 4.0 (#8802)

I’ll have to go find out.  I see that it’s still rejecting on
Status Message: DeploymentDocument 'CsmDocument_2_0' failed the validation. Error: 'VM size 'standard_e4_v3' provided in the request is not allowed. Valid values are: STANDARD_D12,STANDARD_D12_V2,STANDARD_D13,STANDARD_D13_V2,STANDARD_D14,STANDARD_D14_V2,STANDARD_D3,STANDARD_D3_V2,STANDARD_D4,STANDARD_D4_V2,STANDARD_D5_V2,STANDARD_DS12_V2,STANDARD_DS13_V2,STANDARD_DS14_V2,STANDARD_DS3_V2,STANDARD_DS4_V2,STANDARD_DS5_V2,STANDARD_A2_V2,STANDARD_E16S_V3,STANDARD_E20S_V3,STANDARD_E2S_V3,STANDARD_E32S_V3,STANDARD_E4S_V3,STANDARD_E64S_V3,STANDARD_E8S_V3,STANDARD_A3,STANDARD_A4,STANDARD_A5,STANDARD_A6,STANDARD_A7' (Code:InvalidDocumentErrorCode)

@Xue Shan Zhao<mailto:Xue.Zhao@microsoft.com> can you or one of your team help me here.  As I understand it SU12 was deployed to FairFax earlier in Feb.  I’m still seeing failures when I try and use the new Ev3 VM sizes.

Guy

**Comment by guyhay** [comment]
Hi, all

I have enabled EV3 for all public regions.

Thanks
Silan

From: Xue Shan Zhao <Xue.Zhao@microsoft.com>
Sent: Saturday, February 27, 2021 7:22 AM
To: Guy Haycock <guyhay@microsoft.com>; Azure/azure-quickstart-templates <reply@reply.github.com>; Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com>; Silan Hu <silahu@microsoft.com>
Cc: Mention <mention@noreply.github.com>; Mimi Gentz <mimig@microsoft.com>
Subject: RE: [Azure/azure-quickstart-templates] Update VM size to Ev3 and add VM parameters, 4.0 (#8802)

Loop Silan for help. @Silan Hu<mailto:silahu@microsoft.com>

From: Guy Haycock <guyhay@microsoft.com<mailto:guyhay@microsoft.com>>
Sent: 2021年2月27日 7:08
To: Azure/azure-quickstart-templates <reply@reply.github.com<mailto:reply@reply.github.com>>; Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com<mailto:azure-quickstart-templates@noreply.github.com>>; Xue Shan Zhao <Xue.Zhao@microsoft.com<mailto:Xue.Zhao@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Mimi Gentz <mimig@microsoft.com<mailto:mimig@microsoft.com>>
Subject: RE: [Azure/azure-quickstart-templates] Update VM size to Ev3 and add VM parameters, 4.0 (#8802)

I’ll have to go find out.  I see that it’s still rejecting on
Status Message: DeploymentDocument 'CsmDocument_2_0' failed the validation. Error: 'VM size 'standard_e4_v3' provided in the request is not allowed. Valid values are: STANDARD_D12,STANDARD_D12_V2,STANDARD_D13,STANDARD_D13_V2,STANDARD_D14,STANDARD_D14_V2,STANDARD_D3,STANDARD_D3_V2,STANDARD_D4,STANDARD_D4_V2,STANDARD_D5_V2,STANDARD_DS12_V2,STANDARD_DS13_V2,STANDARD_DS14_V2,STANDARD_DS3_V2,STANDARD_DS4_V2,STANDARD_DS5_V2,STANDARD_A2_V2,STANDARD_E16S_V3,STANDARD_E20S_V3,STANDARD_E2S_V3,STANDARD_E32S_V3,STANDARD_E4S_V3,STANDARD_E64S_V3,STANDARD_E8S_V3,STANDARD_A3,STANDARD_A4,STANDARD_A5,STANDARD_A6,STANDARD_A7' (Code:InvalidDocumentErrorCode)

@Xue Shan Zhao<mailto:Xue.Zhao@microsoft.com> can you or one of your team help me here.  As I understand it SU12 was deployed to FairFax earlier in Feb.  I’m still seeing failures when I try and use the new Ev3 VM sizes.

Guy

**Comment by guyhay** [comment]
Thank you very much!

From: Silan Hu <silahu@microsoft.com>
Sent: Monday, March 1, 2021 00:38
To: Xue Shan Zhao <Xue.Zhao@microsoft.com>; Guy Haycock <guyhay@microsoft.com>; Azure/azure-quickstart-templates <reply@reply.github.com>; Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Mimi Gentz <mimig@microsoft.com>; Alicia Li (COSMOS) <ali@microsoft.com>; Guy Haycock <guyhay@microsoft.com>
Subject: RE: [Azure/azure-quickstart-templates] Update VM size to Ev3 and add VM parameters, 4.0 (#8802)

Hi, all

I have enabled EV3 for all public regions.

Thanks
Silan

From: Xue Shan Zhao <Xue.Zhao@microsoft.com<mailto:Xue.Zhao@microsoft.com>>
Sent: Saturday, February 27, 2021 7:22 AM
To: Guy Haycock <guyhay@microsoft.com<mailto:guyhay@microsoft.com>>; Azure/azure-quickstart-templates <reply@reply.github.com<mailto:reply@reply.github.com>>; Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com<mailto:azure-quickstart-templates@noreply.github.com>>; Silan Hu <silahu@microsoft.com<mailto:silahu@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Mimi Gentz <mimig@microsoft.com<mailto:mimig@microsoft.com>>
Subject: RE: [Azure/azure-quickstart-templates] Update VM size to Ev3 and add VM parameters, 4.0 (#8802)

Loop Silan for help. @Silan Hu<mailto:silahu@microsoft.com>

From: Guy Haycock <guyhay@microsoft.com<mailto:guyhay@microsoft.com>>
Sent: 2021年2月27日 7:08
To: Azure/azure-quickstart-templates <reply@reply.github.com<mailto:reply@reply.github.com>>; Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com<mailto:azure-quickstart-templates@noreply.github.com>>; Xue Shan Zhao <Xue.Zhao@microsoft.com<mailto:Xue.Zhao@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Mimi Gentz <mimig@microsoft.com<mailto:mimig@microsoft.com>>
Subject: RE: [Azure/azure-quickstart-templates] Update VM size to Ev3 and add VM parameters, 4.0 (#8802)

I’ll have to go find out.  I see that it’s still rejecting on
Status Message: DeploymentDocument 'CsmDocument_2_0' failed the validation. Error: 'VM size 'standard_e4_v3' provided in the request is not allowed. Valid values are: STANDARD_D12,STANDARD_D12_V2,STANDARD_D13,STANDARD_D13_V2,STANDARD_D14,STANDARD_D14_V2,STANDARD_D3,STANDARD_D3_V2,STANDARD_D4,STANDARD_D4_V2,STANDARD_D5_V2,STANDARD_DS12_V2,STANDARD_DS13_V2,STANDARD_DS14_V2,STANDARD_DS3_V2,STANDARD_DS4_V2,STANDARD_DS5_V2,STANDARD_A2_V2,STANDARD_E16S_V3,STANDARD_E20S_V3,STANDARD_E2S_V3,STANDARD_E32S_V3,STANDARD_E4S_V3,STANDARD_E64S_V3,STANDARD_E8S_V3,STANDARD_A3,STANDARD_A4,STANDARD_A5,STANDARD_A6,STANDARD_A7' (Code:InvalidDocumentErrorCode)

@Xue Shan Zhao<mailto:Xue.Zhao@microsoft.com> can you or one of your team help me here.  As I understand it SU12 was deployed to FairFax earlier in Feb.  I’m still seeing failures when I try and use the new Ev3 VM sizes.

Guy

**Comment by guyhay** [comment]
Is there a delay in pushing this change to production?

I just re-submitted a job to update the template earlier today.  It’s still failing .  full details here Pipelines - Run 47330 logs (azure.com)<https://dev.azure.com/azurequickstarts/azure-quickstart-templates/_build/results?buildId=47330&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=7e8496a1-77f9-5e6b-1973-c1d3d4714959>

Guy

From: Silan Hu <silahu@microsoft.com>
Sent: Sunday, February 28, 2021 23:38
To: Xue Shan Zhao <Xue.Zhao@microsoft.com>; Guy Haycock <guyhay@microsoft.com>; Azure/azure-quickstart-templates <reply@reply.github.com>; Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Mimi Gentz <mimig@microsoft.com>; Alicia Li (COSMOS) <ali@microsoft.com>; Guy Haycock <guyhay@microsoft.com>
Subject: RE: [Azure/azure-quickstart-templates] Update VM size to Ev3 and add VM parameters, 4.0 (#8802)

Hi, all

I have enabled EV3 for all public regions.

Thanks
Silan

From: Xue Shan Zhao <Xue.Zhao@microsoft.com<mailto:Xue.Zhao@microsoft.com>>
Sent: Saturday, February 27, 2021 7:22 AM
To: Guy Haycock <guyhay@microsoft.com<mailto:guyhay@microsoft.com>>; Azure/azure-quickstart-templates <reply@reply.github.com<mailto:reply@reply.github.com>>; Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com<mailto:azure-quickstart-templates@noreply.github.com>>; Silan Hu <silahu@microsoft.com<mailto:silahu@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Mimi Gentz <mimig@microsoft.com<mailto:mimig@microsoft.com>>
Subject: RE: [Azure/azure-quickstart-templates] Update VM size to Ev3 and add VM parameters, 4.0 (#8802)

Loop Silan for help. @Silan Hu<mailto:silahu@microsoft.com>

From: Guy Haycock <guyhay@microsoft.com<mailto:guyhay@microsoft.com>>
Sent: 2021年2月27日 7:08
To: Azure/azure-quickstart-templates <reply@reply.github.com<mailto:reply@reply.github.com>>; Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com<mailto:azure-quickstart-templates@noreply.github.com>>; Xue Shan Zhao <Xue.Zhao@microsoft.com<mailto:Xue.Zhao@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Mimi Gentz <mimig@microsoft.com<mailto:mimig@microsoft.com>>
Subject: RE: [Azure/azure-quickstart-templates] Update VM size to Ev3 and add VM parameters, 4.0 (#8802)

I’ll have to go find out.  I see that it’s still rejecting on
Status Message: DeploymentDocument 'CsmDocument_2_0' failed the validation. Error: 'VM size 'standard_e4_v3' provided in the request is not allowed. Valid values are: STANDARD_D12,STANDARD_D12_V2,STANDARD_D13,STANDARD_D13_V2,STANDARD_D14,STANDARD_D14_V2,STANDARD_D3,STANDARD_D3_V2,STANDARD_D4,STANDARD_D4_V2,STANDARD_D5_V2,STANDARD_DS12_V2,STANDARD_DS13_V2,STANDARD_DS14_V2,STANDARD_DS3_V2,STANDARD_DS4_V2,STANDARD_DS5_V2,STANDARD_A2_V2,STANDARD_E16S_V3,STANDARD_E20S_V3,STANDARD_E2S_V3,STANDARD_E32S_V3,STANDARD_E4S_V3,STANDARD_E64S_V3,STANDARD_E8S_V3,STANDARD_A3,STANDARD_A4,STANDARD_A5,STANDARD_A6,STANDARD_A7' (Code:InvalidDocumentErrorCode)

@Xue Shan Zhao<mailto:Xue.Zhao@microsoft.com> can you or one of your team help me here.  As I understand it SU12 was deployed to FairFax earlier in Feb.  I’m still seeing failures when I try and use the new Ev3 VM sizes.

Guy

**Comment by guyhay** [comment]
I saw the region is usgovvirginia right? There is still two provisioning subscriptions don’t have enough cores for ev3 so that I didn’t enable it in Fairfax.

Do you also want me to enable it for Fairfax?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Guy Haycock <guyhay@microsoft.com>
Sent: Monday, March 1, 2021 11:33:01 PM
To: Silan Hu <silahu@microsoft.com>; Xue Shan Zhao <Xue.Zhao@microsoft.com>; Azure/azure-quickstart-templates <reply@reply.github.com>; Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Mimi Gentz <mimig@microsoft.com>; Alicia Li (COSMOS) <ali@microsoft.com>
Subject: RE: [Azure/azure-quickstart-templates] Update VM size to Ev3 and add VM parameters, 4.0 (#8802)


Is there a delay in pushing this change to production?



I just re-submitted a job to update the template earlier today.  It’s still failing .  full details here Pipelines - Run 47330 logs (azure.com)<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fazurequickstarts%2Fazure-quickstart-templates%2F_build%2Fresults%3FbuildId%3D47330%26view%3Dlogs%26j%3D275f1d19-1bd8-5591-b06b-07d489ea915a%26t%3D7e8496a1-77f9-5e6b-1973-c1d3d4714959&data=04%7C01%7Csilahu%40microsoft.com%7C6f17d7289b5c445c9d6f08d8dcc74c9c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637502095863164335%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Hf33CpxNpAFt8eREinIk8Q%2FJHmVrEahfblH7yqJwMkU%3D&reserved=0>



Guy



From: Silan Hu <silahu@microsoft.com>
Sent: Sunday, February 28, 2021 23:38
To: Xue Shan Zhao <Xue.Zhao@microsoft.com>; Guy Haycock <guyhay@microsoft.com>; Azure/azure-quickstart-templates <reply@reply.github.com>; Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Mimi Gentz <mimig@microsoft.com>; Alicia Li (COSMOS) <ali@microsoft.com>; Guy Haycock <guyhay@microsoft.com>
Subject: RE: [Azure/azure-quickstart-templates] Update VM size to Ev3 and add VM parameters, 4.0 (#8802)



Hi, all



I have enabled EV3 for all public regions.



Thanks

Silan



From: Xue Shan Zhao <Xue.Zhao@microsoft.com<mailto:Xue.Zhao@microsoft.com>>
Sent: Saturday, February 27, 2021 7:22 AM
To: Guy Haycock <guyhay@microsoft.com<mailto:guyhay@microsoft.com>>; Azure/azure-quickstart-templates <reply@reply.github.com<mailto:reply@reply.github.com>>; Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com<mailto:azure-quickstart-templates@noreply.github.com>>; Silan Hu <silahu@microsoft.com<mailto:silahu@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Mimi Gentz <mimig@microsoft.com<mailto:mimig@microsoft.com>>
Subject: RE: [Azure/azure-quickstart-templates] Update VM size to Ev3 and add VM parameters, 4.0 (#8802)



Loop Silan for help. @Silan Hu<mailto:silahu@microsoft.com>



From: Guy Haycock <guyhay@microsoft.com<mailto:guyhay@microsoft.com>>
Sent: 2021年2月27日 7:08
To: Azure/azure-quickstart-templates <reply@reply.github.com<mailto:reply@reply.github.com>>; Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com<mailto:azure-quickstart-templates@noreply.github.com>>; Xue Shan Zhao <Xue.Zhao@microsoft.com<mailto:Xue.Zhao@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Mimi Gentz <mimig@microsoft.com<mailto:mimig@microsoft.com>>
Subject: RE: [Azure/azure-quickstart-templates] Update VM size to Ev3 and add VM parameters, 4.0 (#8802)



I’ll have to go find out.  I see that it’s still rejecting on

Status Message: DeploymentDocument 'CsmDocument_2_0' failed the validation. Error: 'VM size 'standard_e4_v3' provided in the request is not allowed. Valid values are: STANDARD_D12,STANDARD_D12_V2,STANDARD_D13,STANDARD_D13_V2,STANDARD_D14,STANDARD_D14_V2,STANDARD_D3,STANDARD_D3_V2,STANDARD_D4,STANDARD_D4_V2,STANDARD_D5_V2,STANDARD_DS12_V2,STANDARD_DS13_V2,STANDARD_DS14_V2,STANDARD_DS3_V2,STANDARD_DS4_V2,STANDARD_DS5_V2,STANDARD_A2_V2,STANDARD_E16S_V3,STANDARD_E20S_V3,STANDARD_E2S_V3,STANDARD_E32S_V3,STANDARD_E4S_V3,STANDARD_E64S_V3,STANDARD_E8S_V3,STANDARD_A3,STANDARD_A4,STANDARD_A5,STANDARD_A6,STANDARD_A7' (Code:InvalidDocumentErrorCode)



@Xue Shan Zhao<mailto:Xue.Zhao@microsoft.com> can you or one of your team help me here.  As I understand it SU12 was deployed to FairFax earlier in Feb.  I’m still seeing failures when I try and use the new Ev3 VM sizes.



Guy

**Comment by guyhay** [comment]
Yes please for Fairfax.  Without that I can’t update any quick start templates.  Are there other .gov regions that don’t have ev3?

Guy

**Comment by guyhay** [comment]
Is there some minimum quota that Mimi and I should be thinking about that is needed to add a new VM series?

Guy

**Comment by guyhay** [comment]
Hi, Guy



I have enabled EV3 for FairFax. But there are still provisioning subscriptions which don’t have enough quota so if customer choose ev3 in usgoviowa and usdodcentral it may be failed due to provisioning subscription doesn’t have enough cores.  For this problem we have another email thread and you also in it, Sanjeev is handling this.



When we try to enable a new VM serial we usually get 1000-2000 cores for non hero regions, for hero regions I think we can get more than 5000? But it also depends the usage and whether we want to make this VM as default sku, if it’s true we may need more quota. And we also have a monitor to monitor the usage of each sku, if it’s large than a threshold we will file sev3 or sev2 ICM ticket and will automatically open a work item for capacity team to increase the quota.

Also we need to check the meter id and price for this VM. And considerate the exclude filter.



Thanks

Silan

________________________________
From: Guy Haycock <guyhay@microsoft.com>
Sent: Tuesday, March 2, 2021 6:58:59 AM
To: Silan Hu <silahu@microsoft.com>; Xue Shan Zhao <Xue.Zhao@microsoft.com>; Azure/azure-quickstart-templates <reply@reply.github.com>; Azure/azure-quickstart-templates <azure-quickstart-templates@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Mimi Gentz <mimig@microsoft.com>; Alicia Li (COSMOS) <ali@microsoft.com>
Subject: RE: [Azure/azure-quickstart-templates] Update VM size to Ev3 and add VM parameters, 4.0 (#8802)


Is there some minimum quota that Mimi and I should be thinking about that is needed to add a new VM series?



Guy

**Comment by guyhay** [comment]
@Brian Moore (AZURE RESOURCE MANAGER)<mailto:bmoore@microsoft.com>, I believe we are now unblocked.

Guy
[Graphical user interface, text, application, email  Description automatically generated]

**Comment by guyhay** [comment]
Thank you.  This has solved the first immediate problem of updating QuickStart templates.

Guy
[Graphical user interface, text, application, email  Description automatically generated]

**Comment by guyhay** [comment]
@bmoore-msft Morning, I think this is ready to integrate having solved the FF ev3 issues.

**Comment by guyhay** [comment]
Thank you.  @Brian Moore (AZURE RESOURCE MANAGER)<mailto:bmoore@microsoft.com> the tests are now passing and I think this updates is ready to commit.

Guy

**Pull request merged**
