### PR TITLE
openshift prepMaster epel repo

### PR DESCRIPTION
**Pull request by borehack**
please merge new epel repo ... @haroldwongms 
without this change the template will not work anymore.

### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

* update epel repository

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@borehack__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by borehack** [comment]
haven't change anything in the deployment or parameter json files. can you explain what is the problem?
I have just changed one line in prepMaster.sh and prepNode.sh

**Comment by haroldwongms** [comment]
I already made a PR 6 days ago with the changes. My changes showed all tests passed but am still waiting for it to be merged.

**Comment by borehack** [comment]
@haroldwongms  sorry havn't seen your PR... will close mine. interesting why my checks fail as I havn't changed anything in the json files.

**Comment by haroldwongms** [comment]
I looked at the tests for your PR and the tests tried to deploy the ARM template versus just checking the validity of the scripts.  TravisCI cannot validate my templates automatically since one of the parameters (keyvault) cannot be auto generated. Looks like mine only tested the scripts.

**Pull request closed without merging**
