### PR TITLE
201-rbac-multipleprincipals-maps

### PR DESCRIPTION
**Pull request by stack111**
### Best Practice Checklist

1. uri's compatible with all clouds (Stack, China, Government)
N/A
2. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
N/A
3. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
Yes
4. Folder names for artifacts (nestedtemplates, scripts, DSC)
N/A
5. Use literal values for apiVersion (no variables)
Yes
6. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
Yes
7. $schema and other uris use https
Yes
8. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
Yes
9. Update the metadata.json with the current date
Yes

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog
Azure Maps supports Azure AD RBAC for data-plane, I would like to provide samples to quick start template authoring to use this feature. Once this is approved I plan to create some 3xx and scenarios using App Service.

* Added 201-rbac-multipleprincipals-maps

### CODE REVIEW

**Comment by stack111** [comment]
I expect CI to fail:

- the service principal used does not have User Access Administrator role
- the princpals will not exist in the CI subscription's Azure AD directory.

Anyone who wants to use this quickstart must provide the principal id's and provide User Access Adminstrator permissions.

**Comment by bmoore-msft** [comment]
see comments in #6601 and apply the same here...

**Comment by stack111** [comment]
@bmoore-msft this is an interesting question, how do we provide principal ids which do not exist the Azure AD tenants?

**Comment by bmoore-msft** [comment]
This one isn't terribly different that the other so probably not worth a separate sample to maintain... lmk if I'm missing anything.

**Comment by stack111** [comment]
> This one isn't terribly different that the other so probably not worth a separate sample to maintain... lmk if I'm missing anything.

Ok as long as the idea is clear, we support another 201-rbac version which does have assigned principal ids as well.

**Pull request closed without merging**
