### PR TITLE
Updated trusted launch template default to 2022 azure edition

### PR DESCRIPTION
**Pull request by AjKundnani**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Added support for Windows Server 2022 Gen2 images in template.
* Changed default OS image to Windows Server 2022 Azure Edition.
* Updated UIDefinition to be more aligned to vm-simple-windows template
* Updated bicep file

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@cynthn - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by azure-quickstarts** [comment]
@cynthn - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by AjKundnani** [comment]
#sign-off

**Comment by AjKundnani** [comment]
@bmoore-msft - Kindly review

**Comment by azure-quickstarts** [comment]
@cynthn - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by AjKundnani** [comment]
@bmoore-msft - Is it mandatory to remove ARM template? Originally both ARM and Bicep file were available in repository.

If mandatory, how do we share sample ARM template file if customer is still on ARM and not Bicep?

**Comment by bmoore-msft** [comment]
azuredeploy.json is automatically generated when the sample is merged.

**Pull request merged**
