### PR TITLE
docker-swarm: Fix typo in template output cmd

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
Little typo fix.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ahmetalpbalkan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ahmetb). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@ahmetalpbalkan let's run this through the test bot, can you supply valid dummy values in parameters file that will allow this to deploy successfully?

**Comment by ahmetalpbalkan** [comment]
@singhkay I deployed this fine manually. Deployment of this requires a DNS name which I guess needs to be unique. How can I pass such a value so that it successfully gets deployed every time bot runs this?

**Comment by ahmetalpbalkan** [comment]
hmm actually maybe I can even get rid of the dns name altogether by using

    swarm-[uniqueString(subs-id/resource-group)]

nobody really cares about the FQDN anyways.

**Comment by singhkay** [comment]
@template-deploy-bot test this please

**Comment by singhkay** [comment]
@template-deploy-bot test this please

**Pull request merged**
