### PR TITLE
Updates ARM template files - IoT Device Provisioning Service

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template files for [quickstart](https://docs.microsoft.com/azure/iot-dps/quick-setup-auto-provision-rm) article.
- Adds quickstart article's author to `docOwner` in _metadata.json_.
- Updates _README.md_ with link to the quickstart article.

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@wesmc7777 - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
Gov build failed with error: An internal error occurred while activating IotHub. ResourcePool not found.

Closed/reopened to reinitiate the build process. The template and parameter files weren't changed in this PR. Noticed the directory showed a failed Gov status test on 11/23/2020.

**Comment by bmoore-msft** [comment]
@wesmc7777 - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@wesmc7777 - check this PR for updates that may be needed to documentation that references this sample.

**Comment by wesmc7777** [comment]
Looks fine to me. I don't see any changes here that would require updates to the docs

**Comment by davidsmatlak** [comment]
@wesmc7777 Any concerns with the Gov build failure? See my [prior comment](https://github.com/Azure/azure-quickstart-templates/pull/8587#issuecomment-740130009). Thanks.

**Comment by wesmc7777** [comment]
@davidsmatlak honestly not sure yet.  I'm looking closer at it to see if I can see anything

**Comment by wesmc7777** [comment]
@davidsmatlak I don't know what would cause this "ResourcePool" not found error in the gov environment...

```
2020-12-07T19:54:53.5237806Z New-AzResourceGroupDeployment : 7:54:53 PM - The deployment 'mainTemplate-deployment' failed with error(s). Showing 1 out of 1 error(s).
2020-12-07T19:54:53.5239972Z Status Message: An internal error occurred while activating IotHub (Code: IotHubActivationFailed)
2020-12-07T19:54:53.5241483Z  - ResourcePool not found (Code:IotHubActivationFailed)
```

**Comment by davidsmatlak** [comment]
@wesmc7777 submitted PR #8589 to resolve the build problem and included my changes to the _README.md_ and _metadata.json_. Thanks!

Closing this PR as **Do not merge**.

**Pull request closed without merging**
