### PR TITLE
Crucial Updates for Blockchain templates

### PR DESCRIPTION
**Pull request by Duality-CDOO**
Anyone attempting to deploy using the blockchain templates currently will not be able to set up a Bitcoin node, Dash node, connect to the correct Syscoin blockchain, and Shadowcoin has been replaced by Particl.

These templates must be updated ASAP.

@bmoore-msft 

### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

* Add Dynamic install script
* Add dynamic.md and dynamic.svg
* Update Syscoin to version 4.0.3 and connect to the correct blockchain
* Add quickstart button to syscoin.md and add syscoin.png
* Removed Shadowcoin as it has changed/rebranded to Particl
* Added Particl install script
* Add quickstart button to particl.md and add particl.png
* Updated all API's used in azuredeploy.json to latest versions
* updated blockchain/metadata.json githubUsername and dateUpdated
* Refactored azuredeploy.json and removed shadow, added particl
* Add Bitcoin to template (md, image, quickstart, install script, azuredeploy.json)
* Add Dash to template (md, image, quickstart, install script, azuredeploy.json)

### CODE REVIEW

**Comment by Duality-CDOO** [comment]
image

I get this error, however, I have the __artifactsLocationSasToken referenced the same as Azure documentation states:

image

**Comment by Duality-CDOO** [comment]
This is failing the 'Run Best Practice Tests' and 'Deploy mainTemplate' tests.

The error is that _artifactsLocationSasToken is not referenced, but I am unsure where to reference it, fileUris? 

I tried adding it to this line:
```"[concat(parameters('_artifactsLocation'), 'scripts/', parameters('blockchainSoftware'), '.sh')]"```
it passed the 'Run Best Practice Tests' but then fails the 'Deploy mainTemplate' test with an error complaining that the template is incorrect.

The azuredeploy.json file does have this declared:
```"_artifactsLocation": {
      "type": "string",
      "metadata": {
        "description": "The base URI where artifacts required by this template are located. When the template is deployed using the accompanying scripts, a private location in the subscription will be used and this value will be automatically generated."
      },
      "defaultValue": "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/blockchain/"
    },
    "_artifactsLocationSasToken": {
      "type": "securestring",
      "metadata": {
        "description": "The sasToken required to access _artifactsLocation.  When the template is deployed using the accompanying scripts, a sasToken will be automatically generated."
      },
      "defaultValue": ""```

**Comment by Duality-CDOO** [comment]
This is failing the 'Run Best Practice Tests' and 'Deploy mainTemplate' tests.

The error is that _artifactsLocationSasToken is not referenced.

image

The azuredeploy.json file does have this declared:
```
"_artifactsLocation": {
      "type": "string",
      "metadata": {
        "description": "The base URI where artifacts required by this template are located. When the template is deployed using the accompanying scripts, a private location in the subscription will be used and this value will be automatically generated."
      },
      "defaultValue": "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/blockchain/"
    },
    "_artifactsLocationSasToken": {
      "type": "securestring",
      "metadata": {
        "description": "The sasToken required to access _artifactsLocation.  When the template is deployed using the accompanying scripts, a sasToken will be automatically generated."
      },
      "defaultValue": ""
```
image

I really require help getting this to pass the tests if anyone knows how to fix this issue.

**Comment by Duality-CDOO** [comment]
This commit is ready for review.

**Comment by bmoore-msft** [comment]
@Duality-CDOO  - I'm going to close this as it contains changes from 2 different samples (PR must only contain changes from one sample) and the merge conflicts...  if you can clean those up, please resubmit in 2 PRs if you need both changes

**Comment by Duality-CDOO** [comment]
> @Duality-CDOO - I'm going to close this as it contains changes from 2 different samples (PR must only contain changes from one sample) and the merge conflicts... if you can clean those up, please resubmit in 2 PRs if you need both changes

I will repair this. Somewhere the permissions were touched and changed for those two files in  puppet-enterprise-rhel-win. I can fix this PR if you wish to reopen it.

**Comment by Duality-CDOO** [comment]
@bmoore-msft I will resubmit this PR without the accidental touches to the permissions of those two files 😛 

Please could you merge ASAP as the blockchain templates are grossly out-of-date.

**Pull request closed without merging**
