### PR TITLE
multi-api add bicep support

### PR DESCRIPTION
**Pull request by markjbrown**
# PR Checklist

## Changelog

* add bicep support

### CODE REVIEW

**Comment by markjbrown** [comment]
@bmoore-msft I tested this without the empty capabilities property but because it won't work because I use a formula for the capabilities property for the databaseAccount resource. If I remove it from line 105 it throws an exception when deployed.

Otherwise, this PR is good to go.

Thanks.

**Comment by bmoore-msft** [comment]
So if the capabilities property is not present for SQL deployment fails (which I'd expect if there's no check for the property before referencing it) but it doesn't for MongoDB?  Looking at the sample as-is I'd expect it to fail if the user chooses mongo...

If the property is optional the solution would be something like:

```
capabilities: contains(apiType[api], 'capabilities') ? apiType[api].capabilities : null
```

**Comment by markjbrown** [comment]
@bmoore-msft Oh ok. Advance stuff for me there :) I'll update the PR with that. Thanks

**Comment by markjbrown** [comment]
Not sure why this failed. Looks temporal. Restarting.

**Comment by markjbrown** [comment]
Hey @bmoore-msft I'm having trouble debugging this template. I took your advice for how to fix the capabilities property but the resulting template I built from the bicep file throws an exception.

Could you take a look at this possibly?

Thanks!

**Pull request merged**
