### PR TITLE
MOVE: 101-vm-simple-windows to quickstarts\microsoft.compute

### PR DESCRIPTION
**Pull request by akhilthomas011**
…e-windows

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@tfitzmac - this appears to be a "Move" that will need a manual doc update

**Comment by mumian** [comment]
@cynthn, @tfitzmac - I will take this one.

**Comment by mumian** [comment]
local branch for the fixes: 0511-quickstarts-vm-win

**Comment by mumian** [comment]
https://github.com/MicrosoftDocs/azure-docs-pr/pull/158320

**Comment by mumian** [comment]
https://github.com/MicrosoftDocs/azure-docs-pr/pull/158320 is merged.

**Pull request merged**
