### PR TITLE
Updates ARM template files - Cache for Redis

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template used in ARM template [quickstart](https://docs.microsoft.com/azure/azure-cache-for-redis/cache-redis-cache-arm-provision) article.
- Adds quickstart article's author to `docOwner` in _metadata.json_.
- Updates `Microsoft.Cache/Redis` resource `type` to the latest `apiVersion`.
- fixes indentation.

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@yegu-ms - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@yegu-ms - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
Public build failed with a scope error. Will close and reopen the pull request to rerun the build.

**Comment by davidsmatlak** [comment]
To fix a Gov build error, reverts `Microsoft.Cache/redis/providers/diagnosticsettings` to `apiVersion 2017-05-01-preview`.

**Comment by bmoore-msft** [comment]
@yegu-ms - check this PR for updates that may be needed to documentation that references this sample.

**Pull request merged**
