### PR TITLE
Changed values to match diagram and simplified NAT gateway deployment

### PR DESCRIPTION
**Pull request by asudbring**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by azure-quickstarts** [comment]
@asudbring - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by asudbring** [comment]
@alex-frankel 
I did this separate PR for the bicep file because I thought we had to do both. If this one is merged, will the ARM template autogenerate or is there something additional I need to do?

Thanks for your help with this!

-allen

**Comment by alex-frankel** [comment]
yep, just merged it. We should be good to go. There might be some time before the background generation of the JSON file finishes running.

**Comment by asudbring** [comment]
@alex-frankel 
Thank you again!

**Pull request merged**
