### PR TITLE
Improved 101-vm-multiple-data-disk

### PR DESCRIPTION
**Pull request by sk-bln**
In my fork, I did the following changes to 101-vm-multiple-data-disk
- Added a selection of instance types (Standard_D1 to Standard_D4)
- Changed the location to the location of the created resource group
- Added a custom script extension to the VM that creates &formats a storage pool out of the four data disks

Regards
Steffen

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sk-bln__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@sk-bln Can you sign the CLA and back out the change that changes the username of the author from metadata.json file? Thanks!

**Comment by sk-bln** [comment]
Hello Kay,

I signed the CLA, my manager is on vacation so this might take some time.
I undid the author change. However, your bot complains about the author not being me…

Regards
Steffen

**Comment by singhkay** [comment]
@sk-bln Now that I see the changes you made, this looks like a new 201 template you can submit. I would suggest opening another PR with this as a 201-vm-storage-pool so the important scenario is captured in the name

**Pull request closed without merging**
