### PR TITLE
Revert "removing allowedSizes altogether" We need Allowed Sizes.

### PR DESCRIPTION
**Pull request by gjackson-eip**
This reverts commit 2e536828734712fcc29a96402b9771f7333f9576.

### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

*
*
*

### CODE REVIEW

**Comment by bmoore-msft** [comment]
Why do we need allowedSizes?  It's bad practice for the repo and requires maint like this...

**Comment by gjackson-eip** [comment]
Brian,

We only support certain Azure sizes for our images but if we remove it how
will the clients choose what size the VM needs to be?

The default one listed was only for a test to get the template create.
After testing we select which sizes will give us the correct performance
our images.

Do you want me to turn it into a text box instead of a drop down box?

Thanks,
Gerald


Sent from my iPhone

On Mar 15, 2018, at 3:35 PM, Brian Moore <notifications@github.com> wrote:

Why do we need allowedSizes? It's bad practice for the repo and requires
maint like this...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/azure-quickstart-templates/pull/4349#issuecomment-373497343>,
or mute the thread

**Comment by bmoore-msft** [comment]
What's the actual requirement?  Is it a feature of the size?  Not that the existing vhd may be in a storage account of one type, that may not be supported by the VM size, so restricting the sizes can make that problem worse...

**Comment by gjackson-eip** [comment]
Brian,

Ok.  I will change it to text box.  I will have to update our documentation
but that is not a big issue.

I will cancel the pull request so I can change the code.

Thanks,
Gerald

Sent from my iPhone

On Mar 15, 2018, at 3:55 PM, Brian Moore <notifications@github.com> wrote:

What's the actual requirement? Is it a feature of the size? Not that the
existing vhd may be in a storage account of one type, that may not be
supported by the VM size, so restricting the sizes can make that problem
worse...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/azure-quickstart-templates/pull/4349#issuecomment-373503033>,
or mute the thread

**Pull request closed without merging**
