### PR TITLE
Adapted the template 201-api-management-create-with-vnet to deploy th…

### PR DESCRIPTION
**Pull request by mikemowgli**
Adapted the template 201-api-management-create-with-vnet to deploy the APIM instance in Internal network mode, with respect to NSG rules to secure the instance

### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

*
*
*

### CODE REVIEW

**Comment by mikemowgli** [comment]
I saw the CI job failed. However I already tested the template. I'm not used to pull request. What's the deal now?

**Comment by mikemowgli** [comment]
The CI job says: 'The template resource '' at line '1' and column '2332' is not valid. The name property cannot be null or empty.'
Even when I trim carriage returns from the template file, I cannot see anything wrong there. Plus, the template I based this one on gives the same issue...

**Comment by bmoore-msft** [comment]
@mikemowgli - Ok, CI is running now but we need valid parameter values for CI, check the readme/contribution guide

**Comment by mikemowgli** [comment]
so what happened? the last CI job failed, but no log...

**Comment by bmoore-msft** [comment]
Check the readme/contribution guide for valid parameter values needed for CI.

**Comment by bmoore-msft** [comment]
Closing abandoned request - please reopen if you can address the feedback.

**Pull request closed without merging**
