### PR TITLE
Lapstack fix

### PR DESCRIPTION
**Pull request by gatneil**
LAD version and Ubuntu version were mismatched; fixed with auto-upgrade minor version of LAD

### CODE REVIEW

**Comment by singhkay** [comment]
@sedouard Looks like this one returned a more detailed server:undefined error after your fix yesterday. Does this give any info? 

```
Server Error:{
    "error": {
        "code": "ENOTFOUND",
        "errno": "ENOTFOUND",
        "syscall": "getaddrinfo",
        "hostname": "arm-validator.40.118.211.57.xip.io"
    }
}
```

**Comment by gatneil** [comment]
@singhkay @sedouard Is the backlog for Travis CI super long or the like? This template usually deploys within 10-15 minutes, but it looks like it is timing out before this template is being deployed.

**Comment by singhkay** [comment]
@gatneil Probably because the template is using the Standard_A1 size. Try deploying a bigger size?

**Comment by singhkay** [comment]
lgtm, merged

**Pull request merged**
