### PR TITLE
New Azure Automation State Configuration Template

### PR DESCRIPTION
**Pull request by valainisgt**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by valainisgt** [comment]
Pipeline fails due to an 'unused' variable `Unreferenced variable: $fxv#0`. This line in my bicep file is what is causing the issue:

`loadTextContent('dsc/configuration.ps1')`

Doing a compile against my bicep file generates variable $fxv#0 and it is being used. Not sure what the problem is here.

**Review by bmoore-msft — CHANGES_REQUESTED** [review]
check the pipeline results for the BP changes that are needed

**Comment by valainisgt** [comment]
First, I seem to be suffering from 'works in my environment'. But maybe more accurately 'works with my subscription/region'. I have deployed this template multiple times. Each time it runs to completion without error. My deployment command is:

`New-AzResourceGroupDeployment -ResourceGroup $aResourceGroup -TemplateFile main.bicep`

Second, the AzQuickStarts-MAC deployment has an issue in the 'Run BPA' job. I am getting the following error:

Azure.Deployments.Core.Exceptions.ExpressionException: The language expression property 'keys' can't be evaluated.

I am not sure what the issue is here. This usage should be fine as documented [here](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-resource#list) and [here](https://learn.microsoft.com/en-us/rest/api/automation/keys/list-by-automation-account).

**Comment by bmoore-msft** [comment]
Just focus on getting a successful deployment - something seems off w/ DSC

**Comment by valainisgt** [comment]
Using the DSC extension via ARM has inconsistent results. However, using an `Az` command like `Register-AzAutomationDscNode` works every time (that I have seen). Closing this PR as this template just won't work consistently.

**Pull request closed without merging**
