### PR TITLE
Azure IaaS V2 end-to-end

### PR DESCRIPTION
**Pull request by srakesh28**
Request to Add this Template to Azure repository , It provides example on how to deploy IaaS V2 Infrastructure on Azure with best practices in 3 simple steps and creates Automated 3 Tier Architecture from scratch with all right security controls is can be used for Demo of DevOps model on Azure.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@srakesh28__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@srakesh28 Just had a chat with @telmosampaio who's working on something similar. Maybe you guys can work together to contribute one template that covers all the scenarios!

**Comment by azurecla** [comment]
__@srakesh28__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by telmosampaio** [comment]
@srakesh28 let me know when you have a few minutes to talk about this. I have a project on doing exactly this (IaaS v2 end-to-end) going on with the CSI (documentation) team at Microsoft. Maybe we can join efforts.

**Comment by srakesh28** [comment]
Sure let talk tomorrow around 10:00 am?


Sent from my mobile
Rakesh Shah
408-391-9610

**Comment by singhkay** [comment]
@srakesh28 @telmosampaio Closing this since it can be merged with existing work

**Pull request closed without merging**
