### PR TITLE
Beta 2.0- Secure installation of SonarQube

### PR DESCRIPTION
**Pull request by hkamel**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use resourceGroup().location for resource locations
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/bp-checklist.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

* Support Secure SonarQube installation.
* Fixing an issue with firewall rule name in sub-template (azureDBDeploy.json) 
* Provide more documentations around changing the generated self-signed certificate with a production/ trusted certificate.
* Provide two output variables (Secure/non-secure) URLs
* Provide default value for Soanrqube VM name
* Moving SonarQube version variable from the DSC file to the main template as a variable to easily fork the repo and change the supported version
* Update SonarQube version used for the installation with the latest LTS version

### CODE REVIEW

**Comment by singhkays** [comment]
@hkamel Looks like the deployment is failing with this error. Can you check? 

```
    "error": "error: Deployment provisioning state was not successful\nerror: The resource operation completed with terminal provisioning state 'Failed'.\nerror: VM has reported a failure when processing extension 'configureAppVM_DSC'. Error message: \"The DSC Extension received an incorrect input: A parameter cannot be found that matches parameter name 'sonarQubeVersion'.\n\nAnother common error is to specify parameters of type PSCredential without an explicit type. Please be sure to use a typed parameter in DSC Configuration, for example:\n\n    configuration Example {\n        param([PSCredential] $UserAccount)\n        ...\n    }.\nPlease correct the input and retry executing the extension.\".\n",
```

**Comment by hkamel** [comment]
Updating the parameters file to fix CI

**Comment by hkamel** [comment]
Thank you @singhkays it's all good now

**Comment by singhkays** [comment]
lgtm, merged

**Pull request merged**
