### PR TITLE
Ams2

### PR DESCRIPTION
**Pull request by IngridAtMicrosoft**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by IngridAtMicrosoft** [comment]
#sign-off

**Comment by IngridAtMicrosoft** [comment]
@bmoore-msft Hi there.  Can this get merged into master?

**Comment by bmoore-msft** [comment]
Check the pipeline results for some changes that need to be made - can do a full code review after that...

**Comment by bmoore-msft** [comment]
Closing abandoned request - please reopen if you can address the feedback.

**Comment by bmoore-msft** [comment]
Closing abandoned request - please reopen if you can address the feedback.

**Pull request closed without merging**
