### PR TITLE
Support access endpoint type in Azure logic apps Integration Service …

### PR DESCRIPTION
**Pull request by laveeshb**
…Environment template

The parameter is documented here -- https://docs.microsoft.com/en-us/azure/logic-apps/connect-virtual-network-vnet-isolated-environment#create-your-ise

### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

* Add support for access endpoint type in Azure logic apps Integration Service Environment

### CODE REVIEW

**Comment by laveeshb** [comment]
@brandonh-msft I need some help with the checks. The failure in public cloud is retryable; I checked the service side logs and found a corner case error with which ISE provisioning fails sometimes. How can I retry the check?

Regarding Fairfax, ISE is not supported there yet.

**Comment by brandonh-msft** [comment]
The vast majoriy of PRs in this repo are failing checks RN. If you want to re-run the checks, just re-run the AzDO build pipelines. I'll try and do this now.

**Comment by brandonh-msft** [comment]
Alas I do not have permission to do so.

**Comment by laveeshb** [comment]
@brandonh-msft I reached out to you as I think you are one of the administrators of this repo and could help me with the checks. By the way, I have tested the changes by deploying it myself. Can you help complete the PR if the checks are failing anyway?

**Comment by bmoore-msft** [comment]
re: fairfax see: https://github.com/Azure/azure-quickstart-templates/tree/master/1-CONTRIBUTION-GUIDE#cloud-support

To run the pipeline again, just add a commit to the PR (the fairfax change will work)

**Comment by laveeshb** [comment]
@bmoore-msft thanks for your recommendation. I made the necessary fixes and now the PR checks succeeded. Could you complete the PR?

**Pull request merged**
