### PR TITLE
Updating READMEs of SQL VM templates to be more clear to users

### PR DESCRIPTION
**Pull request by ninarn**
### Contributing guide
https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md

### Changelog
*
*
*
*
*

### Description of the change

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ninarn__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ninarn). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ninarn** [comment]
I'm confused as to how my pull request failed the check tests as I only changed the README markdown files. Could you please let me know how to proceed?

**Comment by singhkay** [comment]
@ninarn Some of these are expected failures since they require existing resources. You can click the "details" or "red cross" to check the logs of what failed and why.

**Comment by ninarn** [comment]
It appears that these failures have to do with accessing the nested templates. Does this prevent my pull request from being accepted? There are not files I touched, I have no way of determining the cause of the failure or fixing them.

**Comment by singhkay** [comment]
@ninarn Looks like these templates are broken. I found that the download link has the name of the template called "101-vm-sql-full-autobackup" but the template in the repo is actually called 201-vm-sql-full-autobackup. Can you check and fix these as well?

**Comment by singhkay** [comment]
@ninarn I see you changed the links in the readme file but the actual template files have similar issues as well.

**Comment by ninarn** [comment]
Thanks, Kay. I understand what you were referring to now. I have fixed those errors in the template

**Comment by singhkay** [comment]
@ninarn Thanks for fixing. I'll let @weidaiMS fix the rest of the errors in the new PR #2040

**Pull request merged**
