### PR TITLE
Virtual Network Manager Creation Template - Bicep

### PR DESCRIPTION
**Pull request by mbrat2005**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by mbrat2005** [comment]
Automated validation fails due to role assignment and new resource group creation

**Comment by alex-frankel** [comment]
> Automated validation fails due to role assignment and new resource group creation

Not sure I understand this one. Both role assignments and RG creation should be possible. The template will need to be a subscription-scoped template if you need to do that: https://github.com/Azure/azure-quickstart-templates/tree/master/subscription-deployments

**Comment by mbrat2005** [comment]
> > Automated validation fails due to role assignment and new resource group creation
> 
> Not sure I understand this one. Both role assignments and RG creation should be possible. The template will need to be a subscription-scoped template if you need to do that: https://github.com/Azure/azure-quickstart-templates/tree/master/subscription-deployments

I'll switch back to automated validation and confirm / get a screenshot.

**Comment by mbrat2005** [comment]
@alex-frankel Oh, I see--the deployment needs to be in the 'subscription-deployments' directory to target that scope. 

In this case, all components except an Azure Policy definition and assignment are resource group scope. The Policy is only supported at the subscription scope. Should I move the whole sample to the 'subscription-deployments' directory?

**Comment by alex-frankel** [comment]
> @alex-frankel Oh, I see--the deployment needs to be in the 'subscription-deployments' directory to target that scope.
> 
> In this case, all components except an Azure Policy definition and assignment are resource group scope. The Policy is only supported at the subscription scope. Should I move the whole sample to the 'subscription-deployments' directory?

Missed this response - yes, if the scope of your main template/bicep file starts at subscription scope, then it should move to that directory

**Comment by mbrat2005** [comment]
Ok, I'll give that a try. Thanks!
________________________________

**Comment by mbrat2005** [comment]
@alex-frankel Trying again at the subscription scope, I still get the same permissions errors where the deploying identity doesn't appear to have permissions to create Resource Groups, VNETs, etc. 

The client '5991c0de-xxxx-xxxx-xxxx-xxxxxxxx' with object id '5991c0de-xxxx-xxxx-xxxx-xxxxxxxx' does not have permission to perform action 'Microsoft.Resources/subscriptions/resourceGroups/write' at scope '/subscriptions/0cec7090-xxxx-xxxx-xxxx-xxxxxxxx/resourceGroups/rg-avnm-sample'

**Pull request merged**
