### PR TITLE
Clarify that this template creates a Consumption logic app, not a Standard one

### PR DESCRIPTION
**Pull request by ecfan**
Azure now offers two types of logic apps, Consumption and Standard, which are different in many ways. This info should clarify that the template creates a Consumption logic app. Also included editorial and clarity edits to align with Microsoft style. Thanks!

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Clarify that the template creates a Consumption logic app, not the Standard version.
* Editorial and clarity updates to align with Microsoft style.
*

### CODE REVIEW

**Comment by ecfan** [comment]
Hi @jeffhollan, 

I'm updating the ReadMe for your [quickstart template](https://azure.microsoft.com/en-us/resources/templates/logic-app-create/) and don't know why some checks are unsuccessful? I'm not familiar with the template itself, but just needed to update the doc.

**Review by bmoore-msft — CHANGES_REQUESTED** [review]
Can you sync your branch with Azure/master - I think that's what's causing the failure...

**Comment by azure-quickstarts** [comment]
@ecfan - check this PR for updates that may be needed to documentation that references this sample.  [This is an automated message. You are receiving it because you are listed as the docOwner in metadata.json.]

**Comment by ecfan** [comment]
@bmoore-msft: Synced, thanks!

**Pull request merged**
