### PR TITLE
Add new deployment for ARM.

### PR DESCRIPTION
**Pull request by robinsh**
Add article and template for iot-hub-auto-route-messages. (missing screenshots)

### CODE REVIEW

**Comment by MCKLMT** [comment]
The deployment fails.
I think you have to fix a function name: https://github.com/robinsh/azure-quickstart-templates/blob/robinsh-arm-hub/101-iothub-auto-route-messages/azuredeploy.json#L14

Replace
```
subscription().subscriptionid
```
By
```
subscription().subscriptionId
```

**Comment by robinsh** [comment]
When trying to publish that quickstart, I get errors, so I assumed it wasn’t published. I’ll take a look at it today. Thanks for letting me know.
Robin

**Comment by MCKLMT** [comment]
@robinsh Let me know if you need help with the template.

**Comment by robinsh** [comment]
The template actually works, at least for me. “The Powers That Be” edited it after I submitted it, so I’ll have to deploy it and check for errors (like the one you found). This is part of a “horizontal article” coming showing how to use that template to create the resources and then run an application to send messages to the hub, and see them be routed to storage. The real problem is getting the template pushed to the repo, as it gives a lot of strange error messages that I haven’t figured out how to fix yet. That’s why I was surprised to see that it’s in the repo. What good is it to give fatal error messages if it’s going to publish anyway??

**Comment by robinsh** [comment]
Can you let me know where you see that? I looked at azure/azure-quickstart-templates and don’t see it in there. Is it in the private repo?
Robin

**Comment by MCKLMT** [comment]
image
In the Azure Pipeline

**Comment by robinsh** [comment]
Doesn’t the little red x on that line mean it failed? Why would you pull it if it failed? (Genuinely interested.)

**Comment by MCKLMT** [comment]
Each template should follow best practices which are tested before the deployment. 
In your case, the deployment also fails.

**Comment by robinsh** [comment]
Then why can you see it? I wouldn’t think it would how a deployment that failed. I know I’m bad at GIT, but generally that’s true!

**Comment by robinsh** [comment]
So here's the deal. If you haven't published the template, and you refer to it in your readme file or in the how-to article, it won't build because your article can't find the template If you publish the template and parameter files first, thinking you will publish the how-to article later, they won't publish unless you have all the files, including a readme. This push should have the template, the parameters file, the metadata json, and a readme file (which is not the how-to unless a bunch of the other templates). Hopefully this will work.

**Comment by MCKLMT** [comment]
Why opening multiple pull requests? The regular process is to open a pull request from a single branch and update this branch with your modifications. You have now 4 pull requests opened for the same template, right?

**Comment by robinsh** [comment]
Thank you for your feedback.

Robin

**Comment by robinsh** [comment]
Did you put in PRs against my branch(es) ? Are you mcklmt? I would appreciate it in the future if you would not edit my work while I’m still working on it. Seriously, dude.

**Comment by MCKLMT** [comment]
Apologies it was a mistake.

**Comment by robinsh** [comment]
Abandon in favor of the lasttry branch.

**Comment by robinsh** [comment]
Ok. I have half-committed changes that I can’t see in the repo, but they come out if I merge something else in there. I’ve removed most of the extras now, and hopefully am working on the (final) changes.

Robin

**Pull request closed without merging**
