### PR TITLE
adding premium redis templates

### PR DESCRIPTION
**Pull request by tfitzmac**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@tfitzmac__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (tomfitz). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@tfitzmac Looks good mostly. To clarify, what's the difference between vnet-cluster and non cluster templates?

**Comment by tfitzmac** [comment]
@singhkay I have added more to the metadata and readme to clarify how the templates differ from each other. I also added a 4th template which is the last of the templates for now.

**Comment by tfitzmac** [comment]
@singhkay I have removed the template that provided almost duplicate functionality. And, revised the parameter description to describe both uses in the remaining template.

**Comment by tfitzmac** [comment]
@singhkay - I made the same parameter name change in these templates as the other redis template yesterday.

**Comment by singhkay** [comment]
THanks @tfitzmac! merged

**Pull request merged**
