### PR TITLE
Updated API's used for blockchain templates

### PR DESCRIPTION
**Pull request by gruve-p**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [X] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Updated all API's used in azuredeploy.json to match the versions used on https://github.com/Azure/azure-quickstart-templates/pull/8811
* Reorder coin names on alphabetical order

### CODE REVIEW

**Comment by gruve-p** [comment]
@Duality-CDOO @bmoore-msft 

Anyone attempting to deploy using the blockchain templates currently will not be able to set up any node (tested with Bitcoin and Groestlcoin) because of newuserscript failing/time-out.

This PR bumps the API's but I am not sure if this will fix the newuserscript issue.

**Comment by bmoore-msft** [comment]
What change specifically?  The diff looks rather benign...

**Comment by gruve-p** [comment]
The `apiVersion` changes, but not sure if that will solve the newuserscript issue

**Comment by bmoore-msft** [comment]
ok, this looks better - let's see how the pipeline finishes...

And then are you getting a different/new error when deployed outside the pipeline?

**Comment by gruve-p** [comment]
That is correct. Outside the pipelines the deployment fails with a time out on the newuserscript extension. I hope by bumping the apiversion the issue will be solved.

**Comment by gruve-p** [comment]
Pipeline finishes successfull

**Pull request merged**
