### PR TITLE
Updating API version and freshness dates

### PR DESCRIPTION
**Pull request by GarethBradshawMSFT**

### CODE REVIEW

**Comment by singhkay** [comment]
@GarethBradshawMSFT Looks like there are merge conflicts with these changes. You'll need to resolve these before Github allows me to merge these changes.

**Comment by GarethBradshawMSFT** [comment]
@singhkay it looks like the automation is testing the template and it's failing because the auto-generated parameter values (GEN-UNIQUE0/1/2) are not a valid DNS names.  Is there a way to go around that?

**Comment by singhkay** [comment]
@GarethBradshawMSFT We'll skip the acomghbot error messages because of the new pre-flight validation chechking and rely on the TravisCI messages. But to get the TravisCI testing started we need to get the merge conflicts resolved.

**Comment by singhkay** [comment]
@GarethBradshawMSFT Make sure you've read https://github.com/Azure/azure-quickstart-templates/tree/master/1-CONTRIBUTION-GUIDE#travis-ci and updated template parameter files accordingly. The CI can't test templates that require existing resources. If this is the case with your templates, we'll skip the CI and merge.

**Comment by GarethBradshawMSFT** [comment]
@singhkay I've checked the parameter files and they all contain the needed 'GEN-UNIQUE' entries.  The Travis CI seems to be failing on the VM example.  It's complaining about a long running operation, I've run the example myself through PowerShell and it deploys fine so I think it's just Travis CI timing out.

**Comment by singhkay** [comment]
@GarethBradshawMSFT Thanks for testing. Looks like only one template is failing in the CI.

**Pull request merged**
