### PR TITLE
couchbase server 4.1 deployment with additional parameters for servic…

### PR DESCRIPTION
**Pull request by cihanb**
### Changelog
* added new parameters for services and index_ram_quota to cluster-init an add-node
* changed downloaded packages and binary URL

### Description of the change
adapted couchbase-on-ubuntu template to the latest couchbase server 4.1 version. added new settings and required parameters.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@cihanb__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@cihanb__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by singhkay** [comment]
@cihanb Could you please update the existing template with 4.1 install instead of creating a new template? We can chat about more enhancements to that template if that's what you have in mind. The URLs to the template are dependent on the folder name, so when a new version of couchbase comes out, updating the folder name to that will break the current URL

**Comment by cihanb** [comment]
ok got it. I will see if there is any easy way to get the install to be version agnostic. new pull request coming soon.
thanks
-cihan

**Comment by singhkay** [comment]
@cihanb Thanks!

**Pull request closed without merging**
