### PR TITLE
Updates ARM template files - Machine Learning

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template used in ARM template [How-to guide](https://docs.microsoft.com/azure/machine-learning/how-to-create-workspace-template).
- Adds quickstart article's author to `docOwner` in _metadata.json_.
- Fixes headers in _README.md_.
- Fixes order of template's `resources` properties based on best practices guidance.
- Updates resource `type` to the latest `apiVersion`.

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@Blackmist - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
Verified that the best practices error message isn't caused by changes in this pull request. Prior merged pull request shows the same message.

**Comment by bmoore-msft** [comment]
@Blackmist - check this PR for updates that may be needed to documentation that references this sample.

**Comment by Blackmist** [comment]
@bmoore-msft looks OK. #sign-off

**Pull request merged**
