### PR TITLE
Updates ARM template files - API for FHIR

### PR DESCRIPTION
**Pull request by davidsmatlak**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

- Updates template used in ARM template [quickstart](https://docs.microsoft.com/azure/healthcare-apis/fhir-paas-arm-template-quickstart?tabs=azure-portal) article.
- Adds quickstart article's author to `docOwner` in _metadata.json_.
- Updates _README.md_ with link to the quickstart article, fixes broken link.
- Updates resource `type` to the latest `apiVersion`.
- Fixes indentation.

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@mgblythe - check this PR for updates that may be needed to documentation that references this sample.

**Comment by bmoore-msft** [comment]
@mgblythe - check this PR for updates that may be needed to documentation that references this sample.

**Comment by davidsmatlak** [comment]
Changes `Microsoft.HealthcareApis/services` to `apiVersion` **2020-03-15**. I didn't change Line 43 for the best practices issue for _azuredeploy.json_ because that would revert a change from August 19, 2020 on PR 7837 commit `f528de0`.

**Comment by bmoore-msft** [comment]
@mgblythe - check this PR for updates that may be needed to documentation that references this sample.

**Pull request merged**
