### PR TITLE
Adding new reporting views

### PR DESCRIPTION
**Pull request by adityabalaji-msft**
### Best Practice Checklist
Check these items before submitting a PR... See the Contribution Guide for the full detail: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md 

1. uri's compatible with all clouds (Stack, China, Government)
1. Staged artifacts use _artifactsLocation & _artifactsLocationSasToken
1. Use a parameter for resource locations with the defaultValue set to resourceGroup().location
1. Folder names for artifacts (nestedtemplates, scripts, DSC)
1. Use literal values for apiVersion (no variables)
1. Parameter files (GEN-UNIQUE for value generation and no "changemeplease" values)
1. $schema and other uris use https
1. Use uniqueString() whenever possible to generate names for resources.  While this is not required, it's one of the most common failure points in a deployment. 
1. Update the metadata.json with the current date

For details: https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

### Changelog

*
*
*

### CODE REVIEW

**Comment by adityabalaji-msft** [comment]
#sign-off

**Comment by adityabalaji-msft** [comment]
@bmoore-msft @krnese Could you help me understand why the Azure-QuickStart-Templates-Public test keeps failing for me, and what I can do to resolve it? (I do not have access to the "Details" screen, hence there is no clear error code for me to work with). The template works when I manually deploy the same on my LA workspaces.

When I ran this test with some existing working templates (eg., adding a minor change like ',' to a Readme file and creating a draft PR), the Azure-QuickStart-Templates-Public test failed in those cases as well. Has there been a change in the way PR validation is done in the backend?

Would be great if you could direct me to a solution to this issue. Thanks!

**Comment by bmoore-msft** [comment]
What do you see when you try to access the build results? (it's a public AzDO account)

**Comment by adityabalaji-msft** [comment]
@bmoore-msft  Looks like it was a temporary issue. I am now able to access the results and can see the error. Will fix it. Thanks!

**Pull request closed without merging**
