### PR TITLE
Updated Title and custom deployment link

### PR DESCRIPTION
**Pull request by nilaydshah**
Updated Title and custom deployment link

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nilaydshah__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@nilaydshah We're testing the automated deployment bot. Does this template require any pre-setup before executing the template? If not can you edit the parameters file to include a valid set of values that can deploy this template successfully? Thanks!

**Comment by nilaydshah** [comment]
@singhkay , i tried deploying this template, and found that - policy is getting created successfully. But the response isn't proper. It returns empty guid. whereas we expect id, name etc mandatory fields returned as part of the response. That's why even we have got the policy created, template deployment says Failed with following message: "The response for resource had empty or invalid content." 
What should we do in such case?

**Comment by singhkay** [comment]
@nilaydshah Is the empty response returned from the backup service?

**Comment by nilaydshah** [comment]
@singhkay yes.

**Comment by singhkay** [comment]
@nilaydshah I think this should be fixed on the service side so that the template responds as succeeded

**Pull request merged**
