### PR TITLE
Create Codespace Container

### PR DESCRIPTION
**Pull request by dciborow**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

During a PR, users may select to open the repository into a Codespace. This allows users to make remote edits and to regenerate files without the need for a local setup.

image

## Changelog

* Creating [Codespace](https://github.com/features/codespaces) Configuration so that users can open the repository in code space and run commands such as "az bicep build"

### CODE REVIEW

**Comment by dciborow** [comment]
@bmoore-msft should I appease the build system and create the files that it is asking for here?

**Comment by bmoore-msft** [comment]
No the pipeline doesn't really check any PR that's not a sample... so you can ignore anything the pipeline tells you...

We do need to figure out how to get the sas files out of the PR though.

**Comment by dciborow** [comment]
This PR is ready for completion.

**Review by Kimj2539 — COMMENTED** [review]
#12408

**Pull request merged**
