### PR TITLE
Location fix

### PR DESCRIPTION
**Pull request by marcvaneijk**
Changed resource location from parameter to resourceGroup().location.
Deleted location parameter from deployment template and parameter file.

### CODE REVIEW

**Comment by singhkay** [comment]
@marcvaneijk error `AssertionError: windows-server-containers-preview/metadata.json - #/itemDisplayName:Failed "maxLength" criteria`

**Comment by marcvaneijk** [comment]
@singhkay 
- fixed maxLength on metadata.json itemDisplayName
- storageAccountName from param to var
- replaced disk endpoints to dynamic
- removed storageAccountName from param file
- updated param file with placeholders

**Comment by singhkay** [comment]
@marcvaneijk merge conflicts

**Comment by marcvaneijk** [comment]
@singhkay fixed merge conflict

**Pull request merged**
