### PR TITLE
CoreOS + fleet template improvements

### PR DESCRIPTION
**Pull request by EgoAleSum**
The CoreOS + fleet template was using etcd, which is deprecated in favour of etcd2. Also, the documentation has been fixed to use the new format for SSH keys, and clarification on the role of the discoveryUrl.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@EgoAleSum__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (asegala). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
@EgoAleSum Awesome! 

Adding @nmackenzie who originally wrote this for review

**Comment by nmackenzie** [comment]
The deployment worked for me. Thanks for the pull request.

**Comment by singhkay** [comment]
Thanks @nmackenzie! merged

**Pull request merged**
