### PR TITLE
use nohup to run in background

### PR DESCRIPTION
**Pull request by john-connor**
use nohup to run in background

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@john-connor__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by singhkay** [comment]
lgtm, merged

**Comment by john-connor** [comment]
How to get listed on: https://azure.microsoft.com/en-us/documentation/templates/ ?

**Comment by singhkay** [comment]
@john-connor It should have been listed already. Can you file a bug for the Azure.co m team to look at? You can use the [Request Form](https://acomportal.azure.net/#Workspaces/All/dashboard) or via [UserSnap extension for Chrome](http://acomdocs.azurewebsites.net/articles/workitems-usersnap-get-started/)

**Comment by john-connor** [comment]
I tried both links in several browsers (signed in and signed out) and get:

Sorry, but we’re having trouble signing you in.
We received a bad request.

**Pull request merged**
