### PR TITLE
Added NEM Infrastructure Server template (docker-nem)

### PR DESCRIPTION
**Pull request by patmast3r**
### Changelog
* we've added docker-nem
* NEM is a blockchain platform (lots of details in the readme)
* we we'ren't sure wether or not to already change that paths for the deploy buttons so we left it for now.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@patmast3r__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@patmast3r__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by ViralWallet** [comment]
Preparations for deployment and compatibility, cross platform reverse compatibility.

**Comment by patmast3r** [comment]
@ViralWallet Sure you're commenting on the right pull-request ? Care to elaborate ?

**Comment by patmast3r** [comment]
We are hereby retracting our application for the time being due to disagreement about the cla. I've also notified the cla team via email.

**Pull request closed without merging**
