### PR TITLE
Updates to ev3 and HDI versions

### PR DESCRIPTION
**Pull request by guyhay**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by bmoore-msft** [comment]
@guyhay - looks like this one has a prereq of an existing storageAccount (and there's no prereq template)

**Comment by crlosmen** [comment]
I Don't whats it that?

**Comment by guyhay** [comment]
Fixed in parallel update https://github.com/Azure/azure-quickstart-templates/pull/10920

**Comment by guyhay** [comment]
Fixed in parallel update #10920

**Pull request closed without merging**
