### PR TITLE
Update azuredeploy.json

### PR DESCRIPTION
**Pull request by lakmeedee**
Changed the sku to a Gen2 SKU as Gen1 and Gen2 VMs have feature parity

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [x] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by lakmeedee** [comment]
#sign-off

**Comment by lakmeedee** [comment]
#sign-off

**Comment by mimckitt** [comment]
#sign-off

**Comment by mimckitt** [comment]
@bmoore-msft anything else we need to do in order to get this merged?

**Comment by bmoore-msft** [comment]
https://schema.management.azure.com/schemas/2021-11-01/deploymentTemplate.json - is not a valid schema

**Pull request closed without merging**
